force-app/main/default/objects/Retail_Customer__c/Retail_Customer__c.object-meta.xml
<CustomObject>
    <label>Retail Customer</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Retail Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Customer__c/fields/Link_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Link_Lead_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link Lead ID</label>
    <referenceTo>Retail_Lead__c</referenceTo>
    <relationshipLabel>Retail Customers</relationshipLabel>
    <relationshipName>Retail_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/fields/Is_Converted__c.field-meta.xml
<CustomField>
    <fullName>Is_Converted__c</fullName>
    <label>Is Converted?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Retail_Lead_District__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>Retail_District__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Retail_Lead_Taluka__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_Taluka__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Taluka</label>
    <referenceTo>Retail_Taluka__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/RetailLeadState__c.field-meta.xml
<CustomField>
    <fullName>RetailLeadState__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>Retail_State__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Seller_Name__c.field-meta.xml
<CustomField>
    <fullName>Seller_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Avana Retail customer/customers from which this lead is purchasing Avana Retail  products</inlineHelpText>
    <label>Seller Name</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Product__c/Retail_Lead_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Lead Product</label>
    <nameField>
        <displayFormat>RLP-{0000}</displayFormat>
        <label>Retail Lead Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Lead Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead_Product__c/fields/Retail_Lead_Visit__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Lead Visit</label>
    <referenceTo>Retail_Lead_Visit__c</referenceTo>
    <relationshipLabel>Retail Lead Products</relationshipLabel>
    <relationshipName>Retail_Lead_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Product__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Lead Products</relationshipLabel>
    <relationshipName>Retail_Lead_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/Retail_Lead_Visit__c.object-meta.xml
<CustomObject>
    <label>Retail Lead Visit</label>
    <nameField>
        <displayFormat>RLV-{0000}</displayFormat>
        <label>Visit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Lead Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Retail_Lead__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Level_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Interest__c</fullName>
    <label>Level of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold Lead</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Incomplete Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Linked_Customer__c.field-meta.xml
<CustomField>
    <fullName>Linked_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Customer</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order ID</label>
    <referenceTo>Retail_Order__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Other_Reason_For_Cold__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason_For_Cold__c</fullName>
    <label>Other Reason For Cold</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Reason_for_Cold_Lead__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Cold_Lead__c</fullName>
    <label>Reason for Cold Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Price too high</fullName>
            </value>
            <value>
                <fullName>Already bought from elsewhere</fullName>
            </value>
            <value>
                <fullName>Delivery too slow</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Seller_ID__c.field-meta.xml
<CustomField>
    <fullName>Seller_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller ID</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Lead Visits (Seller ID)</relationshipLabel>
    <relationshipName>Retail_Lead_Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product_Group__c/Retail_Product_Group__c.object-meta.xml
<CustomObject>
    <label>Retail Product Group</label>
    <nameField>
        <label>Product Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewOverrideLeadVisitController.cls
public class NewOverrideLeadVisitController {
    @AuraEnabled
    public static String insertLeadVisitWithProduct(List<Retail_Lead_Product__c> productList, Retail_Lead_Visit__c leadVisit,Id leadId) {
        try {
            List<Retail_Lead_Product__c> lstiv = new List<Retail_Lead_Product__c>();
				System.debug('productList'+productList);
            System.debug('leadVisit'+leadVisit);
            if (Schema.sObjectType.Retail_Lead_Visit__c.isCreateable()) {
                upsert leadVisit;
            }

            String leadVisitId = leadVisit.Id;
            if(leadId!=null){
                Retail_Lead__c leadDetails=[SELECT Id,RetailLeadState__c, Retail_Lead_District__c,Is_Converted__c, Retail_Lead_Taluka__c,Village__c,Lead_Name__c,Phone__c FROM Retail_Lead__c WHERE Id = :leadId LIMIT 1];
					leadDetails.Is_Converted__c='Yes';
            		update leadDetails;
            System.debug('leadDetails'+leadDetails);
        }
            
            for (Retail_Lead_Product__c pro : productList) {
                Retail_Lead_Product__c product = new Retail_Lead_Product__c();
                System.debug('pro===='+pro.Name);
                product.Retail_Lead_Visit__c = leadVisit.Id;
                product.Retail_Product_Group__c = pro.Retail_Product_Group__c;
                product.Quantity__c = pro.Quantity__c;
                lstiv.add(product);
            }

            if (!lstiv.isEmpty() && Schema.sObjectType.Retail_Lead_Product__c.isCreateable()) {
                upsert lstiv;
            }

            return leadVisitId;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String insertLeadVisitOnly(Id leadId,Retail_Lead_Visit__c leadVisit) {
          System.debug('leadId'+leadId);
         Retail_Lead__c leadDetails=new Retail_Lead__c();
        
        try {
            if(leadId!=null){
               leadDetails=[SELECT Id,RetailLeadState__c, Retail_Lead_District__c,Is_Converted__c, Retail_Lead_Taluka__c,Village__c,Lead_Name__c,Phone__c FROM Retail_Lead__c WHERE Id = :leadId LIMIT 1];
					leadDetails.Is_Converted__c='Yes';
            		update leadDetails;
            System.debug('leadDetails'+leadDetails);
        }
            if (Schema.sObjectType.Retail_Lead_Visit__c.isCreateable()) {
                upsert leadVisit;
            }

             String leadVisitId = leadVisit.Id;
           return leadVisitId;  
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
     @AuraEnabled
     public static String insertLeadVisit(Id leadId,Retail_Lead_Visit__c leadVisit) {
          System.debug('leadId'+leadId);
             try {
            if (Schema.sObjectType.Retail_Lead_Visit__c.isCreateable()) {
                upsert leadVisit;
            }

             String leadVisitId = leadVisit.Id;
           return leadVisitId;  
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        
    }   

    @AuraEnabled(cacheable = true)
    public static Retail_Product_Group__c getProductGroupDetails(String productGroupId) {
        System.debug('productGroupId====' + productGroupId);
        Retail_Product_Group__c productGroup = [SELECT Id, Name FROM Retail_Product_Group__c WHERE Id = :productGroupId WITH SECURITY_ENFORCED];
        System.debug('productGroup==========' + productGroup);
        return productGroup;
    }
   
        @AuraEnabled(cacheable = true)
         public static Retail_Lead_Visit__c getLeadVisit(String leadVisitId) {
             
			Retail_Lead_Visit__c leadVisit=[SELECT Id,Date__c, Order_ID__c,Follow_up_Date__c, Lead_Name__c, Lead_Type__c, Level_of_Interest__c, Linked_Customer__c, Seller_ID__c, Sale_Type__c, Retail_Product_Group__c,Other_Reason_For_Cold__c,Reason_for_Cold_Lead__c FROM Retail_Lead_Visit__c WHERE Id =:leadVisitId  WITH SECURITY_ENFORCED ];
             return leadVisit;
         }
    @AuraEnabled(cacheable = true)
	public static Retail_Customer__c getLinkCustomer(String leadId) {
    List<Retail_Customer__c> linkCustomers = [SELECT Id, Link_Lead_ID__c FROM Retail_Customer__c WHERE Link_Lead_ID__c = :leadId LIMIT 1];
   
    if (!linkCustomers.isEmpty()) {
        return linkCustomers[0];
      
    }
    
    return null;
}
    @AuraEnabled(cacheable = true)
public static Retail_Lead__c getLinkCustomerLead(String leadId) {
    List<Retail_Lead__c>  leadDetails = [SELECT Id, Lead_Name__c,Lead_Type__c,Seller_Name__c FROM Retail_Lead__c WHERE Id =:leadId LIMIT 1];
    
    if (!leadDetails.isEmpty()) {
       
        return leadDetails[0];
    }
    
    return leadDetails[0];
}

}