force-app/main/default/objects/Retail_Customer__c/Retail_Customer__c.object-meta.xml
<CustomObject>
    <label>Retail Customer</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Retail Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Customer__c/fields/Retail_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Retail_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Code</label>
    <referenceTo>Retail_Warehouse__c</referenceTo>
    <relationshipLabel>Retail Customers</relationshipLabel>
    <relationshipName>Retail_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_District__c/Retail_District__c.object-meta.xml
<CustomObject>
    <label>Retail District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead_Product__c/Retail_Lead_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Lead Product</label>
    <nameField>
        <displayFormat>RLP-{0000}</displayFormat>
        <label>Retail Lead Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Lead Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead_Product__c/fields/Retail_Lead_Visit__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Lead Visit</label>
    <referenceTo>Retail_Lead_Visit__c</referenceTo>
    <relationshipLabel>Retail Lead Products</relationshipLabel>
    <relationshipName>Retail_Lead_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Product__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Lead Products</relationshipLabel>
    <relationshipName>Retail_Lead_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/Retail_Lead_Visit__c.object-meta.xml
<CustomObject>
    <label>Retail Lead Visit</label>
    <nameField>
        <displayFormat>RLV-{0000}</displayFormat>
        <label>Visit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Lead Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/Retail_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Product__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Products</relationshipLabel>
    <relationshipName>Retail_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product_Group__c/Retail_Product_Group__c.object-meta.xml
<CustomObject>
    <label>Retail Product Group</label>
    <nameField>
        <label>Product Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_State__c/Retail_State__c.object-meta.xml
<CustomObject>
    <label>Retail State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Taluka__c/Retail_Taluka__c.object-meta.xml
<CustomObject>
    <label>Retail Taluka</label>
    <nameField>
        <label>Taluka Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Talukas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Warehouse__c/Retail_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Retail Warehouse</label>
    <nameField>
        <label>Retail Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewOverrideLeadVisitController_TestClass.cls
@isTest
public class NewOverrideLeadVisitController_TestClass {
    @isTest
    public  static void testingMethod(){
        Retail_State__c retailState = TestDataFactory.createRetailState('Telangana');
        Retail_District__c retailDistrict =TestDataFactory.createRetailDistrict('Ranga Reddy',retailState.Id);
        Retail_Taluka__c retailTaluka =TestDataFactory.createRetailTaluka('Manakondur', retailDistrict.Id, retailState.Id);
        Retail_Customer__c retailCustomer = TestDataFactory.createRetailCustomer();
        Retail_Lead__c retailLead =TestDataFactory.createRetailLead('Other', 'Test Retail Lead', 'Distributor', 'India(+91)', '9432156987', 'Test Village Adilabad', retailTaluka.Id, retailDistrict.Id,retailState.Id,retailCustomer.Id,'Direct');
        Retail_Lead_Visit__c retailLeadVisit =TestDataFactory.createRetailLeadVisit(retailLead.Id);
        Retail_Warehouse__c retailWarehouse = TestDataFactory.createRetailWarehouse();
        Retail_Product_Group__c retailProductGroup = TestDataFactory.createRetailProductGroup();
        Retail_Product__c retailProduct  = TestDataFactory.createRetailProduct(retailProductGroup.Id);
        Retail_Lead_Product__c retailLeadPrd=TestDataFactory.createRetailPrd(retailProductGroup.Id);
        
        List<Retail_Warehouse__c> createdretailWarehouse = [SELECT Id,Name From Retail_Warehouse__c where Name='Test WarHouse'];
        System.assert(!createdretailWarehouse.isEmpty(),'List should not be empty');
        Assert.areEqual('Test WarHouse', retailWarehouse.Name);
        
        List<Retail_Lead_Product__c> retailLeadPrdList= new List<Retail_Lead_Product__c>();
        retailLeadPrdList.add(retailLeadPrd);
        
        Test.startTest();
        NewOverrideLeadVisitController.insertLeadVisitWithProduct(retailLeadPrdList,retailLeadVisit,retailLead.Id);
        NewOverrideLeadVisitController.insertLeadVisitOnly(retailLead.Id,retailLeadVisit);
        NewOverrideLeadVisitController.insertLeadVisit(retailLead.Id,retailLeadVisit);
        NewOverrideLeadVisitController.getLeadVisit(retailLeadVisit.Id);
            NewOverrideLeadVisitController.getLinkCustomer(retailCustomer.Id);
        NewOverrideLeadVisitController.getLinkCustomerLead(retailLead.Id);
        NewOverrideLeadVisitController.getProductGroupDetails(retailProductGroup.Id);
        Test.stopTest();
        
    }
}