force-app/main/default/objects/Retail_Customer__c/Retail_Customer__c.object-meta.xml
<CustomObject>
    <label>Retail Customer</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Retail Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Customer__c/fields/Link_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Link_Lead_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link Lead ID</label>
    <referenceTo>Retail_Lead__c</referenceTo>
    <relationshipLabel>Retail Customers</relationshipLabel>
    <relationshipName>Retail_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/fields/Is_Converted__c.field-meta.xml
<CustomField>
    <fullName>Is_Converted__c</fullName>
    <label>Is Converted?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Retail_Lead_District__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>Retail_District__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Retail_Lead_Taluka__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_Taluka__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Taluka</label>
    <referenceTo>Retail_Taluka__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/RetailLeadState__c.field-meta.xml
<CustomField>
    <fullName>RetailLeadState__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>Retail_State__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/Retail_Order__c.object-meta.xml
<CustomObject>
    <label>Retail Order</label>
    <nameField>
        <displayFormat>RO-{0000}</displayFormat>
        <label>Retail Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Retail_Customer__c.field-meta.xml
<CustomField>
    <fullName>Retail_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Orders</relationshipLabel>
    <relationshipName>Retail_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerControllerForNew.cls
public class CustomerControllerForNew {
     @AuraEnabled(cacheable=true)
    public static Retail_Lead__c getLeadDetails(Id masterId) {
        Retail_Lead__c leadDetails=[SELECT Id,RetailLeadState__c, Retail_Lead_District__c, Retail_Lead_Taluka__c,Village__c,Lead_Name__c,Phone__c FROM Retail_Lead__c WHERE Id = :masterId LIMIT 1];
    return leadDetails;
    }
     @AuraEnabled(cacheable=true)
     public static Retail_Customer__c getCustomerDetails(Id masterId) {
         System.debug('masterId==========='+masterId);
        	Retail_Customer__c customerDetails=new Retail_Customer__c();
         if(masterId!=null || masterId!=''){
       List<Retail_Customer__c> customerDetails1=[SELECT Id,Link_Lead_ID__c FROM Retail_Customer__c WHERE Link_Lead_ID__c = :masterId LIMIT 1];
         System.debug('customerDetails============'+customerDetails);
            if (customerDetails1.size()>0){
                customerDetails=customerDetails1[0];
             return customerDetails;
             }
             else{
                  return customerDetails;
             }
         }
        return customerDetails;
    }
      @AuraEnabled
    public static Retail_Lead__c updateLead(Id leadId) {
        System.debug('leadId'+leadId);
        Retail_Lead__c leadDetails=new Retail_Lead__c();
        if(leadId!=null){
                   leadDetails=[SELECT Id,RetailLeadState__c, Retail_Lead_District__c,Is_Converted__c, Retail_Lead_Taluka__c,Village__c,Lead_Name__c,Phone__c FROM Retail_Lead__c WHERE Id = :leadId LIMIT 1];
					leadDetails.Is_Converted__c='Yes';
            		update leadDetails;
            System.debug('leadDetails'+leadDetails);
        }
        
    return leadDetails;
    }
     @AuraEnabled(cacheable=true)
     public static Retail_Customer__c getCustomerPhoneDetails(String phone) {
         System.debug('phone==========='+phone);
        	Retail_Customer__c customerDetails=new Retail_Customer__c();
         if(phone!=null || phone!=''){
       List<Retail_Customer__c> customerDetails1=[SELECT Id,Link_Lead_ID__c,Phone_Number__c FROM Retail_Customer__c WHERE Phone_Number__c = :phone LIMIT 1];
         System.debug('customerDetails============'+customerDetails);
            if (customerDetails1.size()>0){
                customerDetails=customerDetails1[0];
             return customerDetails;
             }
             else{
                  return customerDetails;
             }
         }
        return customerDetails;
    }
      @AuraEnabled(cacheable=true)
     public static Retail_Customer__c getCustomerEmailDeatils(String email) {
         System.debug('email==========='+email);
        	Retail_Customer__c customerDetails=new Retail_Customer__c();
         if(email!=null || email!=''){
       List<Retail_Customer__c> customerDetails1=[SELECT Id,Link_Lead_ID__c,Email__c FROM Retail_Customer__c WHERE Email__c = :email LIMIT 1];
         System.debug('customerDetails============'+customerDetails);
            if (customerDetails1.size()>0){
                customerDetails=customerDetails1[0];
             return customerDetails;
             }
             else{
                  return customerDetails;
             }
         }
        return customerDetails;
    }
    	@AuraEnabled(cacheable=true)
      public static Retail_Order__c OrderRelatedCustomer(Id recordId) {
        System.debug('recordId'+recordId);
        Retail_Order__c orderDetails=new Retail_Order__c();
        if(recordId!=null){
               orderDetails=[SELECT Id,Retail_Customer__c,Order_Date__c from Retail_Order__c where Retail_Customer__c=:recordId ORDER BY Order_Date__c DESC limit 1];
            System.debug('orderDetails'+orderDetails);
        }
          if(orderDetails.Order_Date__c!=null){
               return orderDetails;
          }
    return orderDetails;
    }
    
}