force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>Com-{000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <label>Product Information</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Complaints</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Complaint__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed without OTP</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <inlineHelpText>Mobile Number Should be 10 Digits</inlineHelpText>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Enquiry Created</fullName>
            </value>
            <value>
                <fullName>Not Converted</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ComplainTTriggerHandler.cls
public class ComplainTTriggerHandler extends TriggerHandler {
    public override void beforeUpdate(){
        System.debug('before update::::');
        Map<Id,String> mapofAccount=new Map<Id,String>();
        List<Complaint__c> complist=new List<Complaint__c>();
        Complaint__c compOld;
        Set<Id> setcmpId=new Set<Id>();
        for(Complaint__c compNew:(List<Complaint__c>)trigger.new){
            compOld=(Complaint__c)trigger.oldMap.get(compNew.Id);
            if(compNew.Stages__c!=compOld.Stages__c && compNew.Stages__c=='Closed without OTP'){
                setcmpId.add(compNew.Id);
            }
            
        }
        System.debug('set of complaintId::'+setcmpId);
        if(setcmpId.size()>0 && setcmpId!=null){
         complist=[select id,Enquiry__c,Enquiry__r.Lead__c,Enquiry__r.Lead__r.Mobile_Number__c from Complaint__c where id in:setcmpId];
        System.debug('complist::::'+complist);
        }
        if(complist!=null &&complist.size()>0){
            for(Complaint__c cc:complist){
                mapofAccount.put(cc.Enquiry__c,cc.Enquiry__r.Lead__r.Mobile_Number__c);
            }
        }
        System.debug('mapofAccount:::'+mapofAccount);
        
        for(Complaint__c compNew:(List<Complaint__c>)trigger.new){
            compOld=(Complaint__c)trigger.oldMap.get(compNew.Id);
            if(compNew.Stages__c!=compOld.Stages__c && compNew.Stages__c=='Closed without OTP'){
                 System.debug('Inside Close Without OTP:::'+compNew.Enquiry__c);
                 System.debug('mapofAccount.containsKey(compNew.Enquiry__r.Lead__c)::'+mapofAccount.containsKey(compNew.Enquiry__c));
                if(compNew.Enquiry__c!=null && mapofAccount.containsKey(compNew.Enquiry__c)){
                    System.debug('Inside class call method:::::');
                    OTPSend.sendOtp(mapofAccount.get(compNew.Enquiry__c),compNew.Id);                    
                }
                else{
                    compNew.addError('Please Update Lead in Product Informations in this complaint');
                }
                
            }
            
        }
   
    }

}