force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>Com-{000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed without OTP</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Detail__c/Integration_Detail__c.object-meta.xml
<CustomObject>
    <label>Integration Detail</label>
    <nameField>
        <label>OTP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Detail__c/fields/Complaint__c.field-meta.xml
<CustomField>
    <fullName>Complaint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Complaint</label>
    <referenceTo>Complaint__c</referenceTo>
    <relationshipLabel>Integration Details</relationshipLabel>
    <relationshipName>Integration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Detail__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Integration_Detail__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ComplaintClose.cls
public with sharing class ComplaintClose {
    public ComplaintClose() {
        
    }
    @AuraEnabled
    public static string CloseComplaint(String ObjId,String OTPNO){
        System.debug('complaint Id::::'+ObjId);
        System.debug('OTP no::::'+OTPNO);
        List<Complaint__c> fetchComp=[select id,stages__c,IsClosed__c from Complaint__c where id=:ObjId ];
        List<Complaint__c> cclist=new List<Complaint__c>();
        if(fetchComp[0].stages__c=='Closed without OTP'){
            
            Integration_Detail__c checkIt=[select Name,Mobile_Phone__c,Response_Body__c,Complaint__c from Integration_Detail__c where Complaint__c=:ObjId order by createddate desc limit 1];
            
            if(checkIt.Name==OTPNO && checkIt.Name!=null){
                for(Complaint__c cc:fetchComp){
                    cc.IsClosed__c=true;
                    cc.stages__c='Closed with OTP';
                    cclist.add(cc);
                }
            }
            
            if(cclist.size()>0 && cclist!=null){
                update cclist;
                return 'success';
            }
            else{
                return 'error';
            }
        }
        else{
            return 'genpwd';
        }
        
        
    }
}