force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Achivement__c.field-meta.xml
<CustomField>
    <fullName>Achivement__c</fullName>
    <formula>Pondliner_Size_Requested_Required_Sq_Mt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Achivement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateRecordsBatch.cls
public class UpdateRecordsBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        return Database.getQueryLocator('SELECT Id,Achivement__c,Invoice_Date__c FROM Opportunity__c where Invoice_Date__c = LAST_N_MONTHS:3');
    }
    
    public void execute(Database.BatchableContext bc, List<Opportunity__c> scope) {
        
        update scope;
    }
    
    public void finish(Database.BatchableContext bc) {
        // Any post-processing logic can be added here
    }
}