force-app/main/default/objects/Retail_Order_Return_Form__c/Retail_Order_Return_Form__c.object-meta.xml
<CustomObject>
    <label>Retail Order Return Form</label>
    <nameField>
        <displayFormat>OR-{0000}</displayFormat>
        <label>Return ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Order Return Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order_Return_Form__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Sub Total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/Retail_Order_Return_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Order Return Product</label>
    <nameField>
        <displayFormat>RORP-{0000}</displayFormat>
        <label>Retail Order Return Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Order Return Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Discounted_Kg_Rate__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Kg_Rate__c</fullName>
    <label>Discounted Kg Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Discounted_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Unit_Price__c</fullName>
    <label>Discounted Unit Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Hole_Type__c.field-meta.xml
<CustomField>
    <fullName>Hole_Type__c</fullName>
    <label>Hole Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Straight</fullName>
            </value>
            <value>
                <fullName>parallel</fullName>
            </value>
            <value>
                <fullName>Zigzag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Net_Total_for_Product__c.field-meta.xml
<CustomField>
    <fullName>Net_Total_for_Product__c</fullName>
    <label>Net Total for Product</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Product_Discount__c.field-meta.xml
<CustomField>
    <fullName>Product_Discount__c</fullName>
    <label>Product Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Order Return Products</relationshipLabel>
    <relationshipName>Retail_Order_Return_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Products</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Retail_Product__c.Retail_Product_Group__c</field>
            <operation>equals</operation>
            <valueField>$Source.Product_Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Order Return Products</relationshipLabel>
    <relationshipName>Retail_Order_Return_Products1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Retail_Order_Return_Form__c.field-meta.xml
<CustomField>
    <fullName>Retail_Order_Return_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Order Return Form</label>
    <referenceTo>Retail_Order_Return_Form__c</referenceTo>
    <relationshipLabel>Retail Order Return Products</relationshipLabel>
    <relationshipName>Retail_Order_Return_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Return_Net_Total_for_Product__c.field-meta.xml
<CustomField>
    <fullName>Return_Net_Total_for_Product__c</fullName>
    <label>Return Net Total for Product</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Return_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Return_Quantity__c</fullName>
    <label>Return Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Return_Weight__c.field-meta.xml
<CustomField>
    <fullName>Return_Weight__c</fullName>
    <label>Return Weight</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Return_Product__c/fields/Std_Pkg_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Std_Pkg_Sizes__c</fullName>
    <label>Std Pkg Sizes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NewOverrideOrderReturnController.cls
public class NewOverrideOrderReturnController {
     @AuraEnabled
    public static String insertOrderWithProduct(List<Retail_Order_Return_Product__c> productList, Retail_Order_Return_Form__c order) {
        try {
            List<Retail_Order_Return_Product__c> lstiv = new List<Retail_Order_Return_Product__c>();
				System.debug('productList'+productList);
            System.debug('order'+order);
            if (Schema.sObjectType.Retail_Order_Return_Form__c.isCreateable()) {
                insert order;
            }            String orderId = order.Id;
            try{
             for (Retail_Order_Return_Product__c pro : productList) {
                Retail_Order_Return_Product__c product = new Retail_Order_Return_Product__c();
                System.debug('pro===='+pro.Name);
                product.Retail_Order_Return_Form__c = order.Id;
                product.Product_Group__c = pro.Product_Group__c;
                product.Products__c = pro.Products__c;
                product.Hole_Type__c = pro.Hole_Type__c;
                product.Hole_Spacing__c = pro.Hole_Spacing__c;
                product.Std_Pkg_Sizes__c = pro.Std_Pkg_Sizes__c;
                product.Quantity__c = pro.Quantity__c;
                product.Unit_Price__c = pro.Unit_Price__c;
                product.Kg_Rate__c = pro.Kg_Rate__c;
                product.Discounted_Kg_Rate__c = pro.Discounted_Kg_Rate__c;
                product.Weight_Kg__c = pro.Weight_Kg__c;
                product.Sub_Total__c = pro.Sub_Total__c;
                product.Product_Discount__c = pro.Product_Discount__c;
                product.Net_Total_for_Product__c = pro.Net_Total_for_Product__c;
                product.Return_Quantity__c = pro.Return_Quantity__c;
                product.Return_Weight__c = pro.Return_Weight__c;
                product.Return_Net_Total_for_Product__c = pro.Return_Net_Total_for_Product__c;
               
                lstiv.add(product);
            }
                if (!lstiv.isEmpty() && Schema.sObjectType.Retail_Order_Return_Product__c.isCreateable()) {
                insert lstiv;
            }
            }
             catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

            return orderId;
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
     @AuraEnabled(cacheable=true)
    public static List<Retail_Order_Return_Product__c> fetchProductList(String recordId) {
        System.debug('recordId55'+recordId);
        return [select id,Retail_Order_Return_Form__c ,Discounted_Kg_Rate__c , Discounted_Unit_Price__c, Hole_Spacing__c , Hole_Type__c, Kg_Rate__c, Name, Net_Total_for_Product__c,  Products__c , Product_Discount__c , Product_Group__c, Quantity__c, Std_Pkg_Sizes__c, Sub_Total__c, Weight_Kg__c ,Unit_Price__c ,Return_Net_Total_for_Product__c, Return_Quantity__c, Return_Weight__c from Retail_Order_Return_Product__c where Retail_Order_Return_Form__c =:recordId];
   }

}