force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>For the field team to log their daily visits.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {0}</displayFormat>
        <label>Visit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Interest_Level_New__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level_New__c</fullName>
    <label>Dealer Interest Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Not Interested in Pond Lining</fullName>
            </value>
            <value>
                <fullName>Not Interested - Working for Other Pond Lining Company</fullName>
            </value>
            <value>
                <fullName>Contact Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutocheckTestClass.cls
@isTest
public class AutocheckTestClass {
    static testMethod void testocc() {
                               Test.startTest();
                               Visit__c acc = new Visit__c(Interest_Level_New__c = 'Positive');
                               insert acc;
                               ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sub.id;
        content.origin = 'H';
        insert content;
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=acc.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        
        
        insert contentlink;
        Test.stopTest();                               

                   }

                }