force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>SKU Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Customer__c/Retail_Customer__c.object-meta.xml
<CustomObject>
    <label>Retail Customer</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Retail Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Customer__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>Retail_District__c</referenceTo>
    <relationshipLabel>Retail Customers</relationshipLabel>
    <relationshipName>Retail_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Customer__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Customer__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>Shop Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Customer__c/fields/Taluka__c.field-meta.xml
<CustomField>
    <fullName>Taluka__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Taluka</label>
    <referenceTo>Retail_Taluka__c</referenceTo>
    <relationshipLabel>Retail Customers</relationshipLabel>
    <relationshipName>Retail_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_District__c/Retail_District__c.object-meta.xml
<CustomObject>
    <label>Retail District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order__c/Retail_Order__c.object-meta.xml
<CustomObject>
    <label>Retail Order</label>
    <nameField>
        <displayFormat>RO-{0000}</displayFormat>
        <label>Retail Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Cash_on_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Cash_on_Delivery__c</fullName>
    <label>Cash on Delivery</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Dispatch_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dispatch Warehouse</label>
    <referenceTo>Retail_Warehouse__c</referenceTo>
    <relationshipLabel>Retail Orders (Dispatch Warehouse)</relationshipLabel>
    <relationshipName>Retail_Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Expected_Delivery_Date_Customer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery_Date_Customer__c</fullName>
    <label>Expected Delivery Date-Customer</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Freight_Charge_Bearer_values__c.field-meta.xml
<CustomField>
    <fullName>Freight_Charge_Bearer_values__c</fullName>
    <label>Freight Charge Bearer values</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avana</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Net_Total__c.field-meta.xml
<CustomField>
    <fullName>Net_Total__c</fullName>
    <label>Net Total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Order_Discount__c.field-meta.xml
<CustomField>
    <fullName>Order_Discount__c</fullName>
    <label>% Order Discount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Retail_Customer__c.field-meta.xml
<CustomField>
    <fullName>Retail_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Orders</relationshipLabel>
    <relationshipName>Retail_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Owner</label>
    <referenceTo>Retail_Employee__c</referenceTo>
    <relationshipLabel>Retail Orders</relationshipLabel>
    <relationshipName>Retail_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/Retail_Order_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Order Product</label>
    <nameField>
        <displayFormat>ROP-{0000}</displayFormat>
        <label>Retail Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Order Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order_Product__c/fields/Hole_Spacing__c.field-meta.xml
<CustomField>
    <fullName>Hole_Spacing__c</fullName>
    <label>Hole Spacing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/HoleType__c.field-meta.xml
<CustomField>
    <fullName>HoleType__c</fullName>
    <label>Hole Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Straight</fullName>
            </value>
            <value>
                <fullName>Parallel</fullName>
            </value>
            <value>
                <fullName>Zigzag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Kg_Rate__c.field-meta.xml
<CustomField>
    <fullName>Kg_Rate__c</fullName>
    <label>Kg Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Order Products</relationshipLabel>
    <relationshipName>Retail_Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Order Products</relationshipLabel>
    <relationshipName>Retail_Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Retail_Order__c.field-meta.xml
<CustomField>
    <fullName>Retail_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Order</label>
    <referenceTo>Retail_Order__c</referenceTo>
    <relationshipLabel>Retail Order Products</relationshipLabel>
    <relationshipName>Retail_Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Std_Pkg_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Std_Pkg_Sizes__c</fullName>
    <label>Std Pkg Sizes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_Kg__c</fullName>
    <label>Weight(Kg)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/Retail_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Taluka__c/Retail_Taluka__c.object-meta.xml
<CustomObject>
    <label>Retail Taluka</label>
    <nameField>
        <label>Taluka Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Talukas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Warehouse__c/Retail_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Retail Warehouse</label>
    <nameField>
        <label>Retail Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Product_Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avana Tank</fullName>
    </customValue>
    <customValue>
        <fullName>Biofloc Tank</fullName>
    </customValue>
    <customValue>
        <fullName>Leno Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Mulch Film</fullName>
    </customValue>
    <customValue>
        <fullName>Murughas Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Pond Liner</fullName>
    </customValue>
    <customValue>
        <fullName>Tarpaulin</fullName>
    </customValue>
    <customValue>
        <fullName>Thread</fullName>
    </customValue>
    <masterLabel>Product Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RetailOrderPdfController.cls
public class RetailOrderPdfController {
    
    public static Retail_Order__c retailOrder{get;set;}
    public static List<Retail_Order_Product__c> retailOrderList{get;set;}

    public RetailOrderPdfController(){
        String recId = ApexPages.CurrentPage().getParameters().get('id');
        retailOrder = [SELECT Id, OwnerId, Name, Sales_Owner__c, Net_Total__c, Order_Date__c, Freight_Charge_Bearer_values__c, Expected_Delivery_Date_Customer__c, 
                       Dispatch_Warehouse__c,Dispatch_Warehouse__r.Name,Retail_Customer__c,Retail_Customer__r.Name__c,Retail_Customer__r.District__c,
                       Retail_Customer__r.District__r.Name,Retail_Customer__r.Shop_Name__c,Retail_Customer__r.Taluka__c,Comments__c, Retail_Customer__r.Taluka__r.Name,Advance__c, 
                       Cash_on_Delivery__c, Credit__c, Sub_Total__c, Order_Discount__c FROM Retail_Order__c where Id =:recId];
        system.debug('retailOrder'+retailOrder);
        
        
         
        retailOrderList=[SELECT Id, Name, HoleType__c, Quantity__c, Unit_Price__c, Sub_Total__c, Retail_Order__c, Net_Total_for_Product__c, 
                         Product_Discount__c, Product__c,Product__r.Product_Name__c, Product_Group__c, Hole_Spacing__c, Std_Pkg_Sizes__c, Discounted_Unit_Price__c, 
                         Kg_Rate__c, Discounted_Kg_Rate__c, Weight_Kg__c FROM Retail_Order_Product__c where Retail_Order__c=:retailOrder.Id];
        
        system.debug('retailOrderList'+retailOrderList);
    }

}