force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lost_Lead__c.field-meta.xml
<CustomField>
    <fullName>Lost_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lost Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Contact Later</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnquiryTriggerHandler.cls
public class EnquiryTriggerHandler extends TriggerHandler{
    public override void afterUpdate(){
        Opportunity__c OldEnq;
        Set<Id> setLeadId= new Set<Id>();
        for(Opportunity__c newEnq: (List<Opportunity__c>)trigger.new){
            OldEnq=(Opportunity__c)trigger.oldMap.get(newEnq.Id);
            if(newEnq.Opportunity_Stage__c != OldEnq.Opportunity_Stage__c && newEnq.Opportunity_Stage__c !='Not Interested'){
                    setLeadId.add(newEnq.Lead__c);
                }
        }
        System.debug('setLeadId::'+setLeadId);
        
        List<Lead__c> leadList=[select id,Lost_Lead__c from Lead__c where Id In:setLeadId AND Lost_Lead__c=true];
        System.debug('enqList::'+leadList);
        
        if(leadList!=null && leadList.size()>0){
            for(Lead__c ld: leadList){
                ld.Lost_Lead__c=false;
            }
        }
        System.debug('leadList::'+leadList);
        try{
            if(leadList!=null && leadList.size()>0){
               update leadList;
            }
        }catch(Exception e){
            System.debug('Something Wrong::'+e.getMessage()+'Line No:: '+e.getLineNumber());
        }
    }   
}