force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Farmer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_First_Name__c</fullName>
    <label>Farmer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lost_Lead__c.field-meta.xml
<CustomField>
    <fullName>Lost_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lost Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Contact Later</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LostLeadBatch.cls
/* ───────────────────────────────────────────────────────────────────────────────
* @Description      : 
* @Author           : 
* @Company          : Venerate Solutions
* @created          : 
* @Last Modified By : 
* @Last Modified On : 
* @Modification Log : 
* ─────────────────────────────────────────────────────────────────────────────────
*/

global class LostLeadBatch implements Database.Batchable<sObject>,schedulable {
    global Database.QueryLocator start(Database.BatchableContext BC){
        String OppStage='Not Interested';
        String query='SELECT Id, Farmer_First_Name__c,Lost_Lead__c,(SELECT Id, Name FROM Opportunity__r WHERE Opportunity_Stage__c=\''+OppStage+'\') FROM Lead__c Where ID Not IN (SELECT Lead__c FROM Opportunity__c WHERE Opportunity_Stage__c!=\''+OppStage+'\')';
        System.debug('Build Query::::'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Lead__c> Leadlist){
        List<Lead__c> updateLeadList=new List<Lead__c>();
        System.debug('Leadlist Size::::::::'+Leadlist.size()+' details::::'+Leadlist);
        for(Lead__c ld: Leadlist){
            if(ld.Opportunity__r.size()>0){
                Lead__c ll=new Lead__c();
                ll.id=ld.id;
                ll.Lost_Lead__c=true;
                updateLeadList.add(ll);
            }
        }        
        system.debug('updateLeadList Size::'+updateLeadList.size()+ 'details updatelist::'+updateLeadList);
        try{
            if(updateLeadList!=null && updateLeadList.size()>0){
       		 Database.Update(updateLeadList,false);
            }
        } catch(Exception e){
            System.debug('Something Wrong::'+e.getMessage()+'Line No:: '+e.getLineNumber());
        }               
    }
     global void finish(Database.BatchableContext BC){
         System.debug('LostLeadBatch finished');
    }
    
    global void execute(SchedulableContext sc) {
        LostLeadBatch lostLdbatch = new LostLeadBatch();
        ID batchprocessid = Database.executeBatch(lostLdbatch,500);
    }
}