force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WhatsAppIntegrationTest.cls
@isTest
public class WhatsAppIntegrationTest  {

    @isTest
    static void testSendWtpMessage() {
        // Create a test lead with a phone number
        Lead__c l =TestSetupMethod.createFarmer();
        database.insert(l);
        
        Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        whatsAppIntegration.sendWtpMessage(l.Id);
        
        Test.stopTest();
        

    }
    
     @isTest
    static void testSendWtpMessage1() {
        // Create a test lead with a phone number
        Lead__c l =TestSetupMethod.createFarmer();
        l.Tehsil__c ='a082w000009l5UJAAY';
        database.insert(l);
        
        Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        whatsAppIntegration.sendWtpMessage(l.Id);
        
        Test.stopTest();
        

    } 
    
    @isTest
    static void testSendWtpMessage2() {
        // Create a test lead with a phone number
        Lead__c l =TestSetupMethod.createFarmer();
        l.Tehsil__c ='a082w000009l5CjAAI';
        database.insert(l);
        
        Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        whatsAppIntegration.sendWtpMessage(l.Id);
        
        Test.stopTest();
        

    }    
}