force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Current_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Current_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Current Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Previous_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/Dealer_with_Tehsil__c.object-meta.xml
<CustomObject>
    <label>Dealer with Tehsil</label>
    <nameField>
        <label>Dealer with Tehsils Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer with Tehsils</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer_Last_Three_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Last_Three_Month_Target__c</fullName>
    <formula>Tehsil_Name__r.Last_Three_Month_Target__c / Tehsil_Name__r.Dealer_Associate_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Last Three Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer_Previous_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Previous_Month_Target__c</fullName>
    <formula>Tehsil_Name__r.Previous_Month_Target__c / Tehsil_Name__r.Dealer_Associate_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Previous Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer_Target__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Target__c</fullName>
    <formula>Tehsil_Name__r.Curent_Month_Target__c / Tehsil_Name__r.Dealer_Associate_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateDealertargets.cls
public class UpdateDealertargets {
    
    public static void updateDealerMonthlyTargets(List<Dealer_with_Tehsil__c> deal){
        if(Label.update_dealer_target == 'Yes'){
        set<Id> parentIds = new set<Id>();
        List<Dealer__c>dealer = new List<Dealer__c>();
        
        for(Dealer_with_Tehsil__c d:deal ){
            parentIds.add(d.Dealer__c);
        }
        
        for(Id parentId : parentIds){
            
            Dealer__c dea = [Select Id,Current_Month_Target__c,Previous_Month_Target__c,Last_Three_Month_Target__c, 
                             (SELECT Id,Dealer_Target__c,Dealer_Previous_Month_Target__c,Dealer_Last_Three_Month_Target__c
                              FROM Dealer_with_Tehsils__r) FROM Dealer__c WHERE Id = :parentId];
            Decimal dealerTarget =0;
            Decimal dealerPreviousMonthTarget =0;
            Decimal dealerLastThreeMonthTarget =0;
            
            for (Dealer_with_Tehsil__c child : dea.Dealer_with_Tehsils__r) {

            dealerTarget+= child.Dealer_Target__c;
            dealerPreviousMonthTarget+= child.Dealer_Previous_Month_Target__c;
            dealerLastThreeMonthTarget+= child.Dealer_Last_Three_Month_Target__c;
          
        }
            dea.Current_Month_Target__c =dealerTarget;
            dea.Previous_Month_Target__c =dealerPreviousMonthTarget;
            dea.Last_Three_Month_Target__c =dealerLastThreeMonthTarget;
            dealer.add(dea);
        }
        
        update dealer;
        
    }
    }
    
    public static void CCHelp(){
    integer i=1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
        i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    }
}