force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Employee_Names__c.field-meta.xml
<CustomField>
    <fullName>Employee_Names__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Previous_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Three_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Three Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/Dealer_with_Tehsil__c.object-meta.xml
<CustomObject>
    <label>Dealer with Tehsil</label>
    <nameField>
        <label>Dealer with Tehsils Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer with Tehsils</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil_Name__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Three_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last Three Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/Last_Three_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Target__c</fullName>
    <formula>IF(Month_Number__c = 1, December_Target__c+November_Target__c+October_Target__c,
IF(Month_Number__c = 2, January_Target__c +December_Target__c+November_Target__c,
IF(Month_Number__c = 3, February_Target__c +January_Target__c +December_Target__c,
IF(Month_Number__c = 4, March_Target__c+February_Target__c +January_Target__c ,
IF(Month_Number__c = 5, April_Target__c+March_Target__c+February_Target__c ,
IF(Month_Number__c = 6, May_Target__c+April_Target__c+March_Target__c,
IF(Month_Number__c = 7, June_Target__c+May_Target__c+April_Target__c,
IF(Month_Number__c = 8, July_Target__c+June_Target__c+May_Target__c,
IF(Month_Number__c = 9, August_Target__c+July_Target__c+June_Target__c,
IF(Month_Number__c = 10, September_Target__c+August_Target__c+July_Target__c,
IF(Month_Number__c = 11, October_Target__c+September_Target__c+August_Target__c,
IF(Month_Number__c = 12, November_Target__c+ October_Target__c+ September_Target__c, 0) ) ) ) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Three Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/Previous_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Target__c</fullName>
    <formula>IF( Month_Number__c = 2, January_Target__c ,
IF(Month_Number__c = 3, February_Target__c ,
IF(Month_Number__c = 4, March_Target__c,
IF(Month_Number__c = 5, April_Target__c,
IF(Month_Number__c = 6, May_Target__c,
IF(Month_Number__c = 7, June_Target__c,
IF(Month_Number__c = 8, July_Target__c,
IF(Month_Number__c = 9, August_Target__c,
IF(Month_Number__c = 10, September_Target__c,
IF(Month_Number__c = 11, October_Target__c,
IF(Month_Number__c = 12, November_Target__c,
IF(Month_Number__c = 1, December_Target__c, 0) ) ) ) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LwcForTargetsVsAchivementTest.cls
@isTest
public class LwcForTargetsVsAchivementTest {
   /*     
    @isTest
    public static void completedTargetList() {
          User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 dea.Three_Month_Achievement__c = 2500;
         database.insert(dea);
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getFirstStageTargetList();
        
        Test.stopTest();	
    
    }
     @isTest
    public static void completedTargetList1() {
          User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 dea.Three_Month_Achievement__c = 45500;
         database.insert(dea);
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getSecondStageTargetList();
        
        Test.stopTest();	
    
    }
    @isTest
    public static void completedTargetList2() {
          User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 dea.Three_Month_Achievement__c = 45500;
         database.insert(dea);
         
         Dealer__c deaF= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 deaF.Three_Month_Achievement__c = 25500;
         database.insert(deaF);	
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getThirdStageTargetList();
        
        Test.stopTest();	
    
    }
    @isTest
    public static void completedTargetList9() {
          User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 dea.Three_Month_Achievement__c = 45500;
         database.insert(dea);
         
         Dealer__c deaF= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 deaF.Three_Month_Achievement__c = 25500;
         database.insert(deaF);	
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getFourStageTargetList();
        
        Test.stopTest();	
    
    }
    @isTest
    public static void completedTargetList10() {
          User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 dea.Three_Month_Achievement__c = 45500;
         database.insert(dea);
         
         Dealer__c deaF= TestSetupMethod.createDealer(newUser.Id,dis.Id);
      	 deaF.Three_Month_Achievement__c = 25500;
         database.insert(deaF);	
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getAllTargetList();
        
        Test.stopTest();	
    
    }
    @isTest
    public static void completedTargetList3() {
          User newUser = TestSetupMethod.createUser();
         newUser.Three_Month_Achievement__c= 200000;
         database.insert(newUser);
         
        
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getFirstStageEmpTargetList();
        
        Test.stopTest();	
    
    } 
    @isTest
    public static void completedTargetList4() {
          User newUser = TestSetupMethod.createUser();
         newUser.Three_Month_Achievement__c= 200000;
         database.insert(newUser);
         
        
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getSecondStageEmpTargetList();
        
        Test.stopTest();	
    
    }
    @isTest
    public static void completedTargetList7() {
          User newUser = TestSetupMethod.createUser();
         newUser.Three_Month_Achievement__c= 200000;
         database.insert(newUser);
         
        
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getThirdStageEmpTargetList();
        
        Test.stopTest();	
    
    }
    @isTest
    public static void completedTargetList8() {
          User newUser = TestSetupMethod.createUser();
         newUser.Three_Month_Achievement__c= 200000;
         database.insert(newUser);
         
        
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getForthStageEmpTargetList();
        
        Test.stopTest();	
    
    }
    @isTest
    public static void completedTargetList5() {
          User newUser = TestSetupMethod.createUser();
         newUser.Three_Month_Achievement__c= 100000;
         database.insert(newUser);
         
        
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getAllTargetEmpTargetList();
        
        Test.stopTest();	
    
    }
    */
    
   @isTest
    public static void completedTargetList() {
         District__c di =TestSetupMethod.createDistrict();
         database.insert(di);
        
         Tehsil__c teh = TestSetupMethod.createTehsils(di.Id);
         database.insert(teh);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
        
         Employee__c emp =TestSetupMethod.createEmployee();
         database.insert(emp);
        
         Dealer__c dea= TestSetupMethod.createDealerWithoutUser(dis.Id);
      	 dea.Employee_Names__c=emp.Id;
         dea.Last_Three_Month_Target__c =2500;
         database.insert(dea);
        
         Dealer_with_Tehsil__c deteh= TestSetupMethod.createDealerWithTehsils(teh.Id,dea.Id);
         database.insert(deteh);
        
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getFirstStageTargetList();
        LwcForTargetsVsAchivement.getSecondStageTargetList();
        LwcForTargetsVsAchivement.getThirdStageTargetList();
        LwcForTargetsVsAchivement.getFourStageTargetList();
        LwcForTargetsVsAchivement.getAllTargetList();
        LwcForTargetsVsAchivement.getMonthFirstStageTargetList();
        LwcForTargetsVsAchivement.getMonthSecondStageTargetList();
        LwcForTargetsVsAchivement.getMonthThirdStageTargetList();
        LwcForTargetsVsAchivement.getMonthFourStageTargetList();
        LwcForTargetsVsAchivement.getMonthAllTargetList();
        
        Test.stopTest();	
    
    }   
    
    @isTest
    public static void empCompletedTargetList() {
                
         Employee__c emp =TestSetupMethod.createEmployee();
         emp.Previous_Month_Target__c=1500;
         emp.Last_Three_Month_Target__c=1500;
         emp.Employee_Monthly_Target__c=3000;
         database.insert(emp);
      
         Test.startTest();
        
        // Call the sendWtpMessage method and pass in the test lead's ID
        LwcForTargetsVsAchivement.getFirstStageEmpTargetList();
        LwcForTargetsVsAchivement.getSecondStageEmpTargetList();
        LwcForTargetsVsAchivement.getThirdStageEmpTargetList();
        LwcForTargetsVsAchivement.getForthStageEmpTargetList();
        LwcForTargetsVsAchivement.getAllTargetEmpTargetList();
        LwcForTargetsVsAchivement.getMonthFirstStageEmpTargetList();
        LwcForTargetsVsAchivement.getMonthSecondStageEmpTargetList();
        LwcForTargetsVsAchivement.getMonthThirdStageEmpTargetList();
        LwcForTargetsVsAchivement.getMonthForthStageEmpTargetList();
        LwcForTargetsVsAchivement.getMonthAllTargetEmpTargetList();
        
        Test.stopTest();	
    
    }  
    
}