force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Last_Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Achievement__c</fullName>
    <label>Last Three Month Achievement</label>
    <summarizedField>Dealer_with_Tehsil__c.Last_Three_Month_Achievement__c</summarizedField>
    <summaryForeignKey>Dealer_with_Tehsil__c.Dealer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Previous_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Achievement__c</fullName>
    <label>Previous Month Achievement</label>
    <summarizedField>Dealer_with_Tehsil__c.Previous_Month_Achievement__c</summarizedField>
    <summaryForeignKey>Dealer_with_Tehsil__c.Dealer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Three_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Three Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/Dealer_with_Tehsil__c.object-meta.xml
<CustomObject>
    <label>Dealer with Tehsil</label>
    <nameField>
        <label>Dealer with Tehsils Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer with Tehsils</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil_Name__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Previous_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Tehsil_Name__c.field-meta.xml
<CustomField>
    <fullName>Tehsil_Name__c</fullName>
    <label>Tehsil Name</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/This_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>This_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>This Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Dealer_with_Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Dealer_with_Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer with Tehsil</label>
    <referenceTo>Dealer_with_Tehsil__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Product_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Dealer__r.Distributor__r.Name</formula>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Lead__r.District__c</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pondliner_Size_Requested_Required_Sq_Mt__c.field-meta.xml
<CustomField>
    <fullName>Pondliner_Size_Requested_Required_Sq_Mt__c</fullName>
    <label>Qty(In sq m)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Product_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <formula>Lead__r.Tehsil__r.Name</formula>
    <label>Tehsil</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil_Name__c.field-meta.xml
<CustomField>
    <fullName>Tehsil_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil Name</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Product_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>SKU Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateDealerAcheivementHandlerTest.cls
@isTest
public class UpdateDealerAcheivementHandlerTest {
  /* 
     @isTest
     public static void UpdateDealerAcheivTest() {
         User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
         database.insert(dea);
         
         Product__c p= TestSetupMethod.createProduct();
         database.insert(p);
         
         Lead__c l =TestSetupMethod.createFarmer();
         database.insert(l);
         
         Opportunity__c Pi= TestSetupMethod.createProductInformation(dea.Id,p.Id,l.Id);
         database.insert(Pi);
         
           
        Dealer__c parent = [SELECT Id, Three_Month_Achievement__c,Weekly_Achievement__c,This_Month_Achievement__c FROM Dealer__c WHERE Id = :dea.Id];
         System.assertEquals(0, parent.Three_Month_Achievement__c);
       //  System.assertEquals(0, parent.Weekly_Achievement__c);
          System.assertEquals(0, parent.This_Month_Achievement__c);
        Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 4850;
       // Pi.Invoice_Date__c =null; 
        update Pi;
         
        Dealer__c parent1 = [SELECT Id, Three_Month_Achievement__c FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(4850, parent1.Three_Month_Achievement__c); 
         
        Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 6890;
        update Pi;
         
        Dealer__c parent2 = [SELECT Id, Three_Month_Achievement__c FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(6890, parent2.Three_Month_Achievement__c);  
         
        Opportunity__c Py= TestSetupMethod.createProductInformation(dea.Id,p.Id,l.Id);
        database.insert(Py);  
         
        Dealer__c parent3 = [SELECT Id, Three_Month_Achievement__c FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(6890, parent3.Three_Month_Achievement__c);   
         
        Py.Pondliner_Size_Requested_Required_Sq_Mt__c = null;
        update Py;
        Dealer__c parent4 = [SELECT Id, Three_Month_Achievement__c FROM Dealer__c WHERE Id = :dea.Id];
        System.assertEquals(6890, parent4.Three_Month_Achievement__c); 
         
        
        }
    @isTest
     public static void UpdateDealerAcheivTest1() {
         User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
         database.insert(dea);
         
         Product__c p= TestSetupMethod.createProduct();
         database.insert(p);
         
         Lead__c l =TestSetupMethod.createFarmer();
         database.insert(l);
         
         Opportunity__c Pi= TestSetupMethod.createProductInformation(dea.Id,p.Id,l.Id);
         database.insert(Pi);
         
         Opportunity__c Pi1= TestSetupMethod.createProductInformation(dea.Id,p.Id,l.Id);
         database.insert(Pi1);
         
          Dealer__c parent = [SELECT Id, January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,May_Achievement__c,
			June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                              FROM Dealer__c WHERE Id = :dea.Id];
         System.assertEquals(0, parent.March_Achievement__c);
       //  System.assertEquals(0, parent.Weekly_Achievement__c);
          System.assertEquals(0, parent.January_Achievement__c);
        Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 4850;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 4, 25);
        update Pi;
         
        Dealer__c parent1 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(4850, parent1.April_Achievement__c); 
        
        Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 5, 25);
        update Pi; 
        
        Dealer__c parent2 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent2.May_Achievement__c); 
       
        
        Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 2, 25);
        update Pi; 
        
        Pi1.Pondliner_Size_Requested_Required_Sq_Mt__c = 4850;
       // Pi.Invoice_Date__c =null; 
       	Pi1.Invoice_Date__c = Date.newInstance(2023, 3, 25);
        update Pi1; 
         
        Dealer__c parent3 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent3.February_Achievement__c); 
         System.assertEquals(4850, parent3.March_Achievement__c);
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 1, 25);
        update Pi; 
        
        Dealer__c parent4 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent4.January_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 3, 25);
        update Pi; 
        
        Dealer__c parent5 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent5.March_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 6, 25);
        update Pi; 
        
        Dealer__c parent6 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent6.June_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 7, 25);
        update Pi; 
        
        Dealer__c parent7 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent7.July_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 8, 25);
        update Pi; 
        
        Dealer__c parent8 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent8.August_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 9, 25);
        update Pi; 
        
        Dealer__c parent9 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent9.September_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 10, 25);
        update Pi; 
        
        Dealer__c parent10 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent10.October_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 11, 25);
        update Pi; 
        
        Dealer__c parent11 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent11.November_Achievement__c); 
         
         
         Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 450;
       // Pi.Invoice_Date__c =null; 
       	Pi.Invoice_Date__c = Date.newInstance(2023, 12, 25);
        update Pi; 
        
        Dealer__c parent12 = [SELECT Id,January_Achievement__c,February_Achievement__c,March_Achievement__c,April_Achievement__c,
                             May_Achievement__c,June_Achievement__c,July_Achievement__c,August_Achievement__c,
                              September_Achievement__c,October_Achievement__c,November_Achievement__c,December_Achievement__c
                             FROM Dealer__c WHERE Id = :dea.Id]; 
        System.assertEquals(450, parent12.December_Achievement__c); 
         
         
      
         
     }
 
*/
    
  @isTest
     public static void UpdateDealerAcheivTest() {
         User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
         database.insert(dea);
         
         Product__c p= TestSetupMethod.createProduct();
         database.insert(p);
         
         Lead__c l =TestSetupMethod.createFarmer();
         database.insert(l);
         
         Opportunity__c Pi= TestSetupMethod.createProductInformation(dea.Id,p.Id,l.Id);
         database.insert(Pi);
         
         District__c dist= TestSetupMethod.createDistrict();
         database.insert(dist);
    
         Tehsil__c teh= TestSetupMethod.createTehsils(dist.Id);
         database.insert(teh);  
         
         Dealer_with_Tehsil__c dwt =new Dealer_with_Tehsil__c();
     	 dwt.Tehsil_Name__c =teh.Id;
         dwt.Dealer__c = dea.Id;
         database.insert(dwt);
         
           
        Dealer_with_Tehsil__c parent = [SELECT Id, This_Month_Achievement__c,Previous_Month_Achievement__c,Last_Three_Month_Achievement__c FROM Dealer_with_Tehsil__c WHERE Id = :dwt.Id];
         System.assertEquals(0, parent.This_Month_Achievement__c);
         System.assertEquals(0, parent.Previous_Month_Achievement__c);
         System.assertEquals(0, parent.Last_Three_Month_Achievement__c);
		
        Pi.Dealer_with_Tehsil__c = dwt.Id;
        Pi.Pondliner_Size_Requested_Required_Sq_Mt__c = 4850;
        update Pi;

        Dealer_with_Tehsil__c parent1 = [SELECT Id, This_Month_Achievement__c,Previous_Month_Achievement__c,Last_Three_Month_Achievement__c FROM Dealer_with_Tehsil__c WHERE Id = :dwt.Id]; 
        System.assertEquals(4850, parent1.Previous_Month_Achievement__c); 
        System.assertEquals(0, parent1.This_Month_Achievement__c);
        System.assertEquals(4850, parent1.Last_Three_Month_Achievement__c); 
        
       
        }  

}