force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Dealer_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Mobile__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Dealer Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Distributor_Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact_Person__c</fullName>
    <label>Distributor Contact Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Distributor_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Mobile__c</fullName>
    <inlineHelpText>10 Digits mobile Number</inlineHelpText>
    <label>Distributor Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_First_Name__c</fullName>
    <label>Farmer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <inlineHelpText>Mobile Number Should be 10 Digits</inlineHelpText>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Pond_Digging_Done__c.field-meta.xml
<CustomField>
    <fullName>Pond_Digging_Done__c</fullName>
    <label>Pond Digging Done</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don&apos;t Know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Products_Interested__c.field-meta.xml
<CustomField>
    <fullName>Products_Interested__c</fullName>
    <label>Products Interested</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jalasanchay</fullName>
            </value>
            <value>
                <fullName>Retail Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Dealer__r.Distributor__r.Name</formula>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Contact Later</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Payment_Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received_Amount__c</fullName>
    <label>Payment Received Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/Jalasanchay.recordType-meta.xml
<RecordType>
    <fullName>Jalasanchay</fullName>
    <active>true</active>
    <label>Jalasanchay</label>
</RecordType>

force-app/main/default/classes/TestConvertedCannotBeDeleted.cls
@isTest 
public class TestConvertedCannotBeDeleted {
    
    @isTest public static void
        deleteTest()
    {
        Test.startTest();
        Lead__c l = new Lead__c();
        l.Farmer_First_Name__c = 'test';
        l.Pond_Digging_Done__c = 'Yes';
        l.Products_Interested__c = 'Jalasanchay';
        l.Mobile_Number__c ='0987654321';
        insert l;
        
        Distributor__c D = new Distributor__c();
        D.Active__c = True;
        D.Distributor_Contact_Person__c = 'TestPerson';
        D.Distributor_Mobile__c ='1234567890';
        D.Name = 'TestCompany';
        insert D;
        
        Dealer__c c = new Dealer__c();
        c.Active__c = True;
        c.Name = 'TestDealer';
        c.Distributor__c = D.Id;
        c.Dealer_Mobile__c ='8879483713';
        insert c;
        
        
        Opportunity__c a = new Opportunity__c();
        a.Lead__c = l.Id;
        a.Dealer__c = c.Id;
        a.Invoice_Number__c= 'AV1/20-22/12345/13';
        a.Invoice_Date__c = system.today();
        a.Opportunity_Stage__c = 'Converted';
        a.Payment_Received_Amount__c = 123;
        insert a;
        Test.stopTest();
        
        
            try
            {
                Delete  a;
            }
            catch(Exception ee)
            {}      
    }

}