force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 Digits number.</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Dealer__r.Distributor__r.Name</formula>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Farmer_feedback__c.field-meta.xml
<CustomField>
    <fullName>Farmer_feedback__c</fullName>
    <label>Farmer feedback</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Not Satisfied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Date__c</fullName>
    <label>Installation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Invoice_done__c.field-meta.xml
<CustomField>
    <fullName>Invoice_done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Murughas_Bag_Qty__c.field-meta.xml
<CustomField>
    <fullName>Murughas_Bag_Qty__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Name_of_Operator__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jalasanchay_Installation_Operators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pond_Size_Sq_Mtr__c.field-meta.xml
<CustomField>
    <fullName>Pond_Size_Sq_Mtr__c</fullName>
    <label>Size of the Pond(length x width x depth)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pondliner_Size_Requested_Required_Sq_Mt__c.field-meta.xml
<CustomField>
    <fullName>Pondliner_Size_Requested_Required_Sq_Mt__c</fullName>
    <label>Qty(In sq m)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pre_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Pre_Visit_Date__c</fullName>
    <label>Pre Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pre_Visit_Done_By__c.field-meta.xml
<CustomField>
    <fullName>Pre_Visit_Done_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre Visit Done By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiry1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Old Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jalasanchay</fullName>
            </value>
            <value>
                <fullName>Jalasanchay Super</fullName>
            </value>
            <value>
                <fullName>Samruddhi 300</fullName>
            </value>
            <value>
                <fullName>Samruddhi 400</fullName>
            </value>
            <value>
                <fullName>Full bag</fullName>
            </value>
            <value>
                <fullName>Liner</fullName>
            </value>
            <value>
                <fullName>Perco Plus</fullName>
            </value>
            <value>
                <fullName>Jalasanchay 750</fullName>
            </value>
            <value>
                <fullName>Jalasanchay 1000</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>500L</fullName>
            </value>
            <value>
                <fullName>750L</fullName>
            </value>
            <value>
                <fullName>1000L</fullName>
            </value>
            <value>
                <fullName>Blue 4000 denier</fullName>
            </value>
            <value>
                <fullName>White 4000 denier</fullName>
            </value>
            <value>
                <fullName>Waterproof Sutli (Brown 5000 denier)</fullName>
            </value>
            <value>
                <fullName>140 GSM</fullName>
            </value>
            <value>
                <fullName>220 GSM</fullName>
            </value>
            <value>
                <fullName>370 GSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Quality_person__c.field-meta.xml
<CustomField>
    <fullName>Quality_person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Inspector</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <formula>Lead__r.Tehsil__r.Name</formula>
    <label>Tehsil</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Jalasanchay_Installation_Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ajeet Rathod</fullName>
    </customValue>
    <customValue>
        <fullName>Akash Mohite</fullName>
    </customValue>
    <customValue>
        <fullName>Akhilesh Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Arvind Kushwaha</fullName>
    </customValue>
    <customValue>
        <fullName>ASHHG02-Sunil Dongardive</fullName>
    </customValue>
    <customValue>
        <fullName>ASHHG04-Rajesh Kumar</fullName>
    </customValue>
    <customValue>
        <fullName>ASHTM01-Bharat Bhand</fullName>
    </customValue>
    <customValue>
        <fullName>AVATM01-Abhay Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>AVATM03-Roshan Rathod</fullName>
    </customValue>
    <customValue>
        <fullName>AVATM04-Bhushan Rathod</fullName>
    </customValue>
    <customValue>
        <fullName>Avinash Chivhan</fullName>
    </customValue>
    <customValue>
        <fullName>BALTM01-Vitthal Dhere</fullName>
    </customValue>
    <customValue>
        <fullName>BALTM04-Pradip Lohakare</fullName>
    </customValue>
    <customValue>
        <fullName>Bapu Shirsath</fullName>
    </customValue>
    <customValue>
        <fullName>Chanilal singh</fullName>
    </customValue>
    <customValue>
        <fullName>Chothelal</fullName>
    </customValue>
    <customValue>
        <fullName>Deepak Bhusari</fullName>
    </customValue>
    <customValue>
        <fullName>Dinanath Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Dungar Ram</fullName>
    </customValue>
    <customValue>
        <fullName>Gorakh Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Govinda Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Gurjinder Singh</fullName>
    </customValue>
    <customValue>
        <fullName>Himanshu Kushwaha</fullName>
    </customValue>
    <customValue>
        <fullName>JINHG01-Ainl Jhinjha</fullName>
    </customValue>
    <customValue>
        <fullName>JINHG02-pankaj Godara</fullName>
    </customValue>
    <customValue>
        <fullName>Jitendra Kumar</fullName>
    </customValue>
    <customValue>
        <fullName>Krushna Shinde</fullName>
    </customValue>
    <customValue>
        <fullName>KRUTM01-Anil Kushawaha</fullName>
    </customValue>
    <customValue>
        <fullName>Lakhan Parkhe</fullName>
    </customValue>
    <customValue>
        <fullName>Laxman Lokhande</fullName>
    </customValue>
    <masterLabel>Jalasanchay Installation Operators</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PdfClass_Test.cls
@isTest
public class PdfClass_Test {
    public static testMethod void PdfClassTest()
    {
         Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        
        Distributor__c dd=new Distributor__c();
        dd.Name='test';
        dd.Distributor_Email__c='abac@gmail.com';
        insert dd;
        
        Dealer__c Dl= new Dealer__c();
        Dl.Name='sangv';
        Dl.Distributor__c=dd.id;
        insert Dl;
        
        Tehsil__c Tl= new Tehsil__c();
        Tl.Dealer__c=Dl.Id;
        Tl.Name='hgfg';
        insert Tl;
        
        Account acc=new Account();
        acc.name='avana';
        acc.Farmer_First_Name__c='Pritam';
        acc.Farmer_Middle_Name__c='A';
        acc.Address__c='indiranagar';
        acc.Phone='9743443434';
        acc.Alternate_Mobile_No__c='9778906453';
        acc.Aadhar_Number__c='123434345656';
        acc.Pin_Code__c='588899';
        acc.Dealer__c=Dl.id;
        insert acc;
        
        
      Opportunity__c opp = new Opportunity__c();
        opp.Product_Name__c='jhasjg';
        opp.Pondliner_Size_Requested_Required_Sq_Mt__c=0.00;
        opp.Pond_Size_Sq_Mtr__c='20';
        opp.Murughas_Bag_Qty__c=5.0;
        opp.Invoice_done__c=true;
        opp.Invoice_Date__c = Date.newInstance(2016, 12, 9);
        opp.Quality_person__c=u.Id;
        opp.Pre_Visit_Date__c=Date.newInstance(2016, 12, 9);
        opp.Pre_Visit_Done_By__c=u.id;
        opp.Remarks__c='fg';
        opp.Installation_Date__c=Date.newInstance(2016, 12, 9);
        opp.Name_of_Operator__c='ASHHG02-Sunil Dongardive';
        opp.Farmer_feedback__c='Satisfied';
        opp.Customer__c=acc.id;
        
        insert opp;
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
     ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';          
        cv.VersionData =beforeblob;          
        insert cv;        

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];


        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=opp.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        contentlink.Visibility = 'AllUsers';
        insert contentlink;
        
        PageReference pageRef = Page.AttachImagePDF;
        pageRef.getParameters().put('id', opp.id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        PdfClass testAccPlan = new PdfClass(sc);
        testAccPlan.goBack();
        
        
    }

}