force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 Digits number.</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address Landmark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 digits Mobile No</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_First_Name__c</fullName>
    <label>Farmer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Middle_Name__c</fullName>
    <label>Farmer Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Tehsil__r.District__r.State__c)</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Certificate_Valid_Till__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Valid_Till__c</fullName>
    <description>Calculate Warranty Date From Invoice Date</description>
    <formula>CASE( Pondliner_Variant__c ,
 &apos;300 Microns&apos;,  ADDMONTHS( Invoice_Date__c  ,36) ,
 &apos;500 Microns&apos;,  ADDMONTHS( Invoice_Date__c  ,60) ,
null)</formula>
    <label>Certificate Valid Till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Dealer__r.Distributor__r.Name</formula>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Lead__r.District__c</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Farmer_feedback__c.field-meta.xml
<CustomField>
    <fullName>Farmer_feedback__c</fullName>
    <label>Farmer feedback</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Not Satisfied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Date__c</fullName>
    <label>Installation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Invoice_done__c.field-meta.xml
<CustomField>
    <fullName>Invoice_done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Murughas_Bag_Qty__c.field-meta.xml
<CustomField>
    <fullName>Murughas_Bag_Qty__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Name_of_Operator__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jalasanchay_Installation_Operators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pond_Size_Sq_Mtr__c.field-meta.xml
<CustomField>
    <fullName>Pond_Size_Sq_Mtr__c</fullName>
    <label>Size of the Pond(length x width x depth)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pondliner_Size_Requested_Required_Sq_Mt__c.field-meta.xml
<CustomField>
    <fullName>Pondliner_Size_Requested_Required_Sq_Mt__c</fullName>
    <label>Qty(In sq m)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pre_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Pre_Visit_Date__c</fullName>
    <label>Pre Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Pre_Visit_Done_By__c.field-meta.xml
<CustomField>
    <fullName>Pre_Visit_Done_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre Visit Done By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiry1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Old Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jalasanchay</fullName>
            </value>
            <value>
                <fullName>Jalasanchay Super</fullName>
            </value>
            <value>
                <fullName>Samruddhi 300</fullName>
            </value>
            <value>
                <fullName>Samruddhi 400</fullName>
            </value>
            <value>
                <fullName>Full bag</fullName>
            </value>
            <value>
                <fullName>Liner</fullName>
            </value>
            <value>
                <fullName>Perco Plus</fullName>
            </value>
            <value>
                <fullName>Jalasanchay 750</fullName>
            </value>
            <value>
                <fullName>Jalasanchay 1000</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>500L</fullName>
            </value>
            <value>
                <fullName>750L</fullName>
            </value>
            <value>
                <fullName>1000L</fullName>
            </value>
            <value>
                <fullName>Blue 4000 denier</fullName>
            </value>
            <value>
                <fullName>White 4000 denier</fullName>
            </value>
            <value>
                <fullName>Waterproof Sutli (Brown 5000 denier)</fullName>
            </value>
            <value>
                <fullName>140 GSM</fullName>
            </value>
            <value>
                <fullName>220 GSM</fullName>
            </value>
            <value>
                <fullName>370 GSM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Quality_person__c.field-meta.xml
<CustomField>
    <fullName>Quality_person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Inspector</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Lead__r.State__c</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <formula>Lead__r.Tehsil__r.Name</formula>
    <label>Tehsil</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Text(District__r.State__c)</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Jalasanchay_Installation_Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ajeet Rathod</fullName>
    </customValue>
    <customValue>
        <fullName>Akash Mohite</fullName>
    </customValue>
    <customValue>
        <fullName>Akhilesh Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Arvind Kushwaha</fullName>
    </customValue>
    <customValue>
        <fullName>ASHHG02-Sunil Dongardive</fullName>
    </customValue>
    <customValue>
        <fullName>ASHHG04-Rajesh Kumar</fullName>
    </customValue>
    <customValue>
        <fullName>ASHTM01-Bharat Bhand</fullName>
    </customValue>
    <customValue>
        <fullName>AVATM01-Abhay Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>AVATM03-Roshan Rathod</fullName>
    </customValue>
    <customValue>
        <fullName>AVATM04-Bhushan Rathod</fullName>
    </customValue>
    <customValue>
        <fullName>Avinash Chivhan</fullName>
    </customValue>
    <customValue>
        <fullName>BALTM01-Vitthal Dhere</fullName>
    </customValue>
    <customValue>
        <fullName>BALTM04-Pradip Lohakare</fullName>
    </customValue>
    <customValue>
        <fullName>Bapu Shirsath</fullName>
    </customValue>
    <customValue>
        <fullName>Chanilal singh</fullName>
    </customValue>
    <customValue>
        <fullName>Chothelal</fullName>
    </customValue>
    <customValue>
        <fullName>Deepak Bhusari</fullName>
    </customValue>
    <customValue>
        <fullName>Dinanath Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Dungar Ram</fullName>
    </customValue>
    <customValue>
        <fullName>Gorakh Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Govinda Yadav</fullName>
    </customValue>
    <customValue>
        <fullName>Gurjinder Singh</fullName>
    </customValue>
    <customValue>
        <fullName>Himanshu Kushwaha</fullName>
    </customValue>
    <customValue>
        <fullName>JINHG01-Ainl Jhinjha</fullName>
    </customValue>
    <customValue>
        <fullName>JINHG02-pankaj Godara</fullName>
    </customValue>
    <customValue>
        <fullName>Jitendra Kumar</fullName>
    </customValue>
    <customValue>
        <fullName>Krushna Shinde</fullName>
    </customValue>
    <customValue>
        <fullName>KRUTM01-Anil Kushawaha</fullName>
    </customValue>
    <customValue>
        <fullName>Lakhan Parkhe</fullName>
    </customValue>
    <customValue>
        <fullName>Laxman Lokhande</fullName>
    </customValue>
    <masterLabel>Jalasanchay Installation Operators</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Dadra &amp; Nagar Haveli</fullName>
    </customValue>
    <customValue>
        <fullName>Goa</fullName>
    </customValue>
    <customValue>
        <fullName>Gujarat</fullName>
    </customValue>
    <customValue>
        <fullName>Haryana</fullName>
    </customValue>
    <customValue>
        <fullName>Jammu and Kashmir</fullName>
    </customValue>
    <customValue>
        <fullName>Karnataka</fullName>
    </customValue>
    <customValue>
        <fullName>Madhya Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Maharashtra</fullName>
    </customValue>
    <customValue>
        <fullName>Punjab</fullName>
    </customValue>
    <customValue>
        <fullName>Rajasthan</fullName>
    </customValue>
    <customValue>
        <fullName>Tamil Nadu</fullName>
    </customValue>
    <customValue>
        <fullName>Telangana</fullName>
    </customValue>
    <customValue>
        <fullName>Uttar Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Jharkhand</fullName>
    </customValue>
    <description>Indian States</description>
    <masterLabel>Indian States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PdfClass.cls
public class PdfClass {
    public List<ContentVersion> PreConVrsnList {get;set;}
    public List<ContentVersion> PostConVrsnList {get;set;}
    public Id recId=Apexpages.currentPage().getparameters().get('id');
    public List<ContentDocumentLink> cclist {get;set;}
    public List<Opportunity__c> enlist{get;set;}
    
    public PdfClass(ApexPages.StandardController controller) {
        System.debug('record id of object:::::'+recId);
        enlist=[select id,Customer__c,Customer__r.name,Customer__r.Farmer_First_Name__c,Customer__r.Farmer_Middle_Name__c,Customer__r.Address__c,Customer__r.State__c,Lead__c,
                Customer__r.Tehsil__r.Name,Customer__r.District__c,Customer__r.Phone,Customer__r.Alternate_Mobile_No__c,Customer__r.Aadhar_Number__c,Product_Name__c,Pondliner_Size_Requested_Required_Sq_Mt__c,Pond_Size_Sq_Mtr__c,
                Murughas_Bag_Qty__c,Customer__r.Distributor__c,Customer__r.Pin_Code__c,Customer__r.Dealer__r.Name,Invoice_done__c,Invoice_Date__c,Quality_person__r.Name,Pre_Visit_Date__c,Pre_Visit_Done_By__r.Name,
                Remarks__c,Installation_Date__c,Name_of_Operator__c,Certificate_Valid_Till__c,Farmer_feedback__c from opportunity__c where id=:recId];
        
        System.debug('details of enquiry::::::'+enlist);
        if(enlist[0].Customer__c!=null){
            cclist = new List<ContentDocumentLink>(); 
            cclist=[select contentdocumentId,linkedentityid from ContentDocumentLink where linkedentityid =:recId ];
        system.debug('contentdocumentlink details:::'+cclist);
        	Set<Id> conid=new Set<Id>();
            for(ContentDocumentLink co:cclist){
                conid.add(co.ContentDocumentId);
            }
        System.debug('conid:::'+conid);
        	 If(!cclist.isEmpty()){
                PreConVrsnList=[select id,versiondata,title,filetype from ContentVersion where contentdocumentId in:conid AND title LIKE '%PreImage%' ORDER BY LastModifiedDate DESC LIMIT 1];
                System.debug('PRE content Version details::::::'+PreConVrsnList);
                PostConVrsnList=[select id,versiondata,title,filetype from ContentVersion where contentdocumentId in:conid AND title LIKE '%PostImage%' ORDER BY LastModifiedDate DESC LIMIT 1]; 
              	System.debug('POST content Version details::::::'+PostConVrsnList);
        	}
            //FileIds=pdfWithDocumrnt();
        }
        
    }
    
   /* public List<ContentVersion> pdfWithDocumrnt(){
        system.debug('OppId:::'+recId);
        //string FileId; 
        List<ContentVersion> conlist = new List<ContentVersion>();
        Set<Id> conid=new Set<Id>();
        for(ContentDocumentLink co:cclist){
            conid.add(co.ContentDocumentId);
        }
        System.debug('conid:::'+conid);
        system.debug('contentdocumentId details:::'+cclist);
        //string preImg='%'+'PreImage'+'%';
        //string pstImg='%'+'PostImage'+'%';
        If(!cclist.isEmpty()){
            conlist=[select id,versiondata,title,filetype from ContentVersion where contentdocumentId in:conid AND (title LIKE '%PreImage%' OR title LIKE '%PostImage%')];
            //FileId=conlist[0].Id;
            System.debug('content Version details::::::'+conlist);
            //system.debug('FileID:::'+FileId);
        }
        return conlist;
    }*/
    
    public PageReference goBack(){
        Id OppiD = ApexPages.currentPage().getParameters().get('id');
        PageReference pg = new PageReference('/'+OppiD);
        return pg;
    }
}