force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>Credit limit for dealer - usually used for direct dealers (otherwise distributor is given total credit limit to be used across their dealers)</description>
    <inlineHelpText>For Direct Dealers</inlineHelpText>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Dealer_Address__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Address__c</fullName>
    <label>Dealer Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Dealer_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Mobile__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Dealer Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Employee_Names__c.field-meta.xml
<CustomField>
    <fullName>Employee_Names__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Weekly_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Weekly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/Dealer_with_Tehsil__c.object-meta.xml
<CustomObject>
    <label>Dealer with Tehsil</label>
    <nameField>
        <label>Dealer with Tehsils Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer with Tehsils</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>Dealer__r.Active__c</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil_Name__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Tehsil_Name__r.State__c</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>Credit Limit for distributor. Dispatches above this limit may not be approved.</description>
    <label>Credit Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Distributor_Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact_Person__c</fullName>
    <label>Distributor Contact Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Distributor_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Mobile__c</fullName>
    <inlineHelpText>10 Digits mobile Number</inlineHelpText>
    <label>Distributor Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_First_Name__c</fullName>
    <label>Farmer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <inlineHelpText>Mobile Number Should be 10 Digits</inlineHelpText>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Pond_Digging_Done__c.field-meta.xml
<CustomField>
    <fullName>Pond_Digging_Done__c</fullName>
    <label>Pond Digging Done</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don&apos;t Know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Products_Interested__c.field-meta.xml
<CustomField>
    <fullName>Products_Interested__c</fullName>
    <label>Products Interested</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jalasanchay</fullName>
            </value>
            <value>
                <fullName>Retail Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Dealer__r.Distributor__r.Name</formula>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Lead__r.District__c</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <formula>CreatedBy.Monthly_Target__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <formula>Lead__r.Tehsil__r.Name</formula>
    <label>Tehsil</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/Jalasanchay.recordType-meta.xml
<RecordType>
    <fullName>Jalasanchay</fullName>
    <active>true</active>
    <label>Jalasanchay</label>
</RecordType>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Dadra &amp; Nagar Haveli</fullName>
    </customValue>
    <customValue>
        <fullName>Goa</fullName>
    </customValue>
    <customValue>
        <fullName>Gujarat</fullName>
    </customValue>
    <customValue>
        <fullName>Haryana</fullName>
    </customValue>
    <customValue>
        <fullName>Jammu and Kashmir</fullName>
    </customValue>
    <customValue>
        <fullName>Karnataka</fullName>
    </customValue>
    <customValue>
        <fullName>Madhya Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Maharashtra</fullName>
    </customValue>
    <customValue>
        <fullName>Punjab</fullName>
    </customValue>
    <customValue>
        <fullName>Rajasthan</fullName>
    </customValue>
    <customValue>
        <fullName>Tamil Nadu</fullName>
    </customValue>
    <customValue>
        <fullName>Telangana</fullName>
    </customValue>
    <customValue>
        <fullName>Uttar Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Jharkhand</fullName>
    </customValue>
    <description>Indian States</description>
    <masterLabel>Indian States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestSetupMethod.cls
@isTest
public class TestSetupMethod {
    @isTest
    public static User createUser() {
    
        User u = new User();
        u.FirstName = 'John';
        u.LastName = 'Doe';
        u.Email = 'john.doe@example.com';
        u.Username = 'john.doedfbfb@example.com';
        u.ProfileId = '00e2w000001MpKL';
        u.EmailEncodingKey= 'ISO-8859-1';
        u.LanguageLocaleKey= 'en_US';
        u.LocaleSidKey= 'en_US';
        u.TimeZoneSidKey= 'America/Los_Angeles';
        u.Alias = 'jodfe';
        return u;
    
    }
    @isTest
     public static Distributor__c createDistributor() {
    
        Distributor__c d = new Distributor__c();
            d.Name = 'Test Akash';
            d.Distributor_Contact_Person__c ='Akash';
            d.Distributor_Mobile__c ='0000000000';
            d.Credit_Limit__c = 25000;
            d.Active__c =True;
     		
         return d;
    
    }
    
     public static Dealer__c createDealer(Id userId,Id distributorId) {
         
        Dealer__c deal = new Dealer__c();
            deal.Name = 'Test Child 1';
            deal.Dealer_Mobile__c = '0000000000'; 
            deal.Distributor__c = distributorId;
            deal.Dealer_Address__c ='ddddd';
            deal.Active__c =true;
            deal.Employee_Names__c =userId;
            deal.Monthly_Target__c = 15000;
            deal.Weekly_Target__c = 3000;
         return deal;
    }
    public static Dealer__c createDealerWithoutUser(Id distributorId) {
         
        Dealer__c deal = new Dealer__c();
            deal.Name = 'Test Child 1';
            deal.Dealer_Mobile__c = '0000000000'; 
            deal.Distributor__c = distributorId;
            deal.Dealer_Address__c ='ddddd';
            deal.Active__c =true;
            deal.Monthly_Target__c = 15000;
            deal.Weekly_Target__c = 3000;
         return deal;
    }
    
     public static Employee__c createEmployee() {
         
       Employee__c emp = new Employee__c();
        
            emp.Name = 'Test';
            emp.Mobile_Number__c = '7744839497';
            emp.Employee_Email__c = 'test@example.com';
            emp.Employee_Monthly_Target__c = 1500;
      		emp.Employee_Monthly_Achievement__c =1000;
            
          return emp;
    }
    
    
    
    @isTest
     public static Lead__c createFarmer() {
    
        Lead__c l = new Lead__c();	
        l.Farmer_First_Name__c = 'Akash Chavan';
        l.Mobile_Number__c = '9111000000';
        l.Pond_Digging_Done__c = 'Yes';
        l.Tehsil__c = 'a082w000009l4t9AAA';
        l.Products_Interested__c = 'Jalasanchay';
        return l;
    
    }
    
    @isTest
     public static District__c createDistrict() {
    
        District__c l = new District__c();	
        l.Name = 'Sindhudurg';
        l.State__c = 'Maharashtra';
        
        return l;

    }
    
    
     public static Tehsil__c createTehsils(Id disId) {
    
        Tehsil__c l = new Tehsil__c();	
        l.District__c = disId;
        l.Name = 'Devgad';
        
        return l;

    }
    
    @isTest
     public static Product__c createProduct() {
    
        Product__c p = new Product__c();	
        p.Name = 'Jalasanchay-Type2-2x4m';
        p.Product_Name__c = 'Jalasanchay';
        p.Product_Group__c = 'Pond Liner';
        p.Unit_of_Sale__c = 'Sq M';
        p.Product_For__c= 'Avana Products'; 
       
        return p;
    
    }
    
    
    
     public static Opportunity__c createProductInformation(Id DealerId,Id ProductId,Id FarmerId) {
    
        Opportunity__c o = new Opportunity__c();
        RecordType logRecordTypeId = [select developerName from RecordType WHERE DeveloperName = 'Jalasanchay'];               
        o.RecordtypeId = logRecordTypeId.Id;
        o.Opportunity_Stage__c = 'Interested';
        o.Jalasanchay_Product_Type__c = 'Jalasanchay';
        o.Dealer__c = DealerId;
        o.Invoice_Date__c = Date.today()-31;
        o.Product__c= ProductId;
        o.Lead__c =FarmerId;
        
        o.Pondliner_Size_Requested_Required_Sq_Mt__c = 250;
        return o;
    
    }
    
      public static List<Dealer_with_Tehsil__c> createListDealerWithTehsil(Id tehsilId,Id dealerId) {
        List<Dealer_with_Tehsil__c> AccountList = new List<Dealer_with_Tehsil__c>();
        for(integer i = 0; i<10 ; i++) {
            Dealer_with_Tehsil__c dwt = new Dealer_with_Tehsil__c();
            dwt.Tehsil_Name__c =tehsilId;
            dwt.Dealer__c = dealerId;
           
         }
        return AccountList;
    }
    
    public static Dealer_with_Tehsil__c createDealerWithTehsils(Id tehsilId,Id dealerId) {
    
        Dealer_with_Tehsil__c l = new Dealer_with_Tehsil__c();	
        l.Tehsil_Name__c = tehsilId;
        l.Dealer__c = dealerId;
        l.This_Month_Achievement__c=1000;
        l.Previous_Month_Achievement__c=1500;
        l.Last_Three_Month_Achievement__c=2000;
        
        return l;

    }
    
    public static List<Dealer__c> createListDealer(Id distributorId,Id EmpId) {
        List<Dealer__c> dealerList = new List<Dealer__c>();
        for(integer i = 0; i<10 ; i++) {
            Dealer__c deal = new Dealer__c();
            deal.Name = 'Test Child 1';
            deal.Dealer_Mobile__c = '0000000000'; 
            deal.Distributor__c = distributorId;
            deal.Dealer_Address__c ='ddddd';
            deal.Active__c =true;
            deal.Employee_Names__c=EmpId;
            
           dealerList.add(deal);
         }
        return dealerList;
    }
    
    public static List<Employee__c> createListEmployee() {
         
      
            List<Employee__c> EmpList = new List<Employee__c>();
        for(integer i = 0; i<10 ; i++) {
            Employee__c emp = new Employee__c();
            emp.Name = 'Test';
            emp.Mobile_Number__c = '7744839497';
            emp.Employee_Email__c = 'test@example.com';
            emp.Employee_Monthly_Target__c = 1500;
      		emp.Employee_Monthly_Achievement__c =1000;
            
            EmpList.add(emp);
          
         }
        return EmpList;
    
    }
    

}