force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 Digits number.</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address Landmark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 digits Mobile No</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_First_Name__c</fullName>
    <label>Farmer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Middle_Name__c</fullName>
    <label>Farmer Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConverted (old)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kisan March 2022</fullName>
                <label>Lead - Kisan March 2022</label>
            </value>
            <value>
                <fullName>Dispatch Email</fullName>
            </value>
            <value>
                <fullName>TV Ad</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Subsidy List</fullName>
            </value>
            <value>
                <fullName>Toll Free Number Inquiry</fullName>
                <label>Toll Free Number Enquiry</label>
            </value>
            <value>
                <fullName>Gram Sabha</fullName>
            </value>
            <value>
                <fullName>Pond visit</fullName>
            </value>
            <value>
                <fullName>Individual meetings</fullName>
            </value>
            <value>
                <fullName>Krishi Darshan</fullName>
            </value>
            <value>
                <fullName>Bazaar Day</fullName>
            </value>
            <value>
                <fullName>Referred by other farmer</fullName>
            </value>
            <value>
                <fullName>Meeting during pond installation</fullName>
            </value>
            <value>
                <fullName>Marketyard</fullName>
                <label>Marketyard Referral</label>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Baramati KVK Exhibition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <inlineHelpText>Mobile Number Should be 10 Digits</inlineHelpText>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Enquiry Created</fullName>
            </value>
            <value>
                <fullName>Not Converted</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Contact Later</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <formula>Lead__r.Tehsil__r.Name</formula>
    <label>Tehsil</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadConvertClass.cls
public with sharing class LeadConvertClass {
    @AuraEnabled
    public static Lead__c getLeadName( string lId) {
        Lead__c ld=[select Farmer_First_Name__c,Stages__c from Lead__c where id=:lId];
        string CustomerName=ld.Farmer_First_Name__c;
        system.debug('NAME:::'+CustomerName);
        return ld ;
    }
    
    @AuraEnabled
    public static Boolean OppTest( string lId){
        List<Opportunity__c> oplt=[Select Id from Opportunity__c where Lead__c=:lId];
        if(oplt.size()>0){
            return true;
        }
        else{
            return false;
        }
    }
    
    @AuraEnabled
    public static Boolean OppStageTest(string lId){
        List<Opportunity__c> opStageList=[select id,Name from Opportunity__c where Lead__c=:lId and Opportunity_Stage__c='Converted' ];
        if(opStageList.size()>0){
            return true;
        }
        else{
            return false;
        }
    }
    
    @AuraEnabled
    public static string  LeadCnvrt( string ldId, string fName){
        Lead__c lds=[select id,Farmer_First_Name__c,Stages__c,Mobile_Number__c,Lead_Source__c,Address__c,Alternate_Mobile_No__c,Dealer__c,Tehsil__c from Lead__c where id =:ldId];
        List<Opportunity__c> opList=[select id,Name from Opportunity__c where Lead__c=:ldId and Opportunity_Stage__c='Converted' ];
        List<Account> acnt=[select id,Phone from Account where Phone=:lds.Mobile_Number__c];
        system.debug('Acc Phn::'+acnt);
        system.debug('oppList::'+opList);
        List<Opportunity__c> getopplist=LeadConvertClass.getrelatedopp(ldId);
        System.debug('related opportunity:::'+getopplist);
        String Statusofcheck;        
        /*  if(acnt.size()>0 && acnt!=null){
System.debug('inside duplicate:::');
Statusofcheck='duplicate';
System.debug('Statusofcheck::::'+Statusofcheck);
return Statusofcheck;
}
else{*/
        List<Account> acclist=new List<Account>();
        if(opList.size()>0 && opList!=null){
            System.debug('inside if oppo:::');
            Account acc=new Account();
            /*if(mName!=null){
                acc.name=fName+' '+mName+' '+lName;
            }else{
                acc.name=fName+' '+lName;
            }*/
            acc.Name=fName;
            //acc.Farmer_Middle_Name__c=mName;
            acc.Phone=lds.Mobile_Number__c;
            acc.Alternate_Mobile_No__c=lds.Alternate_Mobile_No__c;
            //acc.Dealer__c=lds.Dealer__c;
            acc.Tehsil__c=lds.Tehsil__c;
            acc.Lead_Source__c=lds.Lead_Source__c;
            acc.Address__c=lds.Address__c;
            acclist.add(acc);
        }       
        if(acclist.size()>0 && acclist!=null){
            System.debug('inside acclist::::::'+acclist);
            Database.DMLOptions dml = new Database.DMLOptions(); 
            dml.DuplicateRuleHeader.allowSave = true;
            dml.DuplicateRuleHeader.runAsCurrentUser = true;
            Database.SaveResult[] saveResultList = Database.insert(acclist, dml);
            
            // Iterate through saveResultList based on isSuccess capture the failed records
            for (Database.SaveResult sr : saveResultList) {
                if (sr.isSuccess()==true) {
                    lds.IsConverted__c=true;
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully inserted account. Account ID: ' + acclist[0].Id);
                    lds.Stages__c='Converted';
                    update lds;
                    List<Opportunity__c> listupdateopp=new List<Opportunity__c>();
                    if(getopplist.size()>0 && getopplist!=null){
                        for(Opportunity__c opp:getopplist){
                            opp.Customer__c=sr.getId();
                            listupdateopp.add(opp);
                        }
                        System.debug('final update opplist:::::'+listupdateopp);
                        if(listupdateopp.size()>0 && listupdateopp!=null){
                            update listupdateopp;
                        }
                    }
                    //Statusofcheck=sr.getId();
                    /********modified:21-10-20 start********/   
                    if(acnt.size()>0 && acnt!=null){
                        Statusofcheck=sr.getId()+'duplicate';
                        system.debug('AccId with Duplicate:::'+Statusofcheck);
                    }
                    else{
                        Statusofcheck=sr.getId();
                        system.debug('Only acc Id:::'+Statusofcheck);
                    }
                    /********modified:21-10-20 end********/        
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Account fields that affected this error: ' + err.getFields());
                        Statusofcheck='error';
                    }
                }
            }
        }
        
        return Statusofcheck; 
        //}    
    }
    
    @AuraEnabled
    public static List<Opportunity__c>  getrelatedopp( string leadId){
        System.debug('lead id:::'+leadId);
        List<Opportunity__c> opplist=[select id,Lead__c from opportunity__c where Lead__c =:leadId];
        if(opplist.size()>0 && opplist!=null){
            return opplist;
        }
        else{
            return null;
        }
        
    }
}