force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Dealer_Email__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Email__c</fullName>
    <label>Dealer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Weekly_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Weekly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SendEmailBatch.cls
global class SendEmailBatch implements Database.Batchable<sObject> {
    
    
     global Database.QueryLocator start(Database.BatchableContext BC) {
        // Query the records you want to send emails to

        return Database.getQueryLocator([SELECT Id, Name, Employee_Email__c,Employee_Monthly_Target__c,Active__c,Employee_Monthly_Achievement__c FROM Employee__c Where Active__c = true AND Employee_Email__c != null ]);
    }

    global void execute(Database.BatchableContext BC, List<Employee__c> scope) {
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        
        // Iterate over the records and add email messages to list
        for (Employee__c c : scope) {
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            Decimal a = c.Employee_Monthly_Target__c - c.Employee_Monthly_Achievement__c;
            if(a<0){
                a=0;
            }
            
            email.setToAddresses(new String[]{c.Employee_Email__c});
            email.setOrgWideEmailAddressId('0D2C500000000E8KAI');
            email.setSubject('Target Details: '+ ' ' +c.Name);
            email.setPlainTextBody('Hello ' + c.Name + ',\n\n'
                + 'Hope you had a wonderful month till now.\n\n'
               // + 'Your Area of Operation is : ' + c.Name + '\n'
                + 'Your Target for the month is : ' + c.Employee_Monthly_Target__c + '\n'    
                + 'You have Completed: ' + c.Employee_Monthly_Achievement__c + '\n'
                + 'Your Balance for the month is :'+ a +'\n\n'
                + 'In case you have any difficulty in reaching the target please speak to your manager for support.\n\n'                   
                + 'Warm Regards,'+'\n' 
                +  'Avana Operations Team \n');
            System.debug(email);
            emailList.add(email);
        }
        
        // Send the email messages
        Messaging.sendEmail(emailList);
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Task Finished !!');
    }
    
    
   /* global Database.QueryLocator start(Database.BatchableContext BC) {
        // Query the records you want to send emails to

        return Database.getQueryLocator([SELECT Id, Name, Dealer_Email__c,Active__c,Weekly_Target__c,Weekly_Achievement__c,Monthly_Target__c,This_Month_Achievement__c FROM Dealer__c Where Monthly_Target__c != null AND Dealer_Email__c != null AND Active__c != false]);
    }

    global void execute(Database.BatchableContext BC, List<Dealer__c> scope) {
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        
        // Iterate over the records and add email messages to list
        for (Dealer__c c : scope) {
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            Decimal a = c.Monthly_Target__c - c.This_Month_Achievement__c;
            if(a<0){
                a=0;
            }
            
            email.setToAddresses(new String[]{c.Dealer_Email__c});
            email.setOrgWideEmailAddressId('0D2C500000000E8KAI');
            email.setSubject('Target Not Completed: ' +c.Name);
            email.setPlainTextBody('Hello ' + c.Name + ',\n\n'
                + 'Hope you had a wonderful month till now.\n\n'
                + 'Your Area of Operation is : ' + c.Name + '\n'
                + 'Your Target for the month is : ' + c.Monthly_Target__c + '\n'    
                + 'You have Completed: ' + c.This_Month_Achievement__c + '\n'
                + 'Your Balance for the month is :'+ a +'\n\n'
                + 'In case you have any difficulty in raching the target please speak to your manager for the support.\n\n'                   
                + 'Warm Regards,'+'\n' 
                +  'Avana Operations Team \n');
            System.debug(email);
            emailList.add(email);
        }
        
        // Send the email messages
        Messaging.sendEmail(emailList);
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Task Finished !!');
    }*/
}