force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>Credit limit for dealer - usually used for direct dealers (otherwise distributor is given total credit limit to be used across their dealers)</description>
    <inlineHelpText>For Direct Dealers</inlineHelpText>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Dealer_Address__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Address__c</fullName>
    <label>Dealer Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Dealer_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Mobile__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Dealer Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Employee_Names__c.field-meta.xml
<CustomField>
    <fullName>Employee_Names__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Last_Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Achievement__c</fullName>
    <label>Last Three Month Achievement</label>
    <summarizedField>Dealer_with_Tehsil__c.Last_Three_Month_Achievement__c</summarizedField>
    <summaryForeignKey>Dealer_with_Tehsil__c.Dealer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Previous_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Achievement__c</fullName>
    <label>Previous Month Achievement</label>
    <summarizedField>Dealer_with_Tehsil__c.Previous_Month_Achievement__c</summarizedField>
    <summaryForeignKey>Dealer_with_Tehsil__c.Dealer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Previous_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Weekly_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Weekly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/Dealer_with_Tehsil__c.object-meta.xml
<CustomObject>
    <label>Dealer with Tehsil</label>
    <nameField>
        <label>Dealer with Tehsils Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer with Tehsils</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>Dealer__r.Active__c</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil_Name__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>Dealer__r.Employee_Names__r.Name</formula>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Previous_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <description>Credit Limit for distributor. Dispatches above this limit may not be approved.</description>
    <label>Credit Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Distributor_Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact_Person__c</fullName>
    <label>Distributor Contact Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Distributor__c/fields/Distributor_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Mobile__c</fullName>
    <inlineHelpText>10 Digits mobile Number</inlineHelpText>
    <label>Distributor Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last Three Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Three_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last Three Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/Last_Three_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Target__c</fullName>
    <formula>IF(Month_Number__c = 1, December_Target__c+November_Target__c+October_Target__c,
IF(Month_Number__c = 2, January_Target__c +December_Target__c+November_Target__c,
IF(Month_Number__c = 3, February_Target__c +January_Target__c +December_Target__c,
IF(Month_Number__c = 4, March_Target__c+February_Target__c +January_Target__c ,
IF(Month_Number__c = 5, April_Target__c+March_Target__c+February_Target__c ,
IF(Month_Number__c = 6, May_Target__c+April_Target__c+March_Target__c,
IF(Month_Number__c = 7, June_Target__c+May_Target__c+April_Target__c,
IF(Month_Number__c = 8, July_Target__c+June_Target__c+May_Target__c,
IF(Month_Number__c = 9, August_Target__c+July_Target__c+June_Target__c,
IF(Month_Number__c = 10, September_Target__c+August_Target__c+July_Target__c,
IF(Month_Number__c = 11, October_Target__c+September_Target__c+August_Target__c,
IF(Month_Number__c = 12, November_Target__c+ October_Target__c+ September_Target__c, 0) ) ) ) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Three Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/Previous_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Target__c</fullName>
    <formula>IF( Month_Number__c = 2, January_Target__c ,
IF(Month_Number__c = 3, February_Target__c ,
IF(Month_Number__c = 4, March_Target__c,
IF(Month_Number__c = 5, April_Target__c,
IF(Month_Number__c = 6, May_Target__c,
IF(Month_Number__c = 7, June_Target__c,
IF(Month_Number__c = 8, July_Target__c,
IF(Month_Number__c = 9, August_Target__c,
IF(Month_Number__c = 10, September_Target__c,
IF(Month_Number__c = 11, October_Target__c,
IF(Month_Number__c = 12, November_Target__c,
IF(Month_Number__c = 1, December_Target__c, 0) ) ) ) ) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateUserTargetHandlerTest.cls
@isTest
private class UpdateUserTargetHandlerTest {
  /*  @testSetup
    static void createTestData() {
        User u = new User(
        FirstName = 'John',
        LastName = 'Doe',
        Email = 'john.doe@example.com',
        Username = 'john.doe@example.com',
        ProfileId = '00e2w000001MpKL'
        );
        insert u;
        
        Distributor__c d = new Distributor__c(
            Name = 'Test Akash',
            Distributor_Contact_Person__c ='Akash',
            Distributor_Mobile__c ='0000000000',
            Credit_Limit__c = 25000,
            Active__c =True
        );
        
        insert d;

        
        Dealer__c child1 = new Dealer__c(
            Name = 'Test Child 1',
            Dealer_Mobile__c = '0000000000', 
            Distributor__c = d.Id,
            Dealer_Address__c ='ddddd',
            Active__c =true,
            Employee_Name__c =u.Id,
            Monthly_Target__c = 15000,
            Weekly_Target__c = 3000

            );
            
        Dealer__c child2 = new Dealer__c(
            Name = 'Test Child 2',
            Dealer_Mobile__c = '0000000000', 
            Distributor__c = d.Id,
            Dealer_Address__c ='ddddd',
            Active__c =true,
            Employee_Name__c =u.Id,
            Monthly_Target__c = 20000,
            Weekly_Target__c = 5000


            );    
        
       
        insert new List<Dealer__c>{child1, child2};
    }

    
     @isTest
    static void testTargetUpdate() {
        User u = new User(
        FirstName = 'John',
        LastName = 'Doe',
        Email = 'john.doe@example.com',
        Username = 'john0002.doe@example.com',
        ProfileId = '00e2w000001MpKL',
        EmailEncodingKey= 'ISO-8859-1',
        LanguageLocaleKey= 'en_US',
        LocaleSidKey= 'en_US',
        TimeZoneSidKey= 'America/Los_Angeles',
        Alias = 'jodfe'    
        );
        
        insert u;
        
        // Ensure Total_Amount__c is initially 0
        System.assertEquals(null, u.Monthly_Target__c);
        System.assertEquals(null, u.Weekly_Target__c);
        
        Distributor__c d = new Distributor__c(
            Name = 'Test Akash',
            Distributor_Contact_Person__c ='Akash',
            Distributor_Mobile__c ='0000000000',
            Credit_Limit__c = 25000,
            Active__c =True
        );
        
        insert d;
        
        // Insert a new child record
        Dealer__c newChild = new Dealer__c(
            Name = 'Test Child 1',
            Dealer_Mobile__c = '0000000000', 
            Distributor__c = d.Id,
            Dealer_Address__c ='ddddd',
            Active__c =true,
            Employee_Name__c =u.Id,
            Monthly_Target__c = 15000,
            Weekly_Target__c = 3000

            );
            
        insert newChild;
        
        // Ensure Total_Amount__c is updated correctly
        User parent = [SELECT Id, Monthly_Target__c,Weekly_Target__c FROM User WHERE Id = :u.Id];
        System.assertEquals(15000, parent.Monthly_Target__c);
        System.assertEquals(3000, parent.Weekly_Target__c);
        
        // Update an existing child record
        Dealer__c existingChild = [SELECT Id, Monthly_Target__c,Weekly_Target__c  FROM Dealer__c WHERE Employee_Name__c = :u.Id LIMIT 1];
        existingChild.Monthly_Target__c = 20000;
        existingChild.Weekly_Target__c = 3500;
        
        update existingChild;
        
        // Ensure Total_Amount__c is updated correctly
        parent = [SELECT Id, Monthly_Target__c,Weekly_Target__c FROM User WHERE Id = :u.Id];
        System.assertEquals(20000, parent.Monthly_Target__c);
        System.assertEquals(3500, parent.Weekly_Target__c);
        
        // Delete a child record
      delete existingChild;
        
        // Ensure Total_Amount__c is updated correctly
       // parent = [SELECT Id, Monthly_Target__c,Weekly_Target__c FROM User WHERE Id = :u.Id];
        System.assertEquals(0, parent.Monthly_Target__c);
        System.assertEquals(0, parent.Weekly_Target__c);
    }

    
 static testMethod void test1()
  {
             
      Test.startTest();
      	 District__c di =TestSetupMethod.createDistrict();
         database.insert(di);
        
         Tehsil__c teh = TestSetupMethod.createTehsils(di.Id);
         database.insert(teh);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
        
         Employee__c emp =TestSetupMethod.createEmployee();
         database.insert(emp);
         
         Dealer__c dea= TestSetupMethod.createDealerWithoutUser(dis.Id);
         dea.Employee_Names__c=emp.Id;
         database.insert(dea);
      	 
        
         Dealer_with_Tehsil__c deteh= TestSetupMethod.createDealerWithTehsils(teh.Id,dea.Id);
         database.insert(deteh);
         
      	 
         dea.Last_Three_Month_Target__c =2500;
      	 update dea;
       
      
      // UpdateUserTargetHandler.CCHelp(); 
        
      test.stopTest();
  }*/
   @isTest
    public static void testTargetUpdate() {
        District__c di =TestSetupMethod.createDistrict();
         database.insert(di);
        
         Tehsil__c teh = TestSetupMethod.createTehsils(di.Id);
         database.insert(teh);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
        
         Employee__c emp =TestSetupMethod.createEmployee();
         database.insert(emp);
         
         Dealer__c dea= TestSetupMethod.createDealerWithoutUser(dis.Id);
         dea.Employee_Names__c=emp.Id;
         database.insert(dea);
      	 
        
        Test.startTest();
        dea.Employee_Names__c=emp.Id;
        database.update(dea);
        Test.stopTest();
        
        // Query the updated Employee__c records
        Employee__c e = [SELECT Id, Employee_Monthly_Target__c, Employee_Monthly_Achievement__c,
                                              Last_Three_Month_Achievement__c, Last_Three_Month_Target__c,
                                              Previous_Month_Achievement__c, Previous_Month_Target__c
                                              FROM Employee__c WHERE Id =: emp.Id];
        
        // Assert the expected values
        
            // Perform assertions for target and achievement fields
            System.assertEquals(1500, e.Employee_Monthly_Target__c);
            System.assertEquals(0, e.Previous_Month_Target__c);
            System.assertEquals(0, e.Last_Three_Month_Target__c);
            System.assertEquals(1000, e.Employee_Monthly_Achievement__c);
            System.assertEquals(0, e.Previous_Month_Achievement__c);
            System.assertEquals(0, e.Last_Three_Month_Achievement__c);
        
    }
    
     @isTest
    static void testUpdateDealerMonthlyTarget() {
        
      
        Test.startTest();
        UpdateUserTargetHandler.CCHelp();
        Test.stopTest();
            }
    
}