force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Dealer_Address__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Address__c</fullName>
    <label>Dealer Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Dealer_Email__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Email__c</fullName>
    <label>Dealer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Dealer_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Mobile__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Dealer Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Weekly_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Weekly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SendEmailBatchTest.cls
@isTest
private class SendEmailBatchTest {
	 @isTest static void testSendEmailBatch() {
       Test.startTest();
         List<Employee__c> emp = new List<Employee__c>();
        for (Integer i = 0; i < 20; i++) {
            emp.add(new Employee__c(Name = 'Test'+ i, Mobile_Number__c = '7744839497', Employee_Email__c = 'test' + i + '@example.com',Active__c=True,
                                  Employee_Monthly_Target__c = 1500,Employee_Monthly_Achievement__c =1000));
            
            
        }
        insert emp;
        
		String cronExpression = '0 0 0 20 5 ? 2023'; // Runs on March 15, 2023 at midnight
        String jobId = System.schedule('MyEmailBatchJobs', cronExpression, new SendEmailScheduler());

        List<CronTrigger> triggers = [SELECT Id, CronExpression, CronJobDetail.Name, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals(1, triggers.size());
        CronTrigger trigg = triggers[0];
        System.assertEquals(cronExpression, trigg.CronExpression);

        Test.stopTest();  
         
         
         
         
         
         // Insert test records
      /*	Test.startTest();
        List<Dealer__c> dealer = new List<Dealer__c>();
        User newUser = TestSetupMethod.createUser();
        database.insert(newUser);
         
        Distributor__c dis= TestSetupMethod.createDistributor();
        database.insert(dis);
        
        for (Integer i = 0; i < 200; i++) {
            dealer.add(new Dealer__c(Name = 'Test'+ i, Dealer_Mobile__c = '7744839497', Dealer_Email__c = 'test' + i + '@example.com',
                                   Distributor__c = dis.Id,Dealer_Address__c='ddddd',
                                  Active__c = true,Employee_Name__c = newUser.Id ,
                                  Monthly_Target__c = 1500,Weekly_Target__c =1000));
            
            
        }
        insert dealer;
        
		String cronExpression = '0 0 0 16 5 ? 2023'; // Runs on March 15, 2023 at midnight
        String jobId = System.schedule('MyEmailBatchJob', cronExpression, new SendEmailScheduler());

        List<CronTrigger> triggers = [SELECT Id, CronExpression, CronJobDetail.Name, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals(1, triggers.size());
        CronTrigger trigg = triggers[0];
        System.assertEquals(cronExpression, trigg.CronExpression);

        Test.stopTest(); 
        
         
       List<Messaging.SingleEmailMessage> sentEmails = [SELECT Id, ToAddress, Subject, HtmlBody FROM Messaging.SingleEmailMessage WHERE ToAddress IN :dealer];
        System.assertEquals(200, sentEmails.size());
        for (Messaging.SingleEmailMessage email : sentEmails) {
            System.assertEquals('Test Email Subject', email.Subject);
            System.assertEquals('Test Email Body', email.HtmlBody);
        }
        
         */
    }
   
    

}