force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Current_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Current_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Current Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Employee_Names__c.field-meta.xml
<CustomField>
    <fullName>Employee_Names__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/Dealer_with_Tehsil__c.object-meta.xml
<CustomObject>
    <label>Dealer with Tehsil</label>
    <nameField>
        <label>Dealer with Tehsils Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer with Tehsils</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil_Name__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Tehsil_Name__c.field-meta.xml
<CustomField>
    <fullName>Tehsil_Name__c</fullName>
    <label>Tehsil Name</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateDealertargetsTest.cls
@isTest
public class UpdateDealertargetsTest {
  
    @isTest
    static void testUpdateDealerMonthlyTargets() {
        
        User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Employee__c emp= TestSetupMethod.createEmployee();
         database.insert(emp);
        
         Dealer__c dea= TestSetupMethod.createDealer(newUser.Id,dis.Id);
         dea.Employee_Names__c =emp.Id;
         database.insert(dea);
         
         District__c dist= TestSetupMethod.createDistrict();
         database.insert(dist);
    
         Tehsil__c teh= TestSetupMethod.createTehsils(dist.Id);
         database.insert(teh);  
        
        List<Dealer_with_Tehsil__c> dealerWithTehsils = new List<Dealer_with_Tehsil__c>();
        dealerWithTehsils.add(new Dealer_with_Tehsil__c(Name='Test Dealer with Tehsil', Dealer__c=dea.Id, Tehsil_Name__c = teh.Id));
        dealerWithTehsils.add(new Dealer_with_Tehsil__c(Name='Test Dealer with Tehsil 2', Dealer__c=dea.Id, Tehsil_Name__c = teh.Id));
        insert dealerWithTehsils;
        Test.startTest();
        // Call the method to be tested
      //  UpdateDealertargets.updateDealerMonthlyTargets(dealerWithTehsils);
        update dealerWithTehsils;
        Test.stopTest();
        // Retrieve the updated dealer record
        Dealer__c updatedDealer = [SELECT Id, Current_Month_Target__c FROM Dealer__c WHERE Id=:dea.Id];
        
        // Verify that the dealer's current month target has been updated
       // System.assertEquals(0, updatedDealer.Current_Month_Target__c);
    }
     @isTest
    static void testUpdateDealerMonthlyTarget() {
        
      
        Test.startTest();
        UpdateDealertargets.CCHelp();
        Test.stopTest();
            }
}