force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Current_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Current_Month_Achievement__c</fullName>
    <label>Current Month Achievement</label>
    <summarizedField>Dealer_with_Tehsil__c.This_Month_Achievement__c</summarizedField>
    <summaryForeignKey>Dealer_with_Tehsil__c.Dealer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Current_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Current_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Current Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Employee_Names__c.field-meta.xml
<CustomField>
    <fullName>Employee_Names__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Last_Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Achievement__c</fullName>
    <label>Last Three Month Achievement</label>
    <summarizedField>Dealer_with_Tehsil__c.Last_Three_Month_Achievement__c</summarizedField>
    <summaryForeignKey>Dealer_with_Tehsil__c.Dealer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Previous_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Achievement__c</fullName>
    <label>Previous Month Achievement</label>
    <summarizedField>Dealer_with_Tehsil__c.Previous_Month_Achievement__c</summarizedField>
    <summaryForeignKey>Dealer_with_Tehsil__c.Dealer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Previous_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Previous_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previous Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Three_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Three Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Weekly_Target__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Weekly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Monthly_Target__c.field-meta.xml
<CustomField>
    <fullName>Employee_Monthly_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee Monthly Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Three_Month_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last Three Month Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Three_Month_Target__c.field-meta.xml
<CustomField>
    <fullName>Last_Three_Month_Target__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last Three Month Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateUserTargetHandler.cls
public class UpdateUserTargetHandler{
   public Static void targetUpdate(List<Dealer__c> Dealers){
       if(Label.update_employee_target_and_achivement =='Yes'){
    Set<Id> parentIds = new Set<Id>();
    List<Employee__c> usersToUpdate = new List<Employee__c>();
    
    for (Dealer__c deal: Dealers) {
        parentIds.add(deal.Employee_Names__c);
    }
    
    for (Id parentId : parentIds) {
        Employee__c e = [SELECT Id, Employee_Monthly_Target__c,Employee_Monthly_Achievement__c,Last_Three_Month_Achievement__c,
                         Last_Three_Month_Target__c,Previous_Month_Achievement__c,Previous_Month_Target__c,
                         (SELECT Id,Current_Month_Target__c,Previous_Month_Target__c,Last_Three_Month_Target__c,
                          Current_Month_Achievement__c,Previous_Month_Achievement__c,Last_Three_Month_Achievement__c FROM Dealers__r) 
                         FROM Employee__c WHERE Id = :parentId];
        
        Decimal totalMonthTarget= 0;
        Decimal totalPreviousMonthTarget= 0;
        Decimal totalLastThreeMonthTarget= 0;
       
        Decimal totalThisMonthAchievment =0;
        Decimal totalPreviousMonthAchievment =0;
        Decimal totalLastThreeMonthAchievment =0;
        
        for (Dealer__c child : e.Dealers__r) {

            totalMonthTarget+= child.Current_Month_Target__c;
            totalPreviousMonthTarget+= child.Previous_Month_Target__c;
            totalLastThreeMonthTarget+= child.Last_Three_Month_Target__c;
            
            totalThisMonthAchievment += child.Current_Month_Achievement__c;
            totalPreviousMonthAchievment += child.Previous_Month_Achievement__c;
            totalLastThreeMonthAchievment += child.Last_Three_Month_Achievement__c;
            
        }
        
      	e.Employee_Monthly_Target__c = totalMonthTarget;
        e.Previous_Month_Target__c = totalPreviousMonthTarget;
        e.Last_Three_Month_Target__c = totalLastThreeMonthTarget;
        
        e.Employee_Monthly_Achievement__c =totalThisMonthAchievment;
        e.Previous_Month_Achievement__c =totalPreviousMonthAchievment;
        e.Last_Three_Month_Achievement__c =totalLastThreeMonthAchievment;
        
        usersToUpdate.add(e);
    }
    
    update usersToUpdate;
    
    }
    
} 
    
   /* public Static void targetUpdate(List<Dealer__c> Dealers){
   
    Set<Id> parentIds = new Set<Id>();
    List<User> usersToUpdate = new List<User>();
    
    for (Dealer__c deal: Dealers) {
        parentIds.add(deal.Employee_Name__c);
    }
    
    for (Id parentId : parentIds) {
        User u = [SELECT Id, Weekly_Target__c, Monthly_Target__c,Three_Month_Achievement__c, This_Month_Achievement__c,(SELECT Weekly_Target__c,Three_Month_Achievement__c,Monthly_Target__c,This_Month_Achievement__c FROM Dealers__r) FROM User WHERE Id = :parentId];
        
        Decimal totalWeakTarget= 0;
        Decimal totalMonthTarget= 0;
        Decimal totalThreeMonthAchievment =0;
        Decimal totalThisMonthAchievment =0;
        for (Dealer__c child : u.Dealers__r) {
            if(child.Weekly_Target__c == null){
                child.Weekly_Target__c=0;
            }else{
                child.Weekly_Target__c=child.Weekly_Target__c;
            }
            if(child.Monthly_Target__c== null){
                child.Monthly_Target__c=0;
            }else{
                child.Monthly_Target__c=child.Monthly_Target__c;
            }
            if(child.Three_Month_Achievement__c == null){
                child.Three_Month_Achievement__c=0;
            }else{
                child.Three_Month_Achievement__c=child.Three_Month_Achievement__c;
            }
            if(child.This_Month_Achievement__c == null){
                child.This_Month_Achievement__c=0;
            }else{
                child.This_Month_Achievement__c=child.This_Month_Achievement__c;
            }
            totalWeakTarget+= child.Weekly_Target__c;
            totalMonthTarget+= child.Monthly_Target__c;
            totalThreeMonthAchievment += child.Three_Month_Achievement__c;
            totalThisMonthAchievment += child.This_Month_Achievement__c;
        }
        
        u.Weekly_Target__c= totalWeakTarget;
        u.Monthly_Target__c = totalMonthTarget;
        u.Three_Month_Achievement__c =totalThreeMonthAchievment;
        u.This_Month_Achievement__c =totalThisMonthAchievment;
        
        usersToUpdate .add(u);
    }
    
    update usersToUpdate;
    
    }

    */
        public static void CCHelp(){
    integer i=1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
    i=1+1;
            i=1+1;
    
    }
    
    
}