force-app/main/default/objects/Cluster_Sales_Manager__c/Cluster_Sales_Manager__c.object-meta.xml
<CustomObject>
    <label>Cluster Sales Manager</label>
    <nameField>
        <label>Cluster Sales Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cluster Sales Managers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster_Sales_Manager__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <label>Manager</label>
    <referenceTo>Manager__c</referenceTo>
    <relationshipLabel>Cluster Sales Managers</relationshipLabel>
    <relationshipName>Cluster_Sales_Managers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cluster_Sales_Manager__c/fields/Tehsil_Name__c.field-meta.xml
<CustomField>
    <fullName>Tehsil_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil Name</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Cluster Sales Managers</relationshipLabel>
    <relationshipName>Cluster_Sales_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Cluster_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Sales_Manager__c</fullName>
    <formula>Employee_Names__r.Cluster_Sales_Manager__r.Name</formula>
    <label>Cluster Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Employee_Names__c.field-meta.xml
<CustomField>
    <fullName>Employee_Names__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/Dealer_with_Tehsil__c.object-meta.xml
<CustomObject>
    <label>Dealer with Tehsil</label>
    <nameField>
        <label>Dealer with Tehsils Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer with Tehsils</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Cluster_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Sales_Manager__c</fullName>
    <formula>Dealer__r.Cluster_Sales_Manager__c</formula>
    <label>Cluster Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil_Name__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_with_Tehsil__c/fields/Tehsil_Name__c.field-meta.xml
<CustomField>
    <fullName>Tehsil_Name__c</fullName>
    <label>Tehsil Name</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealer with Tehsils</relationshipLabel>
    <relationshipName>Dealer_with_Tehsils</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Cluster_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Sales_Manager__c</fullName>
    <label>Cluster Sales Manager</label>
    <referenceTo>Cluster_Sales_Manager__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Tehsil__r.District__r.Name</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <label>Manager</label>
    <nameField>
        <label>Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Dealer_with_Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Dealer_with_Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer with Tehsil</label>
    <referenceTo>Dealer_with_Tehsil__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Product_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Dealer__r.Distributor__r.Name</formula>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Lead__r.District__c</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Product_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <formula>Lead__r.Tehsil__r.Name</formula>
    <label>Tehsil</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil_Name__c.field-meta.xml
<CustomField>
    <fullName>Tehsil_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil Name</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Product_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>SKU Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tehsil__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateRecordLastThreeMonthTest.cls
@isTest
public class UpdateRecordLastThreeMonthTest {
@isTest
    public static void UpdateLastThreeMonthTest(){
        
        Test.startTest();
        User newUser = TestSetupMethod.createUser();
         database.insert(newUser);
         
         Distributor__c dis= TestSetupMethod.createDistributor();
         database.insert(dis);
         
         Manager__c m =new Manager__c();
         m.Name ='Test Emmbi';
         database.insert(m);
         
         Cluster_Sales_Manager__c c =new Cluster_Sales_Manager__c();
         c.Name ='Test Emmbi';
         c.Manager__c = m.Id;
         database.insert(c);
         
         Employee__c emp= TestSetupMethod.createEmployee();
         emp.Cluster_Sales_Manager__c =c.Id;
         database.insert(emp); 
        
         Dealer__c dea= TestSetupMethod.createDealerWithoutUser(dis.Id);
         dea.Employee_Names__c = emp.Id;
         database.insert(dea);
         
         Product__c p= TestSetupMethod.createProduct();
         database.insert(p);
         
         Lead__c l =TestSetupMethod.createFarmer();
         database.insert(l);
        
         District__c dist= TestSetupMethod.createDistrict();
         database.insert(dist);

         Tehsil__c teh= TestSetupMethod.createTehsils(dist.Id);
         database.insert(teh);
        
         Dealer_with_Tehsil__c dwt =new Dealer_with_Tehsil__c();
     	 dwt.Tehsil_Name__c =teh.Id;
         dwt.Dealer__c = dea.Id;
		 database.insert(dwt);
         
         Opportunity__c Pi= TestSetupMethod.createProductInformation(dea.Id,p.Id,l.Id);
         database.insert(Pi);
         Pi.Dealer_with_Tehsil__c = dwt.Id;
         update Pi;
         
         String cronExpression = '0 0 0 14 6 ? 2023'; // Runs on March 15, 2023 at midnight
        String jobId = System.schedule('MyResetBatchJob', cronExpression, new UpdateRecordLastThreeMonth());

        List<CronTrigger> triggers = [SELECT Id, CronExpression, CronJobDetail.Name, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals(1, triggers.size());
        CronTrigger trigg = triggers[0];
        System.assertEquals(cronExpression, trigg.CronExpression);
        
        Test.stopTest();
        
    }
    
}