force-app/main/default/objects/Retail_Order__c/Retail_Order__c.object-meta.xml
<CustomObject>
    <label>Retail Order</label>
    <nameField>
        <displayFormat>RO-{0000}</displayFormat>
        <label>Retail Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order__c/fields/Prefered_Transport_Company__c.field-meta.xml
<CustomField>
    <fullName>Prefered_Transport_Company__c</fullName>
    <label>Prefered Transport Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMRUT LOGISTICS (ARCO)</fullName>
            </value>
            <value>
                <fullName>Avinash Cargo Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Batcotranslogistics Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>CHINTAN FREIGHT CARRIER</fullName>
            </value>
            <value>
                <fullName>GIRNAR CARGO ESCORT</fullName>
            </value>
            <value>
                <fullName>Lavakesh Roadlines</fullName>
            </value>
            <value>
                <fullName>LOCAL TRANSPORT</fullName>
            </value>
            <value>
                <fullName>OWN VEHICLE</fullName>
            </value>
            <value>
                <fullName>RISHABH ROADLINES</fullName>
            </value>
            <value>
                <fullName>RITWIZ ROADLINES</fullName>
            </value>
            <value>
                <fullName>Balaji Transport Company</fullName>
            </value>
            <value>
                <fullName>SECURE TRANS LOGISTICS</fullName>
            </value>
            <value>
                <fullName>Shree Nashik Goods TransportCo.</fullName>
                <label>Shree Nashik Goods Transport Co.</label>
            </value>
            <value>
                <fullName>Shree Shyam Logistics</fullName>
            </value>
            <value>
                <fullName>VISHWA LOGISTICS</fullName>
            </value>
            <value>
                <fullName>VRL Logistics Limited</fullName>
            </value>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Shree Krishna Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Retail_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Retail_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt Warehouse</label>
    <referenceTo>Retail_Warehouse__c</referenceTo>
    <relationshipLabel>Retail Orders</relationshipLabel>
    <relationshipName>Retail_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Warehouse__c/Retail_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Retail Warehouse</label>
    <nameField>
        <label>Retail Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FileUploadMultiController_TestClass.cls
@isTest
public class FileUploadMultiController_TestClass 
{
   @isTest
    static void testUploadFiles() {
        try{
              Retail_Warehouse__c testWarehouse = TestDataFactory.createRetailWarehouse();
        Retail_Order__c testOrder = TestDataFactory.createRetailOrderOther('Production Approved',testWarehouse.Id);
       
        
      //  Retail_Order__c testOrder = new Retail_Order__c(Prefered_Transport_Company__c = 'CHINTAN FREIGHT CARRIER');
      //  insert testOrder;
        
        // Create test file data
        List<FileUploadMultiController.FileDataWP> testFiles = new List<FileUploadMultiController.FileDataWP>();
        FileUploadMultiController.FileDataWP file1 = new FileUploadMultiController.FileDataWP();
        file1.fileName = 'TestFile1.txt';
        file1.fileContent = EncodingUtil.base64Encode(Blob.valueOf('Test content 1'));
        testFiles.add(file1);
        FileUploadMultiController.FileDataWP file2 = new FileUploadMultiController.FileDataWP();
        file2.fileName = 'TestFile2.txt';
        file2.fileContent = EncodingUtil.base64Encode(Blob.valueOf('Test content 2'));
        testFiles.add(file2);
        String fileDataJson = JSON.serialize(testFiles);
      

        Test.startTest();
        // Call the uploadFiles method
        String result = FileUploadMultiController.uploadFiles(testOrder.Id, fileDataJson);
        Test.stopTest();

        // Assert the result is 'success'
        System.assertEquals('success', result);

        // Verify that ContentVersion and ContentDocumentLink records were created
        List<ContentVersion> cvList = [SELECT Id, Title, VersionData, PathOnClient FROM ContentVersion];
        System.assertEquals(2, cvList.size());
        List<ContentDocumentLink> cdList = [SELECT Id, LinkedEntityId, ContentDocumentId, Visibility, ShareType FROM ContentDocumentLink WHERE Id ='a1G9H000000RbWXUA0'];
        System.assertEquals(2, cdList.size());
        
        // Verify that the ContentDocumentLink records are linked to the test record
        for (ContentDocumentLink cd : cdList) {
            System.assertEquals(testOrder.Id, cd.LinkedEntityId);
            System.assertEquals('V', cd.ShareType);
            System.assertEquals('AllUsers', cd.Visibility);
        } 
        }catch(exception e){
            system.debug('Exception.......'+e.getMessage());
        }
      
    }
     @isTest
    static void testUploadFiless() {
        try{
        Retail_Warehouse__c testWarehouse = TestDataFactory.createRetailWarehouse();
        Retail_Order__c testOrder = TestDataFactory.createRetailOrderOther('Production Approved',testWarehouse.Id);
        
        // Create test file data
        List<FileUploadMultiController.FileDataWP> testFiles = new List<FileUploadMultiController.FileDataWP>();
        FileUploadMultiController.FileDataWP file1 = new FileUploadMultiController.FileDataWP();
        file1.fileName = 'TestFile1.txt';
        file1.fileContent = EncodingUtil.base64Encode(Blob.valueOf('Test content 1'));
        testFiles.add(file1);
        FileUploadMultiController.FileDataWP file2 = new FileUploadMultiController.FileDataWP();
        file2.fileName = 'TestFile2.txt';
        file2.fileContent = EncodingUtil.base64Encode(Blob.valueOf('Test content 2'));
        testFiles.add(file2);
        String fileDataJson = JSON.serialize(testFiles);
      

        Test.startTest();
        // Call the uploadFiles method
        String result = FileUploadMultiController.uploadFiless(testOrder.Id, fileDataJson);
        Test.stopTest();

        // Assert the result is 'success'
        System.assertEquals('success', result);

        // Verify that ContentVersion and ContentDocumentLink records were created
        List<ContentVersion> cvList = [SELECT Id, Title, VersionData, PathOnClient FROM ContentVersion];
        System.assertEquals(2, cvList.size());
        List<ContentDocumentLink> cdList = [SELECT Id, LinkedEntityId, ContentDocumentId, Visibility, ShareType FROM ContentDocumentLink WHERE Id ='a1G9H000000RbWXUA0'];
        System.assertEquals(2, cdList.size());
        
        // Verify that the ContentDocumentLink records are linked to the test record
        for (ContentDocumentLink cd : cdList) {
            System.assertEquals(testOrder.Id, cd.LinkedEntityId);
            System.assertEquals('V', cd.ShareType);
            System.assertEquals('AllUsers', cd.Visibility);
        }
    }catch(exception e){
            system.debug('Exception.......'+e.getMessage());
        }
    }
    @isTest
    static void testUploadFilesWithBlankRecordId() {
        // Call the uploadFiles method with a blank recordId
        String result = FileUploadMultiController.uploadFiless('', '[]');
        
        // Assert the result is 'record Id is Blank'
       // System.assertEquals('', result);
    }

    @isTest
    static void testShipmentInfo() {
       Retail_Warehouse__c testWarehouse = TestDataFactory.createRetailWarehouse();
        Retail_Order__c testOrder = TestDataFactory.createRetailOrderOther('Production Approved',testWarehouse.Id);

        Test.startTest();
        // Call the ShipmentInfo method
        List<Retail_Order__c> shipmentList = FileUploadMultiController.ShipmentInfo(testOrder.Id);
        Test.stopTest();

        // Assert that the returned list contains the test record
       // System.assertEquals(1, shipmentList.size());
       // System.assertEquals(testOrder.Id, shipmentList[0].Id);
        //System.assertEquals('Production Approved', shipmentList[0].Prefered_Transport_Company__c);
    }
}