force-app/main/default/objects/Retail_Inventory__c/Retail_Inventory__c.object-meta.xml
<CustomObject>
    <label>Retail Inventory</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Inventory__c/fields/Bundle_No__c.field-meta.xml
<CustomField>
    <fullName>Bundle_No__c</fullName>
    <label>Bundle No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Instock__c.field-meta.xml
<CustomField>
    <fullName>Instock__c</fullName>
    <label>Instock</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IMAGE(SUBSTITUTE(&apos;https://chart.googleapis.com/chart?chs=120x120&amp;cht=qr&amp;chl=&apos;, &apos;&amp;amp;&apos;, &apos;&amp;&apos;)&amp;LEFT($Api.Partner_Server_URL_580, FIND(&apos;/services&apos;, $Api.Partner_Server_URL_580))&amp;&apos;lightning/n/QR_Code_Product_Details?c__recordId=&apos;&amp;Id,&apos;Scan QR code to open record in mobile.&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Sales_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sales_Qty__c</fullName>
    <label>Sales Qty</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QRCodeController.cls
public with sharing class QRCodeController {
    @AuraEnabled(cacheable=true)
    public static List<Retail_Inventory__c> fetchProductDetails(String ProductId){
        Datetime fiveMinutesAgo = Datetime.now().addMinutes(-5);
        return [SELECT Id, Name, Add_Qty__c, Bundle_No__c, Instock__c, Product_Name__c, QR_Code__c, Sales_Qty__c FROM Retail_Inventory__c where Id=:ProductId AND LastModifiedDate <= :fiveMinutesAgo LIMIT 1];
    }
    @AuraEnabled
    public static String updateProductDetails(Integer Quantity, String ProductId){
        try{
            List<Retail_Inventory__c> RetailInv = [SELECT Id, Name, Add_Qty__c, Bundle_No__c, Instock__c, Product_Name__c, QR_Code__c, Sales_Qty__c FROM Retail_Inventory__c where Id=:ProductId LIMIT 1];
            RetailInv[0].Sales_Qty__c = RetailInv[0].Sales_Qty__c + Quantity;
            //RetailInv[0].Instock__c = RetailInv[0].Add_Qty__c - RetailInv[0].Sales_Qty__c;
            if(Schema.SobjectType.Retail_Inventory__c.isCreateable()){
                update RetailInv;
                return 'Retail Inventory Details Successfully Saved';
            }
            else {
                return 'You don\'t have sufficient permissions on the Retail Inventory Object to perform Edit operation. Please contact your System Administrator';
            }
        }
        catch(Exception e){
			ApexPages.addMessages(e);
            System.debug('Exception: '+e+', Stack Trace:'+e.getStackTraceString());
            return null;
        }
        
    }
}