force-app/main/default/objects/Retail_Inventory__c/Retail_Inventory__c.object-meta.xml
<CustomObject>
    <label>Retail Inventory</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Inventory__c/fields/Bundle_No__c.field-meta.xml
<CustomField>
    <fullName>Bundle_No__c</fullName>
    <label>Bundle No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Instock__c.field-meta.xml
<CustomField>
    <fullName>Instock__c</fullName>
    <label>Instock</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IMAGE(SUBSTITUTE(&apos;https://chart.googleapis.com/chart?chs=120x120&amp;cht=qr&amp;chl=&apos;, &apos;&amp;amp;&apos;, &apos;&amp;&apos;)&amp;LEFT($Api.Partner_Server_URL_580, FIND(&apos;/services&apos;, $Api.Partner_Server_URL_580))&amp;&apos;lightning/n/QR_Code_Product_Details?c__recordId=&apos;&amp;Id,&apos;Scan QR code to open record in mobile.&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Sales_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sales_Qty__c</fullName>
    <label>Sales Qty</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/Retail_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Product__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <formula>IMAGE(&apos;https://chart.googleapis.com/chart?chs=200x200&amp;cht=qr&amp;chl=https://avana--migration.sandbox.lightning.force.com/lightning/n/QR_Code_Product_Details?c__recordId=&apos;&amp;Id,&apos;Scan QR code to open record in mobile.&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Products</relationshipLabel>
    <relationshipName>Retail_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product_Group__c/Retail_Product_Group__c.object-meta.xml
<CustomObject>
    <label>Retail Product Group</label>
    <nameField>
        <label>Product Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Warehouse__c/Retail_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Retail Warehouse</label>
    <nameField>
        <label>Retail Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QRCodeController_TestClass.cls
@isTest
public class QRCodeController_TestClass 
{
    @isTest
    static void testFetchProductDetails() {
        // Create test data
        try{
             Retail_Product_Group__c retailProdGrup = TestDataFactory.createRetailProductGroup();
        Retail_Product__c retailProduct = TestDataFactory.createRetailProduct(retailProdGrup.id);
        Retail_Warehouse__c retailWarhouse = TestDataFactory.createRetailWarehouse();
        Retail_Inventory__c retailInventory = TestDataFactory.createRetailInventory(retailProdGrup.id,retailWarhouse.id,retailProduct.id);
         
        List<Retail_Inventory__c> result = QRCodeController.fetchProductDetails(retailInventory.Id);
        
        System.assertEquals(1, result.size());
        System.assertEquals(retailInventory.Id, result[0].Id);
        System.assertEquals(retailInventory.Name, result[0].Name);
        System.assertEquals(retailInventory.Add_Qty__c, result[0].Add_Qty__c);
        System.assertEquals(retailInventory.Bundle_No__c, result[0].Bundle_No__c);
        System.assertEquals(retailInventory.Instock__c, result[0].Instock__c);
        System.assertEquals(retailInventory.Product_Name__c, result[0].Product_Name__c);
        System.assertEquals(retailInventory.QR_Code__c, result[0].QR_Code__c);
        System.assertEquals(retailInventory.Sales_Qty__c, result[0].Sales_Qty__c);
        }catch(exception e){
          system.debug('Exception.......'+e.getMessage());
        }
       
    }

    @isTest
    static void testUpdateProductDetails() {
       
        try{
        Retail_Product_Group__c retailProdGrup = TestDataFactory.createRetailProductGroup();
        Retail_Product__c retailProduct = TestDataFactory.createRetailProduct(retailProdGrup.id);
        Retail_Warehouse__c retailWarhouse = TestDataFactory.createRetailWarehouse();
        Retail_Inventory__c retailInventory = TestDataFactory.createRetailInventory(retailProdGrup.id,retailWarhouse.id,retailProduct.id);
      
        String result = QRCodeController.updateProductDetails(10, retailInventory.Id);

        // Retrieve the updated record for verification
        Retail_Inventory__c updatedRetailInv = [SELECT Id, Name, Add_Qty__c, Instock__c, Product_Name__c, QR_Code__c, Sales_Qty__c FROM Retail_Inventory__c WHERE Id = :retailInventory.Id LIMIT 1];

        // Verify the results
        System.assertEquals('Retail Inventory Details Successfully Saved', result);
        System.assertEquals(retailInventory.Sales_Qty__c + 10, updatedRetailInv.Sales_Qty__c);
        System.assertEquals(retailInventory.Add_Qty__c - (retailInventory.Sales_Qty__c + 10), updatedRetailInv.Instock__c);
        }catch(exception e){
          system.debug('Exception.......'+e.getMessage());
        }
    }
}