force-app/main/default/objects/Retail_Inventory__c/Retail_Inventory__c.object-meta.xml
<CustomObject>
    <label>Retail Inventory</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Inventory__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <label>Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instock</fullName>
            </value>
            <value>
                <fullName>Low Stock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Gross_Weight__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight__c</fullName>
    <label>Gross Weight</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Instock__c.field-meta.xml
<CustomField>
    <fullName>Instock__c</fullName>
    <label>Instock</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Net_Weight__c</fullName>
    <label>Net Weight</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Sales_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sales_Qty__c</fullName>
    <label>Sales Qty</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Tare_Weight__c.field-meta.xml
<CustomField>
    <fullName>Tare_Weight__c</fullName>
    <label>Tare Weight</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse Code</label>
    <referenceTo>Retail_Warehouse__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/Retail_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Product__c/fields/Total_In_Stock__c.field-meta.xml
<CustomField>
    <fullName>Total_In_Stock__c</fullName>
    <label>Total In Stock</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Warehouse__c/Retail_Warehouse__c.object-meta.xml
<CustomObject>
    <label>Retail Warehouse</label>
    <nameField>
        <label>Retail Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Warehouse__c/fields/GST_Number__c.field-meta.xml
<CustomField>
    <fullName>GST_Number__c</fullName>
    <label>GST Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Warehouse__c/fields/POC_Email__c.field-meta.xml
<CustomField>
    <fullName>POC_Email__c</fullName>
    <label>POC Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Retail_Warehouse__c/fields/POC_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>POC_Phone_Number__c</fullName>
    <label>POC Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Retail_Warehouse__c/fields/Point_of_Contact_POC_Name__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact_POC_Name__c</fullName>
    <label>Point of Contact (POC) Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Warehouse__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <label>Warehouse Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Warehouse__c/fields/Warehouse_Type__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Type__c</fullName>
    <label>Warehouse Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avana Warehouse</fullName>
            </value>
            <value>
                <fullName>Distributor Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InventoryTriggerHelperController.cls
public class InventoryTriggerHelperController {
    public static Boolean isInventoryInstockUpdate = true;
    public static void handleSendEmailAfterUpdate(List<Retail_Inventory__c> newInventories) {
        System.debug('Method Entered');
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'surender@dhruvsoft.com'];
        List<Retail_Inventory__c> inventoryToUpdate = new List<Retail_Inventory__c>();
        
        for (Retail_Inventory__c newInventory : newInventories) {
            
            if (newInventory.Availability__c == 'Low Stock') {
                inventoryToUpdate.add(newInventory);
                
                System.debug('+newInventory.Owner.name'+newInventory.OwnerId);
                User SalesOwner=[Select Id,Name,Email from user where id =:newInventory.OwnerId limit 1];
                Retail_Warehouse__c WarehouseDeatils=[SELECT Id, Name, Warehouse_Type__c, GST_Number__c, Point_of_Contact_POC_Name__c, POC_Phone_Number__c, POC_Email__c FROM Retail_Warehouse__c where Id=:newInventory.Warehouse_Code__c limit 1];
                Retail_Product__c productDetails=[SELECT Id, Name,Product_Name__c from Retail_Product__c where Id=:newInventory.Product_Name__c limit 1];
                List<String> toaddresses=New List<String>();
                System.debug('UserList toaddresses'+toaddresses);
                Messaging.SingleEmailMessage mymail = new Messaging.SingleEmailMessage();
                toaddresses.add('shashirekha@dhruvsoft.com'); 
                toaddresses.add('thanmayee@dhruvsoft.com'); 
                // toaddresses.add(SalesOwner.Email); 
                mymail.setToAddresses(toaddresses);
                String subject = newInventory.Name+' Order Received- Low Stock in '+WarehouseDeatils.Name+' of '+productDetails.Product_Name__c; 
                mymail.setSubject(subject);
                
                String EmailBody = '<html><body>';
                EmailBody += 'Dear Warehouse Stock Management Team,<br/>';
                EmailBody += '<p><p/>';
                EmailBody += 'The stock in '+WarehouseDeatils.Name+' for the product '+productDetails.Product_Name__c+' is running low. ';
                EmailBody += 'Please place an order if you need to get it from another Avana warehouse. <br/>';
                EmailBody += 'Else add product using this link: ';
                EmailBody +='<a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+newInventory.Id+'" target="_blank">Add Inventory</a>. ';
                EmailBody +='<p><p/>';
                EmailBody +='<b>Warm Regards,</b><br/>';
                EmailBody +='<b>Avana Operations Team</b><br/>';
                EmailBody += '</body></html>';
                mymail.setHtmlBody(EmailBody);
                
                mymail.setOrgWideEmailAddressId(owea.get(0).Id);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mymail });
                
            }
        }
        
    }
    
  /*   public static void handleInventoryUpdate(List<Retail_Inventory__c> newInventories, Map<Id, Retail_Inventory__c> oldInventories) {
        List<Retail_Inventory__c> inventoriesToUpdate = new List<Retail_Inventory__c>();

        // Handle before insert and before update scenarios
        if (Trigger.isInsert || Trigger.isUpdate) {
            for (Retail_Inventory__c inventory : newInventories) {
                Retail_Inventory__c newInstance = new Retail_Inventory__c();
                newInstance.Id = inventory.Id;
                Decimal addQty = inventory.Add_Qty__c != null ? inventory.Add_Qty__c : 0;
                Decimal salesQty = inventory.Sales_Qty__c != null ? inventory.Sales_Qty__c : 0;
                newInstance.Instock__c = addQty - salesQty;
                inventoriesToUpdate.add(newInstance);
            }
        }

        // Handle before delete scenario
        if (Trigger.isDelete) {
            for (Retail_Inventory__c inventory : newInventories) {
                // In before delete trigger, oldInventories contains the records before they are deleted.
                Decimal addQty = oldInventories.get(inventory.Id).Add_Qty__c != null ? oldInventories.get(inventory.Id).Add_Qty__c : 0;
                Decimal salesQty = oldInventories.get(inventory.Id).Sales_Qty__c != null ? oldInventories.get(inventory.Id).Sales_Qty__c : 0;
                inventory.Instock__c = addQty - salesQty;
                inventoriesToUpdate.add(inventory);
            }
        }

        // Update the records with the calculated values
        if (!inventoriesToUpdate.isEmpty()) {
            update inventoriesToUpdate;
        }
    }*/
    
    
    public static void updateInstockAtInventory(List<Retail_Inventory__c> inventoryList){
        List<Retail_Inventory__c> newInstanceList = new  List<Retail_Inventory__c>();
       	isInventoryInstockUpdate = false;
        //if(isInvUpdate){
        for(Retail_Inventory__c invData : inventoryList){
            Retail_Inventory__c newInstance = new Retail_Inventory__c();
            newInstance.Id = invData.Id;
            if(invData.Add_Qty__c != null && invData.Sales_Qty__c != null){
            newInstance.Instock__c = invData.Add_Qty__c - invData.Sales_Qty__c;
            }else{
              newInstance.Instock__c = 0;  
            }
            
            if(invData.Net_Weight__c != null && invData.Tare_Weight__c != null){
            newInstance.Gross_Weight__c = invData.Net_Weight__c + invData.Tare_Weight__c;
            }else{
                newInstance.Gross_Weight__c = 0;
            }
            newInstanceList.add(newInstance);
        }
        update newInstanceList;
       // }
    }
    
    
    
    
    
    
    
    public static void updateParentTotalInStock(List<Retail_Inventory__c> inventoryRecords) {
        Set<Id> productId = new Set<Id>();
        List<Retail_Product__c> retPro = new List<Retail_Product__c>();
        //List<Retail_Inventory__c> retInventory = new List<Retail_Inventory__c>();
        //Map<Id, Decimal> sumValue = new Map<Id, Decimal>();
        //Decimal inStock = 0;
        
        for(Retail_Inventory__c reInv : inventoryRecords){
            productId.add(reInv.Product_Name__c);
        }
        
        List<AggregateResult> agglist = [select Product_Name__c pn, sum(Instock__c) instock from Retail_Inventory__c where Product_Name__c IN: productId group by Product_Name__c];
      /*  List<Retail_Inventory__c> retailInventoryList = [SELECT id,Instock__c FROM Retail_Inventory__c];
        for(Retail_Inventory__c retInv : retailInventoryList){
            retInv.Instock__c = retInv.Add_Qty__c-retInv.Sales_Qty__c;
            retailInventoryList.add(retInv);
        }
        Update retailInventoryList;*/

        
        for(AggregateResult agg : agglist){
            Retail_Product__c rp = new Retail_Product__c();
            rp.Id = (Id) agg.get('pn');
            rp.Total_In_Stock__c = (Decimal) agg.get('instock');
            retPro.add(rp);
        }
        Update retPro;
        
    }
}