force-app/main/default/objects/Retail_Inventory__c/Retail_Inventory__c.object-meta.xml
<CustomObject>
    <label>Retail Inventory</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Inventory__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <label>Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instock</fullName>
            </value>
            <value>
                <fullName>Low Stock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse Code</label>
    <referenceTo>Retail_Warehouse__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/Retail_Order__c.object-meta.xml
<CustomObject>
    <label>Retail Order</label>
    <nameField>
        <displayFormat>RO-{0000}</displayFormat>
        <label>Retail Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order__c/fields/Advance__c.field-meta.xml
<CustomField>
    <fullName>Advance__c</fullName>
    <label>Advance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Closest_Tranport_Branch__c.field-meta.xml
<CustomField>
    <fullName>Closest_Tranport_Branch__c</fullName>
    <label>Closest Tranport Branch</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Freight_Charge_Bearer_values__c.field-meta.xml
<CustomField>
    <fullName>Freight_Charge_Bearer_values__c</fullName>
    <label>Freight Charge Bearer values</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avana</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Net_Total__c.field-meta.xml
<CustomField>
    <fullName>Net_Total__c</fullName>
    <label>Net Total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Order_Discount__c.field-meta.xml
<CustomField>
    <fullName>Order_Discount__c</fullName>
    <label>% Order Discount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail Products</fullName>
                <default>true</default>
                <label>Retail Products</label>
            </value>
            <value>
                <fullName>Internal Stock Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Prefered_Transport_Company__c.field-meta.xml
<CustomField>
    <fullName>Prefered_Transport_Company__c</fullName>
    <label>Prefered Transport Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMRUT LOGISTICS (ARCO)</fullName>
            </value>
            <value>
                <fullName>Avinash Cargo Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Batcotranslogistics Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>CHINTAN FREIGHT CARRIER</fullName>
            </value>
            <value>
                <fullName>GIRNAR CARGO ESCORT</fullName>
            </value>
            <value>
                <fullName>Lavakesh Roadlines</fullName>
            </value>
            <value>
                <fullName>LOCAL TRANSPORT</fullName>
            </value>
            <value>
                <fullName>OWN VEHICLE</fullName>
            </value>
            <value>
                <fullName>RISHABH ROADLINES</fullName>
            </value>
            <value>
                <fullName>RITWIZ ROADLINES</fullName>
            </value>
            <value>
                <fullName>Balaji Transport Company</fullName>
            </value>
            <value>
                <fullName>SECURE TRANS LOGISTICS</fullName>
            </value>
            <value>
                <fullName>Shree Nashik Goods TransportCo.</fullName>
                <label>Shree Nashik Goods Transport Co.</label>
            </value>
            <value>
                <fullName>Shree Shyam Logistics</fullName>
            </value>
            <value>
                <fullName>VISHWA LOGISTICS</fullName>
            </value>
            <value>
                <fullName>VRL Logistics Limited</fullName>
            </value>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Shree Krishna Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exec Discount Approval</fullName>
                <label>Awaiting Discount Approval</label>
            </value>
            <value>
                <fullName>Awaiting Exec Approval</fullName>
                <label>Awaiting Credit Approval</label>
            </value>
            <value>
                <fullName>Awaiting Accounts</fullName>
                <label>Awaiting Accounts Approval</label>
            </value>
            <value>
                <fullName>Payment Approved</fullName>
            </value>
            <value>
                <fullName>Upload Packing List</fullName>
            </value>
            <value>
                <fullName>Packing List in Process</fullName>
            </value>
            <value>
                <fullName>Production Approved</fullName>
            </value>
            <value>
                <fullName>Ready For Dispatch</fullName>
                <label>Commercial : Ready For Dispatch</label>
            </value>
            <value>
                <fullName>Dispatched Awaiting Final Payment</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Awaiting Manager Approval</fullName>
                <isActive>false</isActive>
                <label>Awaiting Manager Approval</label>
            </value>
            <value>
                <fullName>Commercial : Instock - Prepare Invoice</fullName>
                <isActive>false</isActive>
                <label>Commercial : Instock - Prepare Invoice</label>
            </value>
            <value>
                <fullName>Confirm Stock Receipt</fullName>
                <isActive>false</isActive>
                <label>Confirm Stock Receipt</label>
            </value>
            <value>
                <fullName>Exec Credit Approval</fullName>
                <isActive>false</isActive>
                <label>Exec Credit Approval</label>
            </value>
            <value>
                <fullName>Exec Return Approval</fullName>
                <isActive>false</isActive>
                <label>Exec Return Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory2.cls
public class TestDataFactory2 
{
   public static Retail_Order__c createRetailOrderOther(String Status,String warehouse){
        Retail_Order__c retailOrder= new Retail_Order__c();
        retailOrder.Order_Date__c= system.today()+1;
        retailOrder.Order_Type__c='Retail Products 1';
        retailOrder.Freight_Charge_Bearer_values__c='Avana';
        retailOrder.Prefered_Transport_Company__c='AMRUT LOGISTICS (ARCO)1';
        retailOrder.Closest_Tranport_Branch__c='hyd';
        retailOrder.Credit__c=1000;
        retailOrder.Sub_Total__c=1000;
        retailOrder.Net_Total__c=1000;
        retailOrder.Advance__c=0;
        retailOrder.Status__c='production Approved';
        retailOrder.OwnerId = UserInfo.getUserId();
        retailOrder.Order_Discount__c=0.0;
       
        return retailOrder;
        
    }
     public static Retail_Inventory__c createRetailInventory(String prdGrp,String warehouse,String product ){
        Retail_Inventory__c retailInventory = new Retail_Inventory__c();
        retailInventory.Product_Group__c=prdGrp; 
        retailInventory.Warehouse_Code__c=warehouse;
        retailInventory.Product_Name__c = product; 
        retailInventory.Add_Qty__c = 20;
        retailInventory.Availability__c='Low Stock';
        retailInventory.OwnerId = UserInfo.getUserId();
        insert retailInventory;
        return retailInventory;
        
    }
    
    
    

}