force-app/main/default/objects/Retail_Inventory__c/Retail_Inventory__c.object-meta.xml
<CustomObject>
    <label>Retail Inventory</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Inventory__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <label>Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instock</fullName>
            </value>
            <value>
                <fullName>Low Stock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Distributor_MOQ__c.field-meta.xml
<CustomField>
    <fullName>Distributor_MOQ__c</fullName>
    <label>Distributor MOQ</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Distributor_Price__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Price__c</fullName>
    <label>Distributor Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Image_Testing__c.field-meta.xml
<CustomField>
    <fullName>Image_Testing__c</fullName>
    <label>Image Testing</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Instock__c.field-meta.xml
<CustomField>
    <fullName>Instock__c</fullName>
    <label>Instock</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Notification_Threshold_Value__c.field-meta.xml
<CustomField>
    <fullName>Notification_Threshold_Value__c</fullName>
    <label>Notification Threshold Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Pending_QC_Stock__c.field-meta.xml
<CustomField>
    <fullName>Pending_QC_Stock__c</fullName>
    <label>Pending QC Stock</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/QC_Failed_Stock__c.field-meta.xml
<CustomField>
    <fullName>QC_Failed_Stock__c</fullName>
    <label>QC Failed Stock</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/QC_Instock__c.field-meta.xml
<CustomField>
    <fullName>QC_Instock__c</fullName>
    <label>QC Instock</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Retailer_MOQ__c.field-meta.xml
<CustomField>
    <fullName>Retailer_MOQ__c</fullName>
    <label>Retailer MOQ</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Retailer_Price__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Price__c</fullName>
    <label>Retailer Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Saleable_Stock__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Stock__c</fullName>
    <label>Saleable Stock</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Sales_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sales_Qty__c</fullName>
    <label>Sales Qty</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse Code</label>
    <referenceTo>Retail_Warehouse__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/Retail_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Product__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Products</relationshipLabel>
    <relationshipName>Retail_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product_Group__c/Retail_Product_Group__c.object-meta.xml
<CustomObject>
    <label>Retail Product Group</label>
    <nameField>
        <label>Product Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewOverrideProductController.cls
public class NewOverrideProductController {
        
        @AuraEnabled
        public static String insertProductWithInventory(List<Retail_Inventory__c> inventoryList, Retail_Product__c product) {
            try {
                List<Retail_Inventory__c> lstiv = new List<Retail_Inventory__c>();
                System.debug('inventoryList'+inventoryList);
                System.debug('product'+product);
                if (Schema.sObjectType.Retail_Product__c.isCreateable()) {
                    insert product;
                }
                
                String productId = product.Id;
                String productGroup = product.Retail_Product_Group__c;
                try{
                    for (Retail_Inventory__c inv : inventoryList) {
                        Retail_Inventory__c inventory = new Retail_Inventory__c();
                        //System.debug('inv===='+inv.Name);
                        inventory.Product_Name__c = product.Id;
                        if (inv.Date__c == null || inv.Date__c == Date.newInstance(0, 0, 0)) {
                            inventory.Date__c = System.Today();
                        } else {
                            inventory.Date__c = inv.Date__c;
                        }
                        inventory.Warehouse_Code__c = inv.Warehouse_Code__c;
                        inventory.Retailer_Price__c = inv.Retailer_Price__c;
                        inventory.Distributor_Price__c = inv.Distributor_Price__c;
                        inventory.Retailer_MOQ__c = inv.Retailer_MOQ__c;
                        inventory.Distributor_MOQ__c = inv.Distributor_MOQ__c;
                        inventory.Notification_Threshold_Value__c = inv.Notification_Threshold_Value__c;
                        inventory.Add_Qty__c = inv.Add_Qty__c;
                        inventory.Sales_Qty__c = inv.Sales_Qty__c;
                       // if(inv.Instock__c != null){
                        inventory.Instock__c = inv.Instock__c;
                       // }
                        inventory.Pending_QC_Stock__c = inv.Pending_QC_Stock__c;
                        inventory.Saleable_Stock__c = inv.Saleable_Stock__c;
                        inventory.QC_Instock__c = inv.QC_Instock__c;
                        inventory.Availability__c = inv.Availability__c;
                        inventory.Product_Group__c = product.Retail_Product_Group__c;
                        
                        
                        lstiv.add(inventory);
                    }
                    
                    if (!lstiv.isEmpty() && Schema.sObjectType.Retail_Inventory__c.isCreateable()) {
                        insert lstiv;
                    }  
                    System.debug('productId11'+productId);
                    System.debug('Hiii prodduct11');
                    
                    
                    
                }
                catch (Exception e) {
                    throw new AuraHandledException(e.getMessage());
                }
                System.debug('productId'+productId);
                System.debug('Hiii prodduct');
                
                return productId;
            } 
            catch (Exception e) {
                throw new AuraHandledException(e.getMessage());
            }
        }
        
        @AuraEnabled(cacheable=true)
        public static List<Retail_Inventory__c> findInventoryList(String recordId) {
            List<Retail_Inventory__c> inventoryListData = [SELECT Id,Date__c,Warehouse_Code__c,Image_Testing__c,Availability__c,QC_Instock__c,QC_Failed_Stock__c,Saleable_Stock__c,Pending_QC_Stock__c,Instock__c,Sales_Qty__c,Add_Qty__c,Notification_Threshold_Value__c,Retailer_Price__c,Distributor_Price__c,Retailer_MOQ__c,Distributor_MOQ__c FROM Retail_Inventory__c WHERE Product_Name__c =: recordId];
            System.debug('This is inventoryListData ===>'+inventoryListData);
            System.debug(inventoryListData.size());
            return inventoryListData;
            
            
        }
        
        
        @AuraEnabled
        public static void upsertProduct(List<Retail_Inventory__c> inventoryList , Retail_Product__c product,List<Retail_Inventory__c> removeLineItemIds) {
            try {
                System.debug('product' + product);
                System.debug('product Id' + product.Id);
                System.debug('inventoryList1========' + inventoryList);
                if(product.Id!=null){
                    System.debug('product Id' + product.Id);
                    update product;
                }
                System.debug('inventoryList2======' + inventoryList.size());
                if(inventoryList.size()>0){
                    System.debug('inventoryList3======' + inventoryList.size());
                    if (Schema.sObjectType.Retail_Inventory__c.isUpdateable() || Schema.sObjectType.Retail_Inventory__c.isCreateable()) {
                        System.debug('inventoryList3======' + inventoryList.size());
                        //System.debug('inventoryList Id==123=='+inventoryList[1]);
                        upsert inventoryList;
                    }
                }
                if (removeLineItemIds.size() > 0) {
                    System.debug('removeLineItemIds======' + removeLineItemIds.size());
                    if (Schema.sObjectType.Retail_Inventory__c.isDeletable()) {
                        delete removeLineItemIds;
                    }
                }
                
            } catch (Exception e) {
                // throw new AuraHandledException(e.getMessage());
                System.debug('Error ===>'+e.getMessage()+' Linenumber===>104'+e.getlinenumber());
            }
            
        }
        
        
        
        
        
        
    }