force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/fields/Is_Converted__c.field-meta.xml
<CustomField>
    <fullName>Is_Converted__c</fullName>
    <label>Is Converted?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Last_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Order_Date__c</fullName>
    <description>If the Customer Id field in Lead is not null then the Last order date will be the customer last order date</description>
    <formula>IF(NOT(ISBLANK(Link_Customer_Id__c)),Link_Customer_Id__r.Last_Order_Date__c , NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner__c</fullName>
    <formula>CreatedBy.Username</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kisan Exhibition &apos;22</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Pending_Data__c.field-meta.xml
<CustomField>
    <fullName>Pending_Data__c</fullName>
    <label>Pending Data</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seller Id</fullName>
            </value>
            <value>
                <fullName>Customer Id</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReusableMultiSelectLookupController.cls
public with sharing class ReusableMultiSelectLookupController {
   /* @AuraEnabled
    public static List<ResultWrapper> fetchRecords(SearchWrapper inputWrapper) {
        try {
            if(inputWrapper != null){
                string filterCriteria='';
                List<String> searchKeywordList = inputWrapper.searchString.split(' ');
                for(String kw : searchKeywordList){
                    filterCriteria += inputWrapper.fieldApiName + ' LIKE \'%'+kw+'%\' OR ';
                }
                if(string.isNotBlank(inputWrapper.otherFieldApiName) && inputWrapper.searchByOtherField){
                    for(String kw : searchKeywordList){
                    filterCriteria+= inputWrapper.otherFieldApiName + ' LIKE \'%'+kw+'%\' OR ';
                    }
                }
                filterCriteria = filterCriteria.removeEnd(' OR ');
                String fieldsToQuery = 'SELECT Id, ';
                if(string.isNotBlank(inputWrapper.fieldApiName)){
                    fieldsToQuery = fieldsToQuery + inputWrapper.fieldApiName;
                }
                if(string.isNotBlank(inputWrapper.otherFieldApiName)){
                    fieldsToQuery = fieldsToQuery + ', ' + inputWrapper.otherFieldApiName;
                }
                String query = fieldsToQuery + ' FROM '+ inputWrapper.objectApiName;
                if(String.isNotBlank(inputWrapper.parentFieldApiName) && String.isNotBlank(inputWrapper.parentRecordId)){
                    query += ' WHERE '+ inputWrapper.parentFieldApiName+ ' = \''+ inputWrapper.parentRecordId + '\'';
                    query += ' AND (' + filterCriteria+' ) Order By '+ inputWrapper.fieldApiName+' Limit 10';
                } 
                else {
                    query += ' WHERE '+ filterCriteria+' Order By '+ inputWrapper.fieldApiName+' Limit 10';
                }
                System.debug('query==>'+query);
                List<ResultWrapper> returnWrapperList = new List<ResultWrapper>();
                for(SObject s : Database.query(query)) {
                    ResultWrapper wrap = new ResultWrapper();
                    wrap.mainField = (String)s.get(inputWrapper.fieldApiName);
                    //wrap.subField = (String)s.get(inputWrapper.otherFieldApiName);
                    wrap.id = (String)s.get('id');
                    returnWrapperList.add(wrap);
                }
                System.debug('returnWrapperList==>'+returnWrapperList);
                return returnWrapperList;
            }
            return null;
        } catch (Exception err) {
            System.debug(err.getStackTraceString());
            throw new AuraHandledException(err.getMessage());
        }
    }


    

    @AuraEnabled
    public static void saveDataApex(Map<String, Object> recordData,Map<String, Object> lookupfields) {
        system.debug('lookupfields==entered');
        system.debug('lookupfields=='+lookupfields);
        // Extract the field values from the recordData map
        //String field1Value = (String)recordData.get('Lead_Owner__c');
        String field2Value = (String)recordData.get('Lead_Source__c');
       // String field3Value = (String)recordData.get('Name');
        Date field4Value = (Date)recordData.get('Date__c');
        String field5Value = (String)recordData.get('Lead_Type__c');
        String field6Value = (String)recordData.get('Lead_Name__c');
        String field7Value = (String)recordData.get('Phone__c');
        String field8Value = (String)recordData.get('Village__c');
        String field9Value = (String)recordData.get('Is_Converted__c');
        Date field10Value = (Date)recordData.get('Last_Order_Date__c');
        String field11Value = (String)recordData.get('Sale_Type__c');
        String field12Value = (String)recordData.get('Pending_Data__c');
       
      
        // Retrieve more field values as needed

        // Perform the necessary operations to store the data in the database
        // You can create new records, update existing records, etc.
        // Example: Insert a new record
        Retail_Lead__c obj = new Retail_Lead__c();
       // obj.Lead_Owner__c = field1Value;
        obj.Lead_Source__c = field2Value;
       // obj.Name = field3Value;
        obj.Date__c = field4Value;
        obj.Lead_Type__c = field5Value;
        obj.Lead_Name__c = field6Value;
        obj.Phone__c = field7Value;
        obj.Village__c = field8Value;
        obj.Is_Converted__c = field9Value;
        obj.Last_Order_Date__c = field10Value;
        obj.Sale_Type__c = field11Value;
        obj.Pending_Data__c = field12Value;
      

        // Set more field values as needed
        insert obj;
    }

    public class ResultWrapper{
        @AuraEnabled public String mainField{get;set;}
        @AuraEnabled public String subField{get;set;}
        @AuraEnabled public String id{get;set;}
    }

    public class SearchWrapper {
        @AuraEnabled public String objectApiName{get;set;}
        @AuraEnabled public String fieldApiName{get;set;}
        @AuraEnabled public String otherFieldApiName{get;set;}
        @AuraEnabled public String searchString{get;set;}
        @AuraEnabled public String parentRecordId{get;set;}
        @AuraEnabled public String parentFieldApiName{get;set;}
        @AuraEnabled public Boolean searchByOtherField{get;set;}
    }*/
}