force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Visit__c.field-meta.xml
<CustomField>
    <fullName>Lead_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Visit</label>
    <referenceTo>Retail_Lead_Visit__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Link_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Link_Customer_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Connect the customer and lead data for this client</inlineHelpText>
    <label>Link Customer Id</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Leads (Link Customer Id)</relationshipLabel>
    <relationshipName>Retail_Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadControllerForEdit.cls
public class LeadControllerForEdit {
    @AuraEnabled(cacheable=true)
    public static Retail_Lead__c leadRecords(String leadRecordId){
        System.debug('leadRecId-->'+leadRecordId);
        Retail_Lead__c Query = [SELECT Id,Lead_Name__c,Lead_Type__c,Lead_Visit__c,Link_Customer_Id__c FROM Retail_Lead__c WHERE Id=:leadRecordId LIMIT 1];
        System.debug('Query-->'+Query);
        return Query;
    }

}