force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/Retail_Lead_Visit__c.object-meta.xml
<CustomObject>
    <label>Retail Lead Visit</label>
    <nameField>
        <displayFormat>RLV-{0000}</displayFormat>
        <label>Visit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Lead Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Retail_Lead__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadvisitTriggerHandler.cls
public class LeadvisitTriggerHandler {
    public static void handleAfterInsert(List<Retail_Lead_Visit__c> newLeadvisits) {
        List<Retail_Lead__c> leadsToUpdate = new List<Retail_Lead__c>();
        for(Retail_Lead_Visit__c retails : newLeadvisits){
            if(retails.Lead_Name__c != null){
                Retail_Lead__c parentLead = new Retail_Lead__c();
                parentLead.Id = retails.Lead_Name__c;
                parentLead.Sale_Type__c = retails.Sale_Type__c;
                leadsToUpdate.add(parentLead);
            }
        }
        Map<Id,Retail_Lead__c> leadsToUpdateMap = new Map<Id,Retail_Lead__c>(leadsToUpdate);
        // Perform the bulk update of Lead records
        if (!leadsToUpdateMap.isEmpty()) {
            update leadsToUpdateMap.values(); 
        }
    }
}