force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/fields/Link_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Link_Customer_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Connect the customer and lead data for this client</inlineHelpText>
    <label>Link Customer Id</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Leads (Link Customer Id)</relationshipLabel>
    <relationshipName>Retail_Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Pending_Data__c.field-meta.xml
<CustomField>
    <fullName>Pending_Data__c</fullName>
    <label>Pending Data</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seller Id</fullName>
            </value>
            <value>
                <fullName>Customer Id</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Seller_Name__c.field-meta.xml
<CustomField>
    <fullName>Seller_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Avana Retail customer/customers from which this lead is purchasing Avana Retail  products</inlineHelpText>
    <label>Seller Name</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RetailLeadTriggerHelper.cls
public class RetailLeadTriggerHelper {
    public static void updateSaleType(List<Retail_Lead__c> newRetailLeadsList, Map<Id,Retail_Lead__c> oldRetailLeadsMap){
        System.debug('Test');
        for(Retail_Lead__c retails : newRetailLeadsList){
            if(oldRetailLeadsMap.containsKey(retails.Id) && retails.Sale_Type__c != oldRetailLeadsMap.get(retails.Id).Sale_Type__c){
                if((retails.Sale_Type__c == 'Indirect' && oldRetailLeadsMap.get(retails.Id).Sale_Type__c == 'Direct') || (retails.Sale_Type__c == 'Direct' && oldRetailLeadsMap.get(retails.Id).Sale_Type__c == 'Indirect')){
                    retails.Sale_Type__c = 'Both';
                }
                else if(oldRetailLeadsMap.get(retails.Id).Sale_Type__c == 'Both'){
                    retails.Sale_Type__c = 'Both';
                }
            }
        }
    }
    
    public static void updatePendingData(List<Retail_Lead__c> newRetailLeadsList2){
        for(Retail_Lead__c retails2 : newRetailLeadsList2){
            //1
                if(retails2.Sale_Type__c == 'Both'){
                    if(retails2.Seller_Name__c == null && retails2.Link_Customer_Id__c == null){
                        retails2.Pending_Data__c = 'Both';
                    }
                    else if(retails2.Seller_Name__c == null && retails2.Link_Customer_Id__c != null){
                        retails2.Pending_Data__c = 'Seller Id';
                    }
                    else if(retails2.Seller_Name__c != null && retails2.Link_Customer_Id__c == null){
                        retails2.Pending_Data__c = 'Customer Id';
                    }
                }
            
            
            //2
            
            if(retails2.Sale_Type__c == 'Direct' && retails2.Link_Customer_Id__c == null){
                retails2.Pending_Data__c = 'Customer Id';
            }
            
            //3
            
            if(retails2.Sale_Type__c == 'Indirect' && retails2.Seller_Name__c == null){
                retails2.Pending_Data__c = 'Seller Id';
            }
            

        }
                
    }
    
    //To check the Phone number uniqueness
  /*  public static void handleBeforeInsertUpdate(List<Retail_Lead__c> newLeads) {
        
        for (Retail_Lead__c lead : newLeads) {
            if (lead.Phone__c == null || lead.Phone__c.length() != 10) {
                lead.Phone__c.addError('Phone number must be 10 digitsss.');
            }
        }
        
        
        
        
        
        
        Set<String> phoneNumbers = new Set<String>();
        
        for (Retail_Lead__c lead : newLeads) {
            if (!String.isBlank(lead.Phone__c)) {
                phoneNumbers.add(lead.Phone__c);
            }
        }
        
        Map<String,Retail_Lead__c> existingLeads = new Map<String,Retail_Lead__c>([
            SELECT Id,Phone__c
            FROM Retail_Lead__c
            WHERE Phone__c IN: phoneNumbers
            
            
        ]);
        
        for (Retail_Lead__c lead : newLeads) {
            if (!String.isBlank(lead.Phone__c) && existingLeads.containsKey(lead.Phone__c) &&
                (lead.Phone__c != existingLeads.get(lead.Phone__c).Phone__c)) {
                lead.Phone__c.addError('Phone number already exists in a different record.');
            }
        }
    }*/
    
    
}