force-app/main/default/objects/AvanaTrigger__c/AvanaTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AvanaTrigger</label>
</CustomObject>

force-app/main/default/objects/AvanaTrigger__c/fields/EnquiryTrigger__c.field-meta.xml
<CustomField>
    <fullName>EnquiryTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>EnquiryTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address Landmark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Distributor_Email__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Email__c</fullName>
    <label>Distributor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_First_Name__c</fullName>
    <label>Farmer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Last_Name__c</fullName>
    <label>Farmer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Middle_Name__c</fullName>
    <label>Farmer Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsConverted (old)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lost_Lead__c.field-meta.xml
<CustomField>
    <fullName>Lost_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lost Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <inlineHelpText>Mobile Number Should be 10 Digits</inlineHelpText>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Enquiry Created</fullName>
            </value>
            <value>
                <fullName>Not Converted</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Lost_to__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Lost_to__c</fullName>
    <label>Sale Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Price too high</fullName>
            </value>
            <value>
                <fullName>Bad review of product</fullName>
            </value>
            <value>
                <fullName>Delivery time too long</fullName>
            </value>
            <value>
                <fullName>Bad reputation of dealer/distributor</fullName>
            </value>
            <value>
                <fullName>Wanted to buy on credit</fullName>
            </value>
            <value>
                <fullName>Already lined with different company</fullName>
            </value>
            <value>
                <fullName>Not available in area</fullName>
            </value>
            <value>
                <fullName>Not available with preferred retailer</fullName>
            </value>
            <value>
                <fullName>Subsidy not coming on time</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Contact Later</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnquiryTriggerHandler_Test.cls
@isTest
public class EnquiryTriggerHandler_Test {
    public static testMethod void EnquiryTriggerMethod(){
        AvanaTrigger__c tokenCustomSetting = new AvanaTrigger__c();         
        tokenCustomSetting.Name = 'EnquiryTrigger__c';        
        tokenCustomSetting.EnquiryTrigger__c = true;        
        insert tokenCustomSetting;
        
        Lead__c ld= new Lead__c();
        ld.Farmer_Last_Name__c='H';
        ld.Farmer_Middle_Name__c='s';
        ld.Farmer_First_Name__c='S';
        ld.Address__c='indiranagar';
        ld.Mobile_Number__c='9876594421';
        ld.Stages__c='New';
        ld.Distributor_Email__c='abac@gmail.com';
        ld.IsConverted__c=false;
        ld.Lost_Lead__c=true;
        insert ld;
        
        Opportunity__c opp = new Opportunity__c();
        opp.Lead__c=ld.Id;
        opp.Opportunity_Stage__c='Not Interested';
        opp.Opportunity_Lost_to__c='Price too high';
        insert opp;
        
        opp.Opportunity_Stage__c='Closed Without OTP';
        update opp;
    }
}