force-app/main/default/objects/AvanaTrigger__c/AvanaTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AvanaTrigger</label>
</CustomObject>

force-app/main/default/objects/AvanaTrigger__c/fields/ComplaintTrigger__c.field-meta.xml
<CustomField>
    <fullName>ComplaintTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ComplaintTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>Com-{000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint__c/fields/Complaint_Source__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Source__c</fullName>
    <label>Farmer complained to</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Toll Free Number</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Quality Team</fullName>
            </value>
            <value>
                <fullName>Sales team</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CRM team</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Complaint__c/fields/Complaint_Type__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Type__c</fullName>
    <label>Complaint Type old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Faulty fabric - Manufacturing</fullName>
            </value>
            <value>
                <fullName>Damage Fabric - Transport/Logistics</fullName>
            </value>
            <value>
                <fullName>Supply shortage</fullName>
            </value>
            <value>
                <fullName>Delay in Supply</fullName>
            </value>
            <value>
                <fullName>Leakage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Complaint__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Complaints</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Complaints</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed without OTP</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer__c/Dealer__c.object-meta.xml
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 Digits number.</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipLabel>Dealers</relationshipLabel>
    <relationshipName>Dealers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Farmer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address Landmark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Alternate_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile_No__c</fullName>
    <inlineHelpText>10 digits Mobile No</inlineHelpText>
    <label>Alternate Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Distributor_Email__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Email__c</fullName>
    <label>Distributor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_First_Name__c</fullName>
    <label>Farmer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Farmer_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Middle_Name__c</fullName>
    <label>Farmer Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <inlineHelpText>Mobile Number Should be 10 Digits</inlineHelpText>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Products_Interested__c.field-meta.xml
<CustomField>
    <fullName>Products_Interested__c</fullName>
    <label>Products Interested</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jalasanchay</fullName>
            </value>
            <value>
                <fullName>Retail Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Enquiry Created</fullName>
            </value>
            <value>
                <fullName>Not Converted</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tehsil</label>
    <referenceTo>Tehsil__c</referenceTo>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>Prd-{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Enquiry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Dealer__r.Distributor__r.Name</formula>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Product Information</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Lost_to__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Lost_to__c</fullName>
    <label>Sale Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Price too high</fullName>
            </value>
            <value>
                <fullName>Bad review of product</fullName>
            </value>
            <value>
                <fullName>Delivery time too long</fullName>
            </value>
            <value>
                <fullName>Bad reputation of dealer/distributor</fullName>
            </value>
            <value>
                <fullName>Wanted to buy on credit</fullName>
            </value>
            <value>
                <fullName>Already lined with different company</fullName>
            </value>
            <value>
                <fullName>Not available in area</fullName>
            </value>
            <value>
                <fullName>Not available with preferred retailer</fullName>
            </value>
            <value>
                <fullName>Subsidy not coming on time</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Contact Later</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tehsil__c.field-meta.xml
<CustomField>
    <fullName>Tehsil__c</fullName>
    <formula>Lead__r.Tehsil__r.Name</formula>
    <label>Tehsil</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/recordTypes/Jalasanchay.recordType-meta.xml
<RecordType>
    <fullName>Jalasanchay</fullName>
    <active>true</active>
    <label>Jalasanchay</label>
</RecordType>

force-app/main/default/objects/Tehsil__c/Tehsil__c.object-meta.xml
<CustomObject>
    <label>Tehsil</label>
    <nameField>
        <label>Tehsil Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tehsils</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tehsil__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer__c</referenceTo>
    <relationshipLabel>Tehsils</relationshipLabel>
    <relationshipName>Tehsils</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComplainTTriggerHandler_TestClass.cls
@isTest
public class ComplainTTriggerHandler_TestClass {
    public static testMethod void ComplainTTriggerHandler_Test()
    {  
        AvanaTrigger__c tokenCustomSetting = new AvanaTrigger__c();         
        tokenCustomSetting.Name = 'ComplaintTrigger__c';        
        tokenCustomSetting.ComplaintTrigger__c = true;        
        insert tokenCustomSetting;
        
         Distributor__c dd=new Distributor__c();
        dd.Name='test';
        dd.Distributor_Email__c='abac@gmail.com';
        insert dd;
        
        Dealer__c Dl= new Dealer__c();
        Dl.Name='sangv';
        Dl.Distributor__c=dd.id;
        insert Dl;
        
        Tehsil__c Tl= new Tehsil__c();
        Tl.Dealer__c=Dl.Id;
        Tl.Name='hgfg';
        insert Tl;
        
        Lead__c ld=new Lead__c();
        ld.Farmer_First_Name__c='test';
        ld.Mobile_Number__c='1234567890';
        ld.Tehsil__c=Tl.id;
        ld.Products_Interested__c='Jalasanchay';
        insert ld;
        
        Account acc=new Account();
        acc.name='avana';
        acc.Farmer_First_Name__c='Pritam';
        acc.Farmer_Middle_Name__c='A';
        acc.Address__c='indiranagar';
        acc.Phone='9876594421';
        acc.Alternate_Mobile_No__c='9778906453';
        acc.Aadhar_Number__c='123434345656';
        acc.Pin_Code__c='588899';
        acc.Dealer__c=Dl.id;
        insert acc;
        
        Opportunity__c opp = new Opportunity__c();
        opp.Lead__c=ld.Id;
        opp.Opportunity_Stage__c='Not Interested'; 
        opp.Opportunity_Lost_to__c='Price too high';
        insert opp;
        
        list<Complaint__c> cmp=new list<Complaint__c>();
        Complaint__c cmpt=new Complaint__c();
        cmpt.Complaint_Type__c='Faulty fabric - Manufacturing';
        cmpt.Complaint_Source__c='Toll Free Number';
        cmpt.Description__c='test';
        cmpt.Stages__c='Ongoing';
        cmpt.Complaint_Due_to__c = 'Company';
        //cmpt.Customer__c=acc.id;
        cmpt.Enquiry__c=opp.id;
        insert cmpt;
        system.debug('cmpt'+cmpt);
       
        
        
        
        
        Test.startTest();
        cmpt.Stages__c='Closed without OTP';
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorOtp());
        database.update(cmpt,false);
		       
        test.stopTest();
        system.debug('updatecmpt'+cmpt);
        
        
       
    }
    


}