force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>SKU Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Customer__c/Retail_Customer__c.object-meta.xml
<CustomObject>
    <label>Retail Customer</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Retail Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Customer__c/fields/GST_Number__c.field-meta.xml
<CustomField>
    <fullName>GST_Number__c</fullName>
    <label>GST Number</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/Retail_Inventory__c.object-meta.xml
<CustomObject>
    <label>Retail Inventory</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Inventory__c/fields/Instock__c.field-meta.xml
<CustomField>
    <fullName>Instock__c</fullName>
    <label>Instock</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Retailer_Price__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Price__c</fullName>
    <label>Retailer Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse Code</label>
    <referenceTo>Retail_Warehouse__c</referenceTo>
    <relationshipLabel>Retail Inventories</relationshipLabel>
    <relationshipName>Retail_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Inventory__c/fields/Weight_kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_kg__c</fullName>
    <label>Weight (kg)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/Retail_Lead_Visit__c.object-meta.xml
<CustomObject>
    <label>Retail Lead Visit</label>
    <nameField>
        <displayFormat>RLV-{0000}</displayFormat>
        <label>Visit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Lead Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Linked_Customer__c.field-meta.xml
<CustomField>
    <fullName>Linked_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Customer</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead_Visit__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Lead Visits</relationshipLabel>
    <relationshipName>Retail_Lead_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/Retail_Order__c.object-meta.xml
<CustomObject>
    <label>Retail Order</label>
    <nameField>
        <displayFormat>RO-{0000}</displayFormat>
        <label>Retail Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Retail_Customer__c.field-meta.xml
<CustomField>
    <fullName>Retail_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Orders</relationshipLabel>
    <relationshipName>Retail_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exec Discount Approval</fullName>
                <label>Awaiting Discount Approval</label>
            </value>
            <value>
                <fullName>Awaiting Exec Approval</fullName>
                <label>Awaiting Credit Approval</label>
            </value>
            <value>
                <fullName>Awaiting Accounts</fullName>
                <label>Awaiting Accounts Approval</label>
            </value>
            <value>
                <fullName>Payment Approved</fullName>
            </value>
            <value>
                <fullName>Upload Packing List</fullName>
            </value>
            <value>
                <fullName>Packing List in Process</fullName>
            </value>
            <value>
                <fullName>Production Approved</fullName>
            </value>
            <value>
                <fullName>Ready For Dispatch</fullName>
                <label>Commercial : Ready For Dispatch</label>
            </value>
            <value>
                <fullName>Dispatched Awaiting Final Payment</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Awaiting Manager Approval</fullName>
                <isActive>false</isActive>
                <label>Awaiting Manager Approval</label>
            </value>
            <value>
                <fullName>Commercial : Instock - Prepare Invoice</fullName>
                <isActive>false</isActive>
                <label>Commercial : Instock - Prepare Invoice</label>
            </value>
            <value>
                <fullName>Confirm Stock Receipt</fullName>
                <isActive>false</isActive>
                <label>Confirm Stock Receipt</label>
            </value>
            <value>
                <fullName>Exec Credit Approval</fullName>
                <isActive>false</isActive>
                <label>Exec Credit Approval</label>
            </value>
            <value>
                <fullName>Exec Return Approval</fullName>
                <isActive>false</isActive>
                <label>Exec Return Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/Retail_Order_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Order Product</label>
    <nameField>
        <displayFormat>ROP-{0000}</displayFormat>
        <label>Retail Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Order Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Order_Product__c/fields/Hole_Spacing__c.field-meta.xml
<CustomField>
    <fullName>Hole_Spacing__c</fullName>
    <label>Hole Spacing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/HoleType__c.field-meta.xml
<CustomField>
    <fullName>HoleType__c</fullName>
    <label>Hole Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Straight</fullName>
            </value>
            <value>
                <fullName>Parallel</fullName>
            </value>
            <value>
                <fullName>Zigzag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Kg_Rate__c.field-meta.xml
<CustomField>
    <fullName>Kg_Rate__c</fullName>
    <label>Kg Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Retail_Product__c</referenceTo>
    <relationshipLabel>Retail Order Products</relationshipLabel>
    <relationshipName>Retail_Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Order Products</relationshipLabel>
    <relationshipName>Retail_Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Retail_Order__c.field-meta.xml
<CustomField>
    <fullName>Retail_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retail Order</label>
    <referenceTo>Retail_Order__c</referenceTo>
    <relationshipLabel>Retail Order Products</relationshipLabel>
    <relationshipName>Retail_Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Std_Pkg_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Std_Pkg_Sizes__c</fullName>
    <label>Std Pkg Sizes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Order_Product__c/fields/Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_Kg__c</fullName>
    <label>Weight(Kg)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/Retail_Product__c.object-meta.xml
<CustomObject>
    <label>Retail Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Product__c/fields/Retail_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Retail_Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Products</relationshipLabel>
    <relationshipName>Retail_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Product__c/fields/Std_Package_Size__c.field-meta.xml
<CustomField>
    <fullName>Std_Package_Size__c</fullName>
    <label>Std Package Size</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Product_Group__c/Retail_Product_Group__c.object-meta.xml
<CustomObject>
    <label>Retail Product Group</label>
    <nameField>
        <label>Product Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Product_Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avana Tank</fullName>
    </customValue>
    <customValue>
        <fullName>Biofloc Tank</fullName>
    </customValue>
    <customValue>
        <fullName>Leno Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Mulch Film</fullName>
    </customValue>
    <customValue>
        <fullName>Murughas Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Pond Liner</fullName>
    </customValue>
    <customValue>
        <fullName>Tarpaulin</fullName>
    </customValue>
    <customValue>
        <fullName>Thread</fullName>
    </customValue>
    <masterLabel>Product Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewOverrideOrderController.cls
public class NewOverrideOrderController {
    
    @AuraEnabled
    public static String insertOrderWithProduct(List<Retail_Order_Product__c> productList, Retail_Order__c order) {
        try {
             OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'surender@dhruvsoft.com'];
            List<Retail_Order_Product__c> lstiv = new List<Retail_Order_Product__c>();
            System.debug('productList'+productList);
            System.debug('order'+order);
            
            if (Schema.sObjectType.Retail_Order__c.isCreateable()) {
                
                    insert order;
                     System.debug('After Insert order 14 '+order);
               
               
            }
            Retail_Order__c orderDetails=[SELECT Id, Name,Status__c FROM Retail_Order__c where Id=:order.Id];
            System.debug('order 14'+order);
             System.debug('order 14 Name'+order.Name);
           /* if(order.Status__c=='Exec Discount Approval'){
              
            
            Messaging.SingleEmailMessage mymail = new Messaging.SingleEmailMessage();
            String[] toaddresses = new String[] {'shashirekha@dhruvsoft.com'}; 
                mymail.setToAddresses(toAddresses);
            mymail.setSubject('Order Status');
            mymail.setPlainTextBody('Order Status is Changes to '+order.Status__c);
            mymail.setOrgWideEmailAddressId(owea.get(0).Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mymail });   
            }
            
           else if(order.Status__c=='Awaiting Exec Approval'){
                System.debug('Testing Else if 26');
             
            Messaging.SingleEmailMessage mymail = new Messaging.SingleEmailMessage();
            String[] toaddresses = new String[] {'shashirekha@dhruvsoft.com'}; 
                //mymail.setToAddresses(toAddresses);
            String subject = order.Name+' Order Received - '+order.Status__c;
           mymail.setSubject(subject);
			mymail.setOrgWideEmailAddressId(owea.get(0).Id);
            String EmailBody = '<html><body>';
EmailBody +='Dear '+order.Owner.name+',<br/>';
			EmailBody +='<p></p>';
			EmailBody +='Your order '+ order.Name+' is currently awaiting credit approval. Please continue to check the status of your order on this page : <a href="'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+order.Id+'" target="_blank">Order</a><br/>';
			EmailBody +='<p></p>';
			EmailBody +='<b>Warm Regards,</b><br/>';
			EmailBody +='<b>Avana Operations Team</b><br/>';
			EmailBody += '</body></html>';
			mymail.setHtmlBody(EmailBody);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mymail });   
            }
            
            else if(order.Status__c=='Awaiting Accounts'){
                           
            Messaging.SingleEmailMessage mymail = new Messaging.SingleEmailMessage();
            String[] toaddresses = new String[] {'shashirekha@dhruvsoft.com'}; 
                mymail.setToAddresses(toAddresses);
            mymail.setSubject('Order Status');
            mymail.setPlainTextBody('Order Status is Changes to '+order.Status__c);
            mymail.setOrgWideEmailAddressId(owea.get(0).Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mymail });   
            }*/
             if(order.Retail_Customer__c!=null){
               String CustomerId=order.Retail_Customer__c;
               Date OrderDate=order.Order_Date__c;
                System.debug('order.Retail_Customer__c'+order.Retail_Customer__c);
                Retail_Customer__c CustomerDetails=[Select Id,Last_Order_Date__c from Retail_Customer__c where Id=:CustomerId limit 1];
                if(OrderDate!=null){
                    CustomerDetails.Last_Order_Date__c=OrderDate;
                    update CustomerDetails;
                }
                
            }
            
            String orderId = order.Id;
            try{
                for (Retail_Order_Product__c pro : productList) {
                    Retail_Order_Product__c product = new Retail_Order_Product__c();
                    System.debug('pro===='+pro.Name);
                    product.Retail_Order__c = order.Id;
                    product.Product_Group__c = pro.Product_Group__c;
                    product.Product__c = pro.Product__c;
                    product.Net_Total_for_Product__c = pro.Net_Total_for_Product__c;
                    product.Product_Discount__c = pro.Product_Discount__c;
                    product.Sub_Total__c = pro.Sub_Total__c;
                    product.Weight_Kg__c = pro.Weight_Kg__c;
                    product.Discounted_Kg_Rate__c = pro.Discounted_Kg_Rate__c;
                    product.Kg_Rate__c = pro.Kg_Rate__c;
                    product.Unit_Price__c = pro.Unit_Price__c;
                    product.Discounted_Unit_Price__c = pro.Discounted_Unit_Price__c;
                    product.Quantity__c = pro.Quantity__c;
                    product.Std_Pkg_Sizes__c = pro.Std_Pkg_Sizes__c;
                    product.Hole_Spacing__c = pro.Hole_Spacing__c;
                    product.HoleType__c = pro.HoleType__c;
                    lstiv.add(product);
                }
                if (!lstiv.isEmpty() && Schema.sObjectType.Retail_Order_Product__c.isCreateable()) {
                    insert lstiv;
                }
            }
            catch (Exception e) {
                throw new AuraHandledException(e.getMessage());
            }
            
            return orderId;
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String upsertOrder(List<Retail_Order_Product__c> productList , Retail_Order__c order, List<Retail_Order_Product__c> removeLineItemIds) {
        try {
            System.debug('order' + order);
            System.debug('order Id' + order.Id);
            System.debug('productList1========' + productList);
            if(order.Id!=null){
                 System.debug('order Id' + order.Id);
                update order;
            }
            System.debug('productList2======' + productList.size());
            if(productList.size()>0){
                System.debug('productList3======' + productList.size());
                if (Schema.sObjectType.Retail_Order_Product__c.isUpdateable() || Schema.sObjectType.Retail_Order_Product__c.isCreateable()) {
                     System.debug('productList3======' + productList.size());
                    System.debug('productList Id==123=='+productList[0].Id);
                    upsert productList;
                }
            }
            String orderId = order.Id;
             System.debug('orderId' + orderId);
           if (removeLineItemIds.size() > 0) {
                 System.debug('removeLineItemIds======' + removeLineItemIds.size());
                if (Schema.sObjectType.Retail_Order_Product__c.isDeletable()) {
                    delete removeLineItemIds;
                }
            }
            
            return orderId;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Retail_Order_Product__c> fetchProductList(String recordId) {
        System.debug('recordId55'+recordId);
        return [select Id,Retail_Order__c,Discounted_Kg_Rate__c, Discounted_Unit_Price__c, Hole_Spacing__c, HoleType__c, Kg_Rate__c, Name, Net_Total_for_Product__c, Product__c, Product_Discount__c, Product_Group__c, Quantity__c,Std_Pkg_Sizes__c, Sub_Total__c, Weight_Kg__c,Unit_Price__c from Retail_Order_Product__c where Retail_Order__c =:recordId];
    }
     @AuraEnabled(cacheable=true)
    public static String getPrevoiusOrders(String customerId){
        
		List<Retail_Order__c> orderDetails=[select id,Retail_Customer__c from Retail_Order__c where Retail_Customer__c=:customerId];  
        if(orderDetails.size()>0){
             return orderDetails[0].Id;
        }
        return null;
    }
   @AuraEnabled(cacheable=true)
    public static Retail_Product__c getProductDetails(String productId){
		Retail_Product__c productDetails=[select id,Std_Package_Size__c from Retail_Product__c where id=:productId limit 1];  
        if(productDetails!=null){
             return productDetails;
        }
        return null;
    } 
     @AuraEnabled(cacheable=true)
    public static Retail_Inventory__c getUnitPrice(String productId,String dispatchWarehouseId){
        if(productId!=null && dispatchWarehouseId!=null){
          List<Retail_Inventory__c> inventoryDetails=[Select id,Product_Name__c,Instock__c,Warehouse_Code__c,Retailer_Price__c from Retail_Inventory__c where (Product_Name__c =:productId) and (Warehouse_Code__c =:dispatchWarehouseId)]; 
        if(inventoryDetails.size()>0){
             return inventoryDetails[0];
        }  
        }
		
        return null;
    } 
     @AuraEnabled(cacheable=true)
    public static list<sObject> fetchLookupData(string searchKey , string sObjectApiName ,string productGroupId) {    
        List <sObject> returnList = new List <sObject>();
        string sWildCardText = '%' + searchKey + '%';
        string sQuery = 'Select Id,Name From ' + sObjectApiName + ' Where Name Like : sWildCardText and Retail_Product_Group__c=:productGroupId order by createdDate DESC';
        for (sObject obj: database.query(sQuery)) {
            returnList.add(obj);
        }
        return returnList;
    }
     @AuraEnabled(cacheable=true)
    public static Boolean getMulchProductGroup(String productGroupId){
        Boolean isMulchFilm=false;
		List<Retail_Product_Group__c> productDetails=[select id,Name from Retail_Product_Group__c where (id=:productGroupId) and (Name='Avana Mulch Film')];  
        System.debug('productDetails'+productDetails);
        if(productDetails.size()>0){
            isMulchFilm=true;
             return isMulchFilm;
        }
        return isMulchFilm;
    }
    @AuraEnabled(cacheable=true)
    public static Retail_Customer__c getCustomerDetails(String customerId){
        Retail_Customer__c customerDetails=new Retail_Customer__c();
        if(customerId!=null){
         customerDetails=[select Id,PAN_Number__c,GST_Number__c from Retail_Customer__c where id=:customerId limit 1];  
        if(customerDetails!=null){
             return customerDetails;
        }   
        }
		
        return customerDetails;
    }
    @AuraEnabled(cacheable=true)
    public static List<Retail_Lead_Visit__c> getLeadVisitOptions(String customerId){
       List<Retail_Lead_Visit__c> leadVisitDetails=new List<Retail_Lead_Visit__c>();
        if(customerId!=null){
        leadVisitDetails=[select Id,Linked_Customer__c,Name from Retail_Lead_Visit__c where Linked_Customer__c=:customerId]; 
            System.debug('leadVisitDetails.size'+leadVisitDetails.size());
        if(leadVisitDetails.size()>0){
             return leadVisitDetails;
        }   
        }
        return leadVisitDetails;
    }
     @AuraEnabled(cacheable=true)
    public static List<Retail_Product__c> getProductOptions(String productGroupId){
       List<Retail_Product__c> productDetails=new List<Retail_Product__c>();
        if(productGroupId!=null){
        productDetails=[select Id,Retail_Product_Group__c,Product_Name__c,Status__c from Retail_Product__c where (Retail_Product_Group__c=:productGroupId) AND (Status__c='Active')]; 
            System.debug('productDetails.size'+productDetails.size());
        if(productDetails.size()>0){
             return productDetails;
        }   
        }
        return productDetails;
    }
    @AuraEnabled(cacheable=true)
    public static Retail_Lead_Visit__c getLeadVisitName(String leadVisitId){
       Retail_Lead_Visit__c getLeadVisitName=new Retail_Lead_Visit__c();
        if(leadVisitId!=null){
        getLeadVisitName=[select Id,Name from Retail_Lead_Visit__c where Id=:leadVisitId limit 1]; 
            System.debug('getLeadVisitName.size'+getLeadVisitName);
        if(getLeadVisitName!=null){
             return getLeadVisitName;
        }   
                         }
        return null;
                         
    }
     @AuraEnabled(cacheable=true)
    public static Retail_Product__c getProductName(String productId){
       Retail_Product__c getProduct=new Retail_Product__c();
        if(productId!=null){
        getProduct=[select Id,Name,Product_Name__c from Retail_Product__c where Id=:productId limit 1]; 
            System.debug('getProduct.size'+getProduct);
        if(getProduct!=null){
             return getProduct;
        }   
                         }
        return null;
                         
    }                    
                         
}