force-app/main/default/objects/Avana_Api_details__mdt/Avana_Api_details__mdt.object-meta.xml
<CustomObject>
    <label>Avana Api detail</label>
    <pluralLabel>Avana Api details</pluralLabel>
</CustomObject>

force-app/main/default/objects/Avana_Api_details__mdt/fields/msg_type__c.field-meta.xml
<CustomField>
    <fullName>msg_type__c</fullName>
    <description>What kind of msg u want to send 4 for unicode 1 for normal text</description>
    <label>msg_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avana_Api_details__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avana_Api_details__mdt/fields/smsfrom__c.field-meta.xml
<CustomField>
    <fullName>smsfrom__c</fullName>
    <description>smsfrom is the registered name of api details</description>
    <label>smsfrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avana_Api_details__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>Com-{000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint__c/fields/OTP_Language__c.field-meta.xml
<CustomField>
    <fullName>OTP_Language__c</fullName>
    <label>OTP Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hindi</fullName>
                <default>true</default>
                <label>Hindi</label>
            </value>
            <value>
                <fullName>Kannada</fullName>
            </value>
            <value>
                <fullName>Marathi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Detail__c/Integration_Detail__c.object-meta.xml
<CustomObject>
    <label>Integration Detail</label>
    <nameField>
        <label>OTP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Detail__c/fields/Complaint__c.field-meta.xml
<CustomField>
    <fullName>Complaint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Complaint</label>
    <referenceTo>Complaint__c</referenceTo>
    <relationshipLabel>Integration Details</relationshipLabel>
    <relationshipName>Integration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Detail__c/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <inlineHelpText>10 Digits Mobile Number</inlineHelpText>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Integration_Detail__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OTPSend.cls
public class OTPSend {
    @future (callout=true)
    public static void sendOtp(String phone,string objId){
        Avana_Api_details__mdt apiDetail = [select Username__c,Password__c,smsfrom__c,msg_type__c from Avana_Api_details__mdt where MasterLabel='AvanaOTP'];
        System.debug('apidetails of metadata:::'+apiDetail);
        Complaint__c cc=[select id,OTP_Language__c from Complaint__c where id=:objId limit 1];
        system.debug('otp language::::::'+cc.OTP_Language__c);
        String msgdetails=OTPLangugaeFetch.getlablelang(cc.OTP_Language__c);
        System.debug('fetched message:::::'+msgdetails);
        String otp = String.valueOf((Integer)Math.floor(Math.random()*1000000)); //generating 6 digit OTP
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        String smsfrom = apiDetail.smsfrom__c;
        String username = apiDetail.username__c;
        String password = apiDetail.password__c;
        string msgtype = apiDetail.msg_type__c;
        String endpoint;
        if(Test.isRunningTest()){
            endpoint='http://websms.one97.net/sendsms/sms_request.php?username=EmmbiIndust&password=embi123inds&smsfrom=TestAM&content=नमस्कार%20ग्राहक,%20आपण%20समाधानी%20असल्यास%20कृपया%20आमच्या%20कार्यकारीला%20ओटीपी%20%20द्या,%20अन्यथा%20ओटीपी%20प्रदान%20करू%20नका%2078155&receiver=9876594421&msg_type=4';
        }else{
            System.debug('inisde else:::');
            endpoint='http://websms.one97.net/sendsms/sms_request.php?username='+username+'&password='+password+'&smsfrom='+smsfrom+'&content='+msgdetails.replaceAll(' ','%20')+'%20'+ otp+'&receiver='+phone+'&msg_type='+msgtype;
        }
        system.debug('endpoint details formation:::'+endpoint);
        req.setEndpoint(endpoint);
        req.setMethod('GET');
        HttpResponse res = http.send(req);
        System.debug(endpoint);
        System.debug('the otp is '+otp);
        System.debug(res.getStatusCode());
        System.debug(res.getBody());
        
        if(res.getStatusCode()==200) {
            Integration_Detail__c msg = new Integration_Detail__c();
            msg.Name = otp;
            msg.Mobile_Phone__c = phone;
            msg.Response_Body__c = res.getBody();
            msg.Complaint__c=objId;
            insert msg;
        }
 
    
    }
}