force-app/main/default/objects/Retail_District__c/Retail_District__c.object-meta.xml
<CustomObject>
    <label>Retail District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>Retail_State__c</referenceTo>
    <relationshipLabel>Retail Districts</relationshipLabel>
    <relationshipName>Retail_Districts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/Retail_Lead__c.object-meta.xml
<CustomObject>
    <label>Retail Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Lead__c/fields/InterestedProducts__c.field-meta.xml
<CustomField>
    <fullName>InterestedProducts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interested Products</label>
    <referenceTo>Retail_Product_Group__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Is_Converted__c.field-meta.xml
<CustomField>
    <fullName>Is_Converted__c</fullName>
    <label>Is Converted?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Last_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Order_Date__c</fullName>
    <description>If the Customer Id field in Lead is not null then the Last order date will be the customer last order date</description>
    <formula>IF(NOT(ISBLANK(Link_Customer_Id__c)),Link_Customer_Id__r.Last_Order_Date__c , NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner__c</fullName>
    <formula>CreatedBy.Username</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kisan Exhibition &apos;22</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Link_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Link_Customer_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Connect the customer and lead data for this client</inlineHelpText>
    <label>Link Customer Id</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Leads (Link Customer Id)</relationshipLabel>
    <relationshipName>Retail_Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Pending_Data__c.field-meta.xml
<CustomField>
    <fullName>Pending_Data__c</fullName>
    <label>Pending Data</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seller Id</fullName>
            </value>
            <value>
                <fullName>Customer Id</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Retail_Lead_District__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>Retail_District__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Retail_Lead_Taluka__c.field-meta.xml
<CustomField>
    <fullName>Retail_Lead_Taluka__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Taluka</label>
    <referenceTo>Retail_Taluka__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/RetailLeadState__c.field-meta.xml
<CustomField>
    <fullName>RetailLeadState__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>Retail_State__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Seller_Name__c.field-meta.xml
<CustomField>
    <fullName>Seller_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Avana Retail customer/customers from which this lead is purchasing Avana Retail  products</inlineHelpText>
    <label>Seller Name</label>
    <referenceTo>Retail_Customer__c</referenceTo>
    <relationshipLabel>Retail Leads</relationshipLabel>
    <relationshipName>Retail_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Lead__c/fields/Village__c.field-meta.xml
<CustomField>
    <fullName>Village__c</fullName>
    <label>Village</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_State__c/Retail_State__c.object-meta.xml
<CustomObject>
    <label>Retail State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Taluka__c/Retail_Taluka__c.object-meta.xml
<CustomObject>
    <label>Retail Taluka</label>
    <nameField>
        <label>Taluka Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Talukas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Taluka__c/fields/Add_District__c.field-meta.xml
<CustomField>
    <fullName>Add_District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Add District</label>
    <referenceTo>Retail_District__c</referenceTo>
    <relationshipLabel>Retail Talukas</relationshipLabel>
    <relationshipName>Retail_Talukas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RetailLeadCls.cls
public with sharing class RetailLeadCls {
  /* public static List<Retail_Lead__c> retailLeadDataCapture() {
        List<Retail_Lead__c> leadData = [SELECT Id,Lead_Owner__c,Lead_Source__c,Name,Date__c,Lead_Type__c,Seller_Name__c,Lead_Name__c,Phone__c,RetailLeadState__r.Name,Retail_Lead_District__r.Name,Retail_Lead_Taluka__r.Name,Village__c,Is_Converted__c,Last_Order_Date__c,Sale_Type__c,Pending_Data__c,InterestedProducts__c FROM Retail_Lead__c];
        System.debug('leadData===>'+leadData);
        return leadData;
    }*/
    
     @AuraEnabled(cacheable=true)
     public static Retail_Lead__c getRetailLeadPhoneDetails(String phone,Id linkedCustomerId) {
         System.debug('phone==========='+phone);
        	Retail_Lead__c leadDetails=new Retail_Lead__c();
         if(phone!=null || phone!=''){
       List<Retail_Lead__c> leadDetails1=[SELECT Id,Phone__c,Link_Customer_Id__c FROM Retail_Lead__c WHERE Phone__c = :phone LIMIT 1];
         System.debug('leadDetails============'+leadDetails);
            if (leadDetails1.size()>0){
                leadDetails=leadDetails1[0];
             return leadDetails;
             }
             else{
                  return leadDetails;
             }
         }
        return leadDetails;
    }

    @AuraEnabled(cacheable=true)
     public static Retail_Lead__c getLeadDetails(Id masterId) {
         System.debug('masterId==========='+masterId);
         Retail_Lead__c leadDetails=new Retail_Lead__c();
         if(masterId!=null || masterId!=''){
       List<Retail_Lead__c> leadDetails1=[SELECT Id,Link_Customer_Id__c FROM Retail_Lead__c WHERE Link_Customer_Id__c = :masterId LIMIT 1];
         System.debug('leadDetails============'+leadDetails);
            if (leadDetails1.size()>0){
              leadDetails=leadDetails1[0];
             return leadDetails;
             }
             else{
                  return leadDetails;
             }
         }
        return leadDetails;
    }


@AuraEnabled(cacheable=true)
    public static List<Retail_District__c> getDistrictOptions(String stateId){
       List<Retail_District__c> districtDetails=new List<Retail_District__c>();
        if(stateId!=null){
        districtDetails=[SELECT Id, State__c, Name FROM Retail_District__c WHERE State__c=:stateId]; 
            System.debug('districtDetails.size'+districtDetails.size());
        if(districtDetails.size()>0){
             return districtDetails;
        }   
        }
        return districtDetails;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Retail_Taluka__c> getTalukaOptions(String districtId){
       List<Retail_Taluka__c> talukaDetails=new List<Retail_Taluka__c>();
        if(districtId!=null){
        talukaDetails=[SELECT Id, Add_District__c, Name FROM Retail_Taluka__c WHERE Add_District__c=:districtId]; 
            System.debug('talukaDetails.size'+talukaDetails.size());
        if(talukaDetails.size()>0){
             return talukaDetails;
        }   
        }
        return talukaDetails;
    }



}